# Appendix 1 {#appendix-1}

**Source of data related to different sectors**

| Sl No | Data Particulars | Source | Organisation |
|---------------|------------------------|---------------|------------------|
| 1\. | Estimates of area, production of important crops in India | <https://agriwelfare.gov.in/en/AgricultureEstimates> | MoAFW, GOI |
| 2\. | State level, district level aggregates of Area, production and productivity of principal crops in Kerala | <https://www.ecostat.kerala.gov.in> | Department of Economics & Statistics, Govt of Kerala |
| 3\. | District Wise Birth & Death Data, State Level Birth & Death Data | <https://www.ecostat.kerala.gov.in> | Department of Economics & Statistics, Govt of Kerala |
| 4\. | Minimum Support Price (MSP) Statement | <https://desagri.gov.in/statistics-type/latest-minimum-support-price-msp-statement/> | MoAFW, GOI |
| 5\. | Annual Survey of Industries, Index of Industrial Production, Household Consumer Expenditure, Economic Census, Enterprises Surveys, Periodic Labour Force Survey, CPI, etc | <https://www.mospi.gov.in/> | Ministry of Statistics and Programme Implementation |
| 6\. | State/UT wise estimates on population, health, family planning and nutrition related key indicators like fertility, mortality, maternal, child and adult health, women and child nutrition, domestic violence, etc | <https://main.mohfw.gov.in/> | Ministry of Health & Family Welfare |
| 7\. | Commodity wise export import data | <https://tradestat.commerce.gov.in>, <https://ftddp.dgciskol.gov.in> | Ministry of Commerce and Industry |
| 8\. | Data on various aspects of Indian economy, banking and finance | <https://www.rbi.org.in> | Reserve Bank of India |
| 9\. | Sustainable Development Goal report | <https://www.niti.gov.in/> | NITI Aayog |
