<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; Large sample test – TEXTBOOK OF AGRICULTURAL STATISTICS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./smallsampleTest.html" rel="next">
<link href="./hypothesisTest.html" rel="prev">
<link href="./images/cover.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d166b450ba5a8e9f7a0ab969bf6592c1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-84d67a869316b323f81d9f2a2c5555cd.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-bad6a7b64396174f9e6ce9f1aaf6e4b8.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="14&nbsp; Large sample test – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:description" content="">
<meta property="og:image" content="https://www.agrinoteskau.com/agstat-textbook.html/images/cover.jpg">
<meta property="og:site_name" content="TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:title" content="14&nbsp; Large sample test – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://www.agrinoteskau.com/agstat-textbook.html/images/papayalogo.png">
<meta name="twitter:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="541">
<meta name="twitter:image-width" content="956">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./largeSampletest.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Large sample test</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/sidebarcover.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEXTBOOK OF AGRICULTURAL STATISTICS</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basics of statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agstatindia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistics on agriculture</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical representation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Central tendency I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Central tendency II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dispersion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measures of dispersion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./skewness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Skewness and kurtosis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./association.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of association</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probabilitydist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampleSurvey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Sample survey</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesisTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./largeSampletest.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Large sample test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smallsampleTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Small sample tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./designofexperiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Design of experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uniformityTrials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Uniformity trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multipleComparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple comparison tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleFactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Single factor experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Analysis of covariance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./missingPlot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Missing plot analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendix</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Appendix 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Appendix 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_personalities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Notable personalities in the development of statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link active" data-scroll-target="#central-limit-theorem"><span class="header-section-number">14.1</span> Central Limit Theorem</a></li>
  <li><a href="#z-test" id="toc-z-test" class="nav-link" data-scroll-target="#z-test"><span class="header-section-number">14.2</span> Z test</a>
  <ul class="collapse">
  <li><a href="#sec-decision" id="toc-sec-decision" class="nav-link" data-scroll-target="#sec-decision"><span class="header-section-number">14.2.1</span> Decision rule for the Z test</a></li>
  </ul></li>
  <li><a href="#test-for-a-single-population-proportion" id="toc-test-for-a-single-population-proportion" class="nav-link" data-scroll-target="#test-for-a-single-population-proportion"><span class="header-section-number">14.3</span> Test for a single population proportion</a></li>
  <li><a href="#test-for-equality-of-two-proportions" id="toc-test-for-equality-of-two-proportions" class="nav-link" data-scroll-target="#test-for-equality-of-two-proportions"><span class="header-section-number">14.4</span> Test for equality of two proportions</a></li>
  <li><a href="#test-for-a-single-population-mean" id="toc-test-for-a-single-population-mean" class="nav-link" data-scroll-target="#test-for-a-single-population-mean"><span class="header-section-number">14.5</span> Test for a single population mean</a>
  <ul class="collapse">
  <li><a href="#standard-deviation-is-known" id="toc-standard-deviation-is-known" class="nav-link" data-scroll-target="#standard-deviation-is-known"><span class="header-section-number">14.5.1</span> Standard deviation is known</a></li>
  <li><a href="#standard-deviation-is-unknown" id="toc-standard-deviation-is-unknown" class="nav-link" data-scroll-target="#standard-deviation-is-unknown"><span class="header-section-number">14.5.2</span> Standard deviation is unknown</a></li>
  </ul></li>
  <li><a href="#test-for-equality-of-two-means" id="toc-test-for-equality-of-two-means" class="nav-link" data-scroll-target="#test-for-equality-of-two-means"><span class="header-section-number">14.6</span> Test for equality of two means</a>
  <ul class="collapse">
  <li><a href="#standard-deviations-are-equal" id="toc-standard-deviations-are-equal" class="nav-link" data-scroll-target="#standard-deviations-are-equal"><span class="header-section-number">14.6.1</span> Standard deviations are equal</a></li>
  <li><a href="#standard-deviations-are-not-equal" id="toc-standard-deviations-are-not-equal" class="nav-link" data-scroll-target="#standard-deviations-are-not-equal"><span class="header-section-number">14.6.2</span> Standard deviations are not equal</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Large sample test</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>A sample with a size of 30 or more (<span class="math inline">\(n≥30\)</span>) is generally referred to as a large sample. Statistical methods based on such samples are known as large-sample tests. These methods rely on large-sample theory, which uses the Central Limit Theorem to approximate the sampling distribution of test statistics by the normal distribution, even when the population distribution is unknown.</p>
<section id="central-limit-theorem" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="central-limit-theorem"><span class="header-section-number">14.1</span> Central Limit Theorem</h2>
<p>The Central Limit Theorem states that when the sample size is sufficiently large (generally <span class="math inline">\(n≥30\)</span>), the sampling distribution of the sample mean is approximately normal, irrespective of the shape of the population distribution, provided the observations are independent and the population has a finite variance.</p>
<p>Mathematically, if a random sample of size <span class="math inline">\(n\)</span> is drawn from a population with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>, then as <span class="math inline">\(n\)</span> <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\infty\)</span>,</p>
<p><span id="eq-clt"><span class="math display">\[
\frac{\bar{X}-\mu}{\sigma/\sqrt{n}}
\xrightarrow{d}
N(0,1),
\tag{14.1}\]</span></span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\bar{X}\)</span> = sample mean</li>
<li><span class="math inline">\(\mu\)</span> = population mean</li>
<li><span class="math inline">\(\sigma\)</span> = population standard deviation</li>
<li><span class="math inline">\(N(0,1)\)</span> = standard normal distribution</li>
<li><span class="math inline">\(\xrightarrow{d}\)</span> denotes convergence in distribution. For now just think as “tends to follow” or “approaches” the standard normal distribution as the sample size increases.</li>
</ul>
</section>
<section id="z-test" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="z-test"><span class="header-section-number">14.2</span> Z test</h2>
<p>The <span class="math inline">\(Z\)</span>-test is a statistical test based on the standard normal distribution. It is used to test hypotheses about population means and proportions when the sample size is sufficiently large and the necessary assumptions are satisfied. The value of the test statistic is compared with the critical value from the standard normal distribution to decide whether the null hypothesis should be accepted or rejected.</p>
<p>The test statistic <span class="math inline">\(Z\)</span> is calculated from a large sample using appropriate formulas that we will discuss in the coming sections. <span class="math inline">\(Z\)</span> follows a standard normal distribution, <span class="math inline">\(Z \sim N(0,1)\)</span>. The following large sample tests are covered in this chapter:</p>
<ul>
<li><p>Test for a single proportion</p></li>
<li><p>Test for the equality of two proportions</p></li>
<li><p>Test for a single mean</p></li>
<li><p>Test for the equality of two means</p></li>
</ul>
<section id="sec-decision" class="level3" data-number="14.2.1">
<h3 data-number="14.2.1" class="anchored" data-anchor-id="sec-decision"><span class="header-section-number">14.2.1</span> Decision rule for the Z test</h3>
<p>Let <span class="math inline">\(Z\)</span> be the calculated value and <span class="math inline">\(\alpha\)</span> be the level of significance. We reject the null hypothesis if:</p>
<ul>
<li><p><span class="math inline">\(|Z| &gt; Z_{\alpha/2}\)</span> ; for a two-tailed test</p></li>
<li><p><span class="math inline">\(Z &gt; Z_{\alpha}\)</span> ; for a right-tailed test</p></li>
<li><p><span class="math inline">\(Z &lt; -Z_{\alpha}\)</span> ; for a left-tailed test</p></li>
</ul>
<p>The critical values of <span class="math inline">\(Z\)</span> for specified levels of significance are given in <a href="#tbl-zcrit" class="quarto-xref">Table&nbsp;<span>14.1</span></a>.</p>
<div id="tbl-zcrit" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-zcrit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.1: Critical values of the standard normal distribution
</figcaption>
<div aria-describedby="tbl-zcrit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(\alpha\)</span> (one tail)</th>
<th style="text-align: center;"><span class="math inline">\(Z\)</span> value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">1.282</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">1.645</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.025</td>
<td style="text-align: center;">1.960</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">2.326</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.005</td>
<td style="text-align: center;">2.576</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a two-tailed test at <span class="math inline">\(\alpha\)</span> = 0.05, we split the significance level equally between the two tails and use the value at <span class="math inline">\(\alpha/2\)</span> = 0.025, which is <span class="math inline">\(Z_{0.025}\)</span> = 1.960. Similarly, for a two-tailed test at <span class="math inline">\(\alpha\)</span> = 0.01 we use <span class="math inline">\(Z_{0.005}\)</span> = 2.576.</p>
</div>
</div>
</section>
</section>
<section id="test-for-a-single-population-proportion" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="test-for-a-single-population-proportion"><span class="header-section-number">14.3</span> Test for a single population proportion</h2>
<p>Consider a population with proportion <span class="math inline">\(P\)</span>, where <span class="math inline">\(P\)</span> is unknown. We take a random sample of size <span class="math inline">\(n\)</span> from the population and calculate the sample proportion <span class="math inline">\(p\)</span>. We want to test whether the population proportion <span class="math inline">\(P\)</span> is equal to a specified value <span class="math inline">\(P_0\)</span>, based on the sample proportion <span class="math inline">\(p\)</span>. Note here we always frame null hypothesis on population parameter and test using the sample statistics.</p>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P\)</span> = <span class="math inline">\(P_0\)</span></p>
<p>The alternative hypothesis may be either:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P\)</span> &lt; <span class="math inline">\(P_0\)</span> (left-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P\)</span> &gt; <span class="math inline">\(P_0\)</span> (right-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(P_0\)</span> (two-tailed alternative)</p>
<p>For this test, we calculate the test statistic <span class="math inline">\(Z\)</span> using the following formula:</p>
<p><span id="eq-zprop1"><span class="math display">\[Z = \frac{p - P_0}{\sqrt{P_0 Q_0 / n}} \tag{14.2}\]</span></span></p>
<p>where <span class="math inline">\(Q_0 = 1 - P_0\)</span>.</p>
<p>When the null hypothesis is true, this <span class="math inline">\(Z\)</span> follows a standard normal distribution with mean 0 and variance 1, <span class="math inline">\(Z \sim N(0,1)\)</span>.</p>
<p>The calculated value of <span class="math inline">\(Z\)</span> is then compared with the critical value of <span class="math inline">\(Z\)</span> from the table of the standard normal distribution. If the calculated value is higher than the table value, we reject the null hypothesis. If the calculated value is less than the table value, we conclude that we do not have enough evidence in our sample to reject the null hypothesis. See <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The standard error in the single-proportion test is computed using the null value <span class="math inline">\(P_0\)</span>, giving <span class="math inline">\(\sqrt{P_0 Q_0/n}\)</span>, because the test statistic is derived under the assumption that the null hypothesis is true. Some textbooks use the sample-based standard error <span class="math inline">\(\sqrt{pq/n}\)</span>; for large samples the two give very similar results.</p>
</div>
</div>
<div id="exm-prop1" class="theorem example">
<p><span class="theorem-title"><strong>Example 14.1</strong></span> A sample of 500 apples was taken from a large consignment and 60 were found to be bad. Test whether the proportion of bad apples in the consignment is 0.1 or not, at the 5% level of significance.</p>
<p><strong>Solution</strong></p>
<p>Sample size (<span class="math inline">\(n\)</span>) = 500</p>
<p>Proportion of bad apples in the sample (<span class="math inline">\(p\)</span>) = 60/500 = 0.12</p>
<p>We want to test whether the proportion of bad apples in the population is 0.1, so <span class="math inline">\(P_0\)</span> = 0.1 and <span class="math inline">\(Q_0\)</span> = 1 - 0.1 = 0.9.</p>
<p>The null hypothesis is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P\)</span> = 0.1</p>
<p>Since we want to test whether the proportion is 0.1 or not, we use a two-tailed test with the alternative hypothesis:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> 0.1</p>
<p>The level of significance is 5%, so <span class="math inline">\(\alpha\)</span> = 0.05.</p>
<p>Now we calculate <span class="math inline">\(Z\)</span> using <a href="#eq-zprop1" class="quarto-xref">Equation&nbsp;<span>14.2</span></a>:</p>
<p><span class="math display">\[Z = \frac{p - P_0}{\sqrt{P_0 Q_0 / n}} = \frac{0.12 - 0.1}{\sqrt{0.1 \times 0.9 / 500}} = \frac{0.02}{0.01342} = 1.49\]</span></p>
<p>Since it is a two-tailed test, we compare with the critical value at <span class="math inline">\(\alpha/2\)</span> = 0.025, which is 1.960 (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>). The calculated value (1.49) is less than the table value (1.960), so we do not have enough evidence to reject the null hypothesis. We conclude that there is insufficient evidence to say the proportion of bad apples differs from 0.1.</p>
</div>
<div id="exr-prop1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 14.1</strong></span> A random sample of 500 plants was taken from a large experimental field and 65 plants were found to be affected by yellowing disease. Test whether the proportion of affected plants differs significantly from 0.1. (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
</div>
</section>
<section id="test-for-equality-of-two-proportions" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="test-for-equality-of-two-proportions"><span class="header-section-number">14.4</span> Test for equality of two proportions</h2>
<p>Consider two populations with proportions <span class="math inline">\(P_1\)</span> and <span class="math inline">\(P_2\)</span>, both unknown. We take random samples of sizes <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> from the two populations respectively and calculate the sample proportions <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>. We want to test whether the population proportions <span class="math inline">\(P_1\)</span> and <span class="math inline">\(P_2\)</span> are equal, based on the sample proportions.</p>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P_1\)</span> = <span class="math inline">\(P_2\)</span></p>
<p>The alternative hypothesis may be either:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P_1\)</span> &lt; <span class="math inline">\(P_2\)</span> (left-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P_1\)</span> &gt; <span class="math inline">\(P_2\)</span> (right-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(P_2\)</span> (two-tailed alternative)</p>
<p>For this test, we calculate the test statistic <span class="math inline">\(Z\)</span> using the following formula:</p>
<p><span id="eq-zprop2"><span class="math display">\[Z = \frac{p_1 - p_2}{\sqrt{\widehat{P}\,\widehat{Q}\left( \dfrac{1}{n_1} + \dfrac{1}{n_2} \right)}} \tag{14.3}\]</span></span></p>
<p>where <span class="math inline">\(\widehat{P} = \dfrac{n_1 p_1 + n_2 p_2}{n_1 + n_2}\)</span> is the pooled proportion and <span class="math inline">\(\widehat{Q} = 1 - \widehat{P}\)</span>.</p>
<p>When the null hypothesis is true, this <span class="math inline">\(Z\)</span> follows a standard normal distribution, <span class="math inline">\(Z \sim N(0,1)\)</span>.</p>
<p>The calculated value of <span class="math inline">\(Z\)</span> is compared with the critical value of <span class="math inline">\(Z\)</span> from the standard normal table (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>). If the calculated value is higher than the table value, we reject the null hypothesis. Otherwise, we conclude that we do not have enough evidence to reject the null hypothesis.</p>
<div id="exm-prop2" class="theorem example">
<p><span class="theorem-title"><strong>Example 14.2</strong></span> In order to assess the adoption of a new variety of paddy by farmers, a survey was conducted in a locality. The survey covered 80 farmers with large land holdings and 250 farmers with small land holdings. It was observed that 50 of the large-holding farmers and 78 of the small-holding farmers adopted the new paddy variety. Test whether there is any significant difference in the adoption behaviour of the two groups of farmers. (<span class="math inline">\(\alpha\)</span> = 0.01)</p>
<p><strong>Solution</strong></p>
<p>Sample size of large-holding farmers (<span class="math inline">\(n_1\)</span>) = 80</p>
<p>Sample size of small-holding farmers (<span class="math inline">\(n_2\)</span>) = 250</p>
<p>Proportion of large-holding farmers who adopted the variety (<span class="math inline">\(p_1\)</span>) = 50/80 = 0.625</p>
<p>Proportion of small-holding farmers who adopted the variety (<span class="math inline">\(p_2\)</span>) = 78/250 = 0.312</p>
<p>We want to test whether the proportion is significantly different between the two populations, so:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P_1\)</span> = <span class="math inline">\(P_2\)</span></p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(P_2\)</span></p>
<p>This is a two-tailed test.</p>
<p><strong>Step 1</strong>: Calculate the pooled proportion.</p>
<p><span class="math display">\[\widehat{P} = \frac{n_1 p_1 + n_2 p_2}{n_1 + n_2} = \frac{80 \times 0.625 + 250 \times 0.312}{80 + 250} = 0.3879\]</span></p>
<p><span class="math display">\[\widehat{Q} = 1 - 0.3879 = 0.6121\]</span></p>
<p><strong>Step 2</strong>: The level of significance is 1%, so <span class="math inline">\(\alpha\)</span> = 0.01.</p>
<p><strong>Step 3</strong>: Calculate <span class="math inline">\(Z\)</span> using <a href="#eq-zprop2" class="quarto-xref">Equation&nbsp;<span>14.3</span></a>.</p>
<p><span class="math display">\[Z = \frac{p_1 - p_2}{\sqrt{\widehat{P}\,\widehat{Q}\left( \dfrac{1}{n_1} + \dfrac{1}{n_2} \right)}} = \frac{0.625 - 0.312}{\sqrt{0.3879 \times 0.6121 \left( \dfrac{1}{80} + \dfrac{1}{250} \right)}}\]</span></p>
<p><span class="math display">\[= \frac{0.313}{\sqrt{0.2374 \times 0.0165}} = \frac{0.313}{0.06258} = 5.00\]</span></p>
<p>Since it is a two-tailed test, we compare with the critical value at <span class="math inline">\(\alpha/2\)</span> = 0.005, which is 2.576 (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>). Since the calculated value (5.00) is greater than the table value (2.576), we reject the null hypothesis and conclude that there is a significant difference between the two population proportions.</p>
</div>
</section>
<section id="test-for-a-single-population-mean" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="test-for-a-single-population-mean"><span class="header-section-number">14.5</span> Test for a single population mean</h2>
<p>Consider a population with mean <span class="math inline">\(\mu\)</span>, where <span class="math inline">\(\mu\)</span> is unknown. We take a random sample of size <span class="math inline">\(n\)</span> from the population and calculate the sample mean <span class="math inline">\(\overline{x}\)</span>. We want to test whether the population mean <span class="math inline">\(\mu\)</span> is equal to a known constant <span class="math inline">\(\mu_0\)</span>, based on the sample mean.</p>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> = <span class="math inline">\(\mu_0\)</span></p>
<p>The alternative hypothesis may be either:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> &lt; <span class="math inline">\(\mu_0\)</span> (left-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> &gt; <span class="math inline">\(\mu_0\)</span> (right-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_0\)</span> (two-tailed alternative)</p>
<p>This test has two cases:</p>
<ul>
<li><p>Case when the population standard deviation <span class="math inline">\(\sigma\)</span> is known</p></li>
<li><p>Case when the population standard deviation <span class="math inline">\(\sigma\)</span> is unknown</p></li>
</ul>
<section id="standard-deviation-is-known" class="level3" data-number="14.5.1">
<h3 data-number="14.5.1" class="anchored" data-anchor-id="standard-deviation-is-known"><span class="header-section-number">14.5.1</span> Standard deviation is known</h3>
<p>When <span class="math inline">\(\sigma\)</span> is known, we calculate the test statistic <span class="math inline">\(Z\)</span> using the following formula:</p>
<p><span id="eq-zmean-known"><span class="math display">\[Z = \frac{\overline{x} - \mu_0}{\dfrac{\sigma}{\sqrt{n}}} \tag{14.4}\]</span></span></p>
<p>When the null hypothesis is true, this <span class="math inline">\(Z\)</span> follows a standard normal distribution, <span class="math inline">\(Z \sim N(0,1)\)</span>. The decision rule is given in <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>.</p>
<div id="exm-mean-known" class="theorem example">
<p><span class="theorem-title"><strong>Example 14.3</strong></span> A fertilizer packing unit is set to fill bags with a mean weight of 50 kg. From long experience the population standard deviation of the filling process is known to be 3.2 kg. A random sample of 64 bags was drawn and the mean weight was found to be 49.2 kg. Test whether the packing process is working at the intended mean weight of 50 kg, at the 5% level of significance.</p>
<p><strong>Solution</strong></p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> = 50</p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> 50 (two-tailed test)</p>
<p>Sample size (<span class="math inline">\(n\)</span>) = 64</p>
<p>Sample mean (<span class="math inline">\(\overline{x}\)</span>) = 49.2</p>
<p>Population standard deviation (<span class="math inline">\(\sigma\)</span>) = 3.2</p>
<p>Population mean (<span class="math inline">\(\mu_0\)</span>) = 50</p>
<p>Level of significance, <span class="math inline">\(\alpha\)</span> = 0.05</p>
<p>Since <span class="math inline">\(\sigma\)</span> is known, we use <a href="#eq-zmean-known" class="quarto-xref">Equation&nbsp;<span>14.4</span></a>:</p>
<p><span class="math display">\[Z = \frac{\overline{x} - \mu_0}{\dfrac{\sigma}{\sqrt{n}}} = \frac{49.2 - 50}{\dfrac{3.2}{\sqrt{64}}} = \frac{-0.8}{0.4} = -2.0\]</span></p>
<p>Since it is a two-tailed test, we compare <span class="math inline">\(|Z|\)</span> with the critical value at <span class="math inline">\(\alpha/2\)</span> = 0.025, which is 1.960 (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>). Since the calculated value (2.0) is greater than the table value (1.960), we reject the null hypothesis. We conclude that the packing process is not working at the intended mean weight of 50 kg.</p>
</div>
</section>
<section id="standard-deviation-is-unknown" class="level3" data-number="14.5.2">
<h3 data-number="14.5.2" class="anchored" data-anchor-id="standard-deviation-is-unknown"><span class="header-section-number">14.5.2</span> Standard deviation is unknown</h3>
<p>When <span class="math inline">\(\sigma\)</span> is unknown, it is replaced by its sample estimate <span class="math inline">\(s\)</span>, and we calculate the test statistic <span class="math inline">\(Z\)</span> using the following formula:</p>
<p><span id="eq-zmean-unknown"><span class="math display">\[Z = \frac{\overline{x} - \mu_0}{\dfrac{s}{\sqrt{n}}} \tag{14.5}\]</span></span></p>
<p>When the null hypothesis is true, this <span class="math inline">\(Z\)</span> follows a standard normal distribution, <span class="math inline">\(Z \sim N(0,1)\)</span>. The decision rule is given in <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>.</p>
<div id="exm-mean1" class="theorem example">
<p><span class="theorem-title"><strong>Example 14.4</strong></span> A sample of 900 items has a mean of 3.4 cm and a standard deviation of 2.61 cm. Test whether the population mean is 3.25 cm at the 5% significance level.</p>
<p><strong>Solution</strong></p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> = 3.25</p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> 3.25 (two-tailed test)</p>
<p>Sample size (<span class="math inline">\(n\)</span>) = 900</p>
<p>Sample mean (<span class="math inline">\(\overline{x}\)</span>) = 3.4</p>
<p>Sample standard deviation (<span class="math inline">\(s\)</span>) = 2.61</p>
<p>Population mean (<span class="math inline">\(\mu_0\)</span>) = 3.25</p>
<p>Level of significance, <span class="math inline">\(\alpha\)</span> = 0.05</p>
<p>Since <span class="math inline">\(\sigma\)</span> is unknown, we use <span class="math inline">\(s\)</span> in place of <span class="math inline">\(\sigma\)</span>, applying <a href="#eq-zmean-unknown" class="quarto-xref">Equation&nbsp;<span>14.5</span></a>:</p>
<p><span class="math display">\[Z = \frac{\overline{x} - \mu_0}{\dfrac{s}{\sqrt{n}}} = \frac{3.4 - 3.25}{\dfrac{2.61}{\sqrt{900}}} = \frac{0.15}{0.087} = 1.724\]</span></p>
<p>Since it is a two-tailed test, we compare with the critical value at <span class="math inline">\(\alpha/2\)</span> = 0.025, which is 1.960 (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>). Since the calculated value (1.724) is less than the table value (1.960), we do not have enough evidence to reject the null hypothesis. We conclude that there is insufficient evidence to say the mean differs from 3.25 cm.</p>
</div>
<div id="exr-mean1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 14.2</strong></span> From a paddy field a sample of 36 plants was selected at random and the panicle lengths were observed. The mean and standard deviation of these measurements were 18.7 cm and 1.25 cm respectively. Test whether the mean panicle length of paddy is 19 cm. (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
</div>
</section>
</section>
<section id="test-for-equality-of-two-means" class="level2" data-number="14.6">
<h2 data-number="14.6" class="anchored" data-anchor-id="test-for-equality-of-two-means"><span class="header-section-number">14.6</span> Test for equality of two means</h2>
<p>Let there be two normally distributed populations with means <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span> and standard deviations <span class="math inline">\(\sigma_1\)</span> and <span class="math inline">\(\sigma_2\)</span> respectively. Let samples of sizes <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> be taken from these populations, with sample means <span class="math inline">\(\overline{x}_1\)</span> and <span class="math inline">\(\overline{x}_2\)</span>. We want to test whether the two population means are significantly different, based on the sample means.</p>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1\)</span> = <span class="math inline">\(\mu_2\)</span></p>
<p>The alternative hypothesis may be either:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> &lt; <span class="math inline">\(\mu_2\)</span> (left-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> &gt; <span class="math inline">\(\mu_2\)</span> (right-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_2\)</span> (two-tailed alternative)</p>
<p>There are two cases under this test:</p>
<ul>
<li><p>Case when the population standard deviations are equal, <span class="math inline">\(\sigma_1 = \sigma_2 = \sigma\)</span></p></li>
<li><p>Case when the population standard deviations are not equal, <span class="math inline">\(\sigma_1 \neq \sigma_2\)</span></p></li>
</ul>
<section id="standard-deviations-are-equal" class="level3" data-number="14.6.1">
<h3 data-number="14.6.1" class="anchored" data-anchor-id="standard-deviations-are-equal"><span class="header-section-number">14.6.1</span> Standard deviations are equal</h3>
<p>When the population standard deviations are equal, we calculate the test statistic <span class="math inline">\(Z\)</span> using the following formula:</p>
<p><span id="eq-zmean2-equal"><span class="math display">\[Z = \frac{\overline{x}_1 - \overline{x}_2}{\sigma \sqrt{\dfrac{1}{n_1} + \dfrac{1}{n_2}}} \tag{14.6}\]</span></span></p>
<p>When the null hypothesis is true, this <span class="math inline">\(Z\)</span> follows a standard normal distribution, <span class="math inline">\(Z \sim N(0,1)\)</span>. The decision rule is the same as above (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>).</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the common <span class="math inline">\(\sigma\)</span> is unknown, it is replaced by its pooled estimate <span class="math inline">\(\sqrt{\dfrac{n_1 s_1^2 + n_2 s_2^2}{n_1 + n_2}}\)</span>, where <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are the sample sizes and <span class="math inline">\(s_1\)</span> and <span class="math inline">\(s_2\)</span> are the sample standard deviations.</p>
</div>
</div>
<div id="exm-mean2" class="theorem example">
<p><span class="theorem-title"><strong>Example 14.5</strong></span> The means of two large samples of sizes 1000 and 2000 members are 67.5 inches and 68 inches respectively. Can the samples be regarded as drawn from the same population with standard deviation 2.5 inches? (Test at the 5% significance level.)</p>
<p><strong>Solution</strong></p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1\)</span> = <span class="math inline">\(\mu_2\)</span></p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_2\)</span> (two-tailed test)</p>
<p>Sample size (<span class="math inline">\(n_1\)</span>) = 2000</p>
<p>Sample size (<span class="math inline">\(n_2\)</span>) = 1000</p>
<p>Sample mean of the first group (<span class="math inline">\(\overline{x}_1\)</span>) = 68</p>
<p>Sample mean of the second group (<span class="math inline">\(\overline{x}_2\)</span>) = 67.5</p>
<p>Population standard deviation (<span class="math inline">\(\sigma\)</span>) = 2.5</p>
<p>Level of significance, <span class="math inline">\(\alpha\)</span> = 0.05</p>
<p>Since the two samples are assumed to come from the same population, the standard deviations are equal. We calculate <span class="math inline">\(Z\)</span> using <a href="#eq-zmean2-equal" class="quarto-xref">Equation&nbsp;<span>14.6</span></a>:</p>
<p><span class="math display">\[Z = \frac{\overline{x}_1 - \overline{x}_2}{\sigma \sqrt{\dfrac{1}{n_1} + \dfrac{1}{n_2}}} = \frac{68 - 67.5}{2.5 \sqrt{\dfrac{1}{2000} + \dfrac{1}{1000}}} = \frac{0.5}{0.0968} = 5.16\]</span></p>
<p>Since it is a two-tailed test, we compare with the critical value at <span class="math inline">\(\alpha/2\)</span> = 0.025, which is 1.960 (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>). Since the calculated value (5.16) is greater than the table value (1.960), we reject the null hypothesis. We conclude that the samples cannot be regarded as drawn from the same population.</p>
</div>
</section>
<section id="standard-deviations-are-not-equal" class="level3" data-number="14.6.2">
<h3 data-number="14.6.2" class="anchored" data-anchor-id="standard-deviations-are-not-equal"><span class="header-section-number">14.6.2</span> Standard deviations are not equal</h3>
<p>When the population standard deviations are not equal, we calculate the test statistic <span class="math inline">\(Z\)</span> using the following formula:</p>
<p><span id="eq-zmean2-unequal"><span class="math display">\[Z = \frac{\overline{x}_1 - \overline{x}_2}{\sqrt{\dfrac{\sigma_1^2}{n_1} + \dfrac{\sigma_2^2}{n_2}}} \tag{14.7}\]</span></span></p>
<p>When the null hypothesis is true, this <span class="math inline">\(Z\)</span> follows a standard normal distribution, <span class="math inline">\(Z \sim N(0,1)\)</span>. The decision rule is the same as above (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>).</p>
<div id="exm-mean2-unequal" class="theorem example">
<p><span class="theorem-title"><strong>Example 14.6</strong></span> Two paddy varieties were compared for their grain yield. A random sample of 100 plots of variety A gave a mean yield of 52 quintals per hectare with a population standard deviation of 8 quintals per hectare, while a random sample of 100 plots of variety B gave a mean yield of 49 quintals per hectare with a population standard deviation of 6 quintals per hectare. The two population standard deviations are known and unequal. Test whether the two varieties differ significantly in mean yield, at the 5% level of significance.</p>
<p><strong>Solution</strong></p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1\)</span> = <span class="math inline">\(\mu_2\)</span></p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_2\)</span> (two-tailed test)</p>
<p>Sample size (<span class="math inline">\(n_1\)</span>) = 100</p>
<p>Sample size (<span class="math inline">\(n_2\)</span>) = 100</p>
<p>Sample mean of variety A (<span class="math inline">\(\overline{x}_1\)</span>) = 52</p>
<p>Sample mean of variety B (<span class="math inline">\(\overline{x}_2\)</span>) = 49</p>
<p>Population standard deviation of variety A (<span class="math inline">\(\sigma_1\)</span>) = 8</p>
<p>Population standard deviation of variety B (<span class="math inline">\(\sigma_2\)</span>) = 6</p>
<p>Level of significance, <span class="math inline">\(\alpha\)</span> = 0.05</p>
<p>Since the two population standard deviations are unequal, we use <a href="#eq-zmean2-unequal" class="quarto-xref">Equation&nbsp;<span>14.7</span></a>:</p>
<p><span class="math display">\[Z = \frac{\overline{x}_1 - \overline{x}_2}{\sqrt{\dfrac{\sigma_1^2}{n_1} + \dfrac{\sigma_2^2}{n_2}}} = \frac{52 - 49}{\sqrt{\dfrac{8^2}{100} + \dfrac{6^2}{100}}} = \frac{3}{\sqrt{0.64 + 0.36}} = \frac{3}{1} = 3.0\]</span></p>
<p>Since it is a two-tailed test, we compare <span class="math inline">\(|Z|\)</span> with the critical value at <span class="math inline">\(\alpha/2\)</span> = 0.025, which is 1.960 (see <a href="#sec-decision" class="quarto-xref"><span>Section 14.2.1</span></a>). Since the calculated value (3.0) is greater than the table value (1.960), we reject the null hypothesis. We conclude that the two paddy varieties differ significantly in mean yield.</p>
</div>
<div id="exr-mean2" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 14.3</strong></span> Two random samples were drawn from two populations and the following data were obtained. Test whether the population means are equal. <span class="math inline">\(n_1\)</span> = 400, <span class="math inline">\(n_2\)</span> = 400, <span class="math inline">\(\overline{x}_1\)</span> = 250, <span class="math inline">\(\overline{x}_2\)</span> = 220, <span class="math inline">\(s_1\)</span> = 40, <span class="math inline">\(s_2\)</span> = 55. (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Historical Insights">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Historical Insights
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Why 30? The bell curve, the astronomer, and the birth of large-sample theory</strong></p>
<p>The reason large-sample tests work at all traces back to one of the most remarkable results in statistics: the <strong>Central Limit Theorem</strong>. It says that no matter what the shape of the parent population, the distribution of the sample mean approaches a normal distribution as the sample size grows. This is why the <span class="math inline">\(Z\)</span>-test, which assumes normality, can be applied to almost any large sample.</p>
<p>The normal curve itself was first derived by Abraham de Moivre in 1733 as an approximation to the binomial distribution, while he was studying games of chance. It was later rediscovered by Carl Friedrich Gauss around 1809, who used it to model the errors astronomers made when measuring the positions of stars and planets. Because the same bell-shaped curve kept appearing whenever many small independent errors were added together, it came to be called the <em>normal</em> distribution, and for a long time the <em>Gaussian</em> distribution. <span class="citation" data-cites="Gauss1809">(<a href="references.html#ref-Gauss1809" role="doc-biblioref">Gauss 1809</a>)</span></p>
<p>But where did the famous cut-off of “<span class="math inline">\(n \geq 30\)</span>” come from? It was never a law of nature. It emerged as a practical rule of thumb in the early twentieth century, around the time William Gosset (writing under the pen name <em>Student</em>) developed the <span class="math inline">\(t\)</span>-distribution in 1908 while working as a brewer at Guinness in Dublin. Gosset showed that for small samples the normal approximation is unreliable and a separate distribution is needed. As the sample size increases, the <span class="math inline">\(t\)</span>-distribution steadily approaches the normal curve, and by about 30 observations the two are so close that the difference rarely matters in practice. That convenient meeting point gave us the boundary between “small” and “large” samples that we still use today. <span class="citation" data-cites="Student1908">(<a href="references.html#ref-Student1908" role="doc-biblioref">Student 1908</a>)</span></p>
<p>So the next time you check whether your sample size crosses 30, remember that you are standing on the shoulders of a gambler, an astronomer, and a brewer.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Quotes to Inspire">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quotes to Inspire
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>“It is a capital mistake to theorize before one has data.” - Sir Arthur Conan Doyle</strong></p>
</div>
</div>



<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Gauss1809" class="csl-entry" role="listitem">
Gauss, Carl Friedrich. 1809. <em>Theoria Motus Corporum Coelestium in Sectionibus Conicis Solem Ambientium</em>. Hamburg: Friedrich Perthes; I. H. Besser.
</div>
<div id="ref-Student1908" class="csl-entry" role="listitem">
Student. 1908. <span>“The Probable Error of a Mean.”</span> <em>Biometrika</em> 6 (1): 1–25. <a href="https://doi.org/10.1093/biomet/6.1.1">https://doi.org/10.1093/biomet/6.1.1</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.agrinoteskau\.com\/agstat-textbook\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./hypothesisTest.html" class="pagination-link" aria-label="Hypothesis testing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./smallsampleTest.html" class="pagination-link" aria-label="Small sample tests">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Small sample tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Published by PAPAYA publishing division of <a href="https://www.statoberry.com/papaya"><img src=".\images/statoberry.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>   
    <div class="nav-footer-center">
<p><a href="https://www.statoberry.com/papaya"><img src=".\images/papayalogo.png" class="img-fluid" style="width: auto; height: 90px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>
    <div class="nav-footer-right">
<p>Licenced under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC-BY-NC-ND 4.0 Int License</a> <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img src=".\images/cclogo.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a> Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>