<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>19&nbsp; Multiple comparison tests – TEXTBOOK OF AGRICULTURAL STATISTICS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./singleFactor.html" rel="next">
<link href="./anova.html" rel="prev">
<link href="./images/cover.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d166b450ba5a8e9f7a0ab969bf6592c1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9fe799a8b491b95f8638fac26051bc8e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-bad6a7b64396174f9e6ce9f1aaf6e4b8.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="19&nbsp; Multiple comparison tests – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:description" content="">
<meta property="og:image" content="https://www.agrinoteskau.com/agstat-textbook.html/images/cover.jpg">
<meta property="og:site_name" content="TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:title" content="19&nbsp; Multiple comparison tests – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://www.agrinoteskau.com/agstat-textbook.html/images/papayalogo.png">
<meta name="twitter:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="541">
<meta name="twitter:image-width" content="956">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./multipleComparison.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple comparison tests</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/sidebarcover.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEXTBOOK OF AGRICULTURAL STATISTICS</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basics of statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agstatindia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Official agricultural statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical representation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Central tendency I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Central tendency II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dispersion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measures of dispersion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./skewness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Skewness and kurtosis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./association.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of association</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probabilitydist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampleSurvey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Sample survey</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesisTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./largeSampletest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Large sample test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smallsampleTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Small sample tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./designofexperiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Design of experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uniformityTrials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Uniformity trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analysis of variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multipleComparison.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple comparison tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleFactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Single factor experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./factorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Factorial experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analysis of covariance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./missingPlot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Missing plot analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Appendix 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Appendix 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Appendix 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Appendix 4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Appendix 5</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_personalities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Appendix 6</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#why-do-we-need-a-post-hoc-test" id="toc-why-do-we-need-a-post-hoc-test" class="nav-link active" data-scroll-target="#why-do-we-need-a-post-hoc-test"><span class="header-section-number">19.1</span> Why do we need a post-hoc test?</a></li>
  <li><a href="#sec-lsd" id="toc-sec-lsd" class="nav-link" data-scroll-target="#sec-lsd"><span class="header-section-number">19.2</span> Fisher’s LSD test</a>
  <ul class="collapse">
  <li><a href="#lsd-least-significant-difference" id="toc-lsd-least-significant-difference" class="nav-link" data-scroll-target="#lsd-least-significant-difference"><span class="header-section-number">19.2.1</span> LSD (Least Significant Difference)</a></li>
  <li><a href="#logic-behind-the-lsd-test" id="toc-logic-behind-the-lsd-test" class="nav-link" data-scroll-target="#logic-behind-the-lsd-test"><span class="header-section-number">19.2.2</span> Logic behind the LSD test</a></li>
  <li><a href="#advantages-and-disadvantages-of-lsd" id="toc-advantages-and-disadvantages-of-lsd" class="nav-link" data-scroll-target="#advantages-and-disadvantages-of-lsd"><span class="header-section-number">19.2.3</span> Advantages and disadvantages of LSD</a></li>
  </ul></li>
  <li><a href="#duncans-multiple-range-test-dmrt" id="toc-duncans-multiple-range-test-dmrt" class="nav-link" data-scroll-target="#duncans-multiple-range-test-dmrt"><span class="header-section-number">19.3</span> Duncan’s Multiple Range Test (DMRT)</a></li>
  <li><a href="#tukeys-test" id="toc-tukeys-test" class="nav-link" data-scroll-target="#tukeys-test"><span class="header-section-number">19.4</span> Tukey’s test</a></li>
  <li><a href="#a-worked-example" id="toc-a-worked-example" class="nav-link" data-scroll-target="#a-worked-example"><span class="header-section-number">19.5</span> A worked example</a></li>
  <li><a href="#letter-grouping-display-of-results" id="toc-letter-grouping-display-of-results" class="nav-link" data-scroll-target="#letter-grouping-display-of-results"><span class="header-section-number">19.6</span> Letter grouping (display of results)</a></li>
  <li><a href="#other-multiple-comparison-tests" id="toc-other-multiple-comparison-tests" class="nav-link" data-scroll-target="#other-multiple-comparison-tests"><span class="header-section-number">19.7</span> Other multiple comparison tests</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">19.8</span> Chapter Summary</a>
  <ul class="collapse">
  <li><a href="#fill-in-the-blanks" id="toc-fill-in-the-blanks" class="nav-link" data-scroll-target="#fill-in-the-blanks">Fill in the blanks</a></li>
  <li><a href="#short-answer-questions" id="toc-short-answer-questions" class="nav-link" data-scroll-target="#short-answer-questions">Short-answer questions</a></li>
  <li><a href="#numerical-and-conceptual-questions" id="toc-numerical-and-conceptual-questions" class="nav-link" data-scroll-target="#numerical-and-conceptual-questions">Numerical and conceptual questions</a></li>
  <li><a href="#important-formulae" id="toc-important-formulae" class="nav-link" data-scroll-target="#important-formulae">Important formulae</a></li>
  <li><a href="#quick-revision" id="toc-quick-revision" class="nav-link" data-scroll-target="#quick-revision">Quick revision</a></li>
  <li><a href="#answers-to-fill-in-the-blanks" id="toc-answers-to-fill-in-the-blanks" class="nav-link" data-scroll-target="#answers-to-fill-in-the-blanks">Answers to fill in the blanks</a></li>
  <li><a href="#solutions-to-numerical-and-conceptual-questions" id="toc-solutions-to-numerical-and-conceptual-questions" class="nav-link" data-scroll-target="#solutions-to-numerical-and-conceptual-questions">Solutions to numerical and conceptual questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple comparison tests</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>ANOVA is an omnibus test. An <em>omnibus test</em>, as the general name suggests, refers to an overall or global test. It is implemented on an overall hypothesis that tends to find whether there is any significant difference between the treatment means (in the case of ANOVA) or not.</p>
<p>ANOVA does not tell us which treatment pairs are different. More clearly, on rejecting the null hypothesis in ANOVA, we conclude that at least a pair of treatment means are different, but it does not give any idea about which specific treatments are different. In order to identify which treatment means are significantly different, we need to employ <strong>multiple comparison tests</strong>, also known as <strong>post-hoc tests</strong>.</p>
<p>A significant omnibus F test in the ANOVA procedure is a prerequisite before conducting post-hoc comparisons; otherwise, those comparisons are not required. There are several methods for performing post-hoc tests. In this chapter, we discuss the three that are most widely used in agricultural research:</p>
<ul>
<li><p>Fisher’s LSD test (Least Significant Difference test)</p></li>
<li><p>Duncan’s Multiple Range Test (DMRT)</p></li>
<li><p>Tukey’s test (Honestly Significant Difference test)</p></li>
</ul>
<section id="why-do-we-need-a-post-hoc-test" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="why-do-we-need-a-post-hoc-test"><span class="header-section-number">19.1</span> Why do we need a post-hoc test?</h2>
<p>A <strong>Type I error</strong> occurs when the null hypothesis <span class="math inline">\(H_0\)</span> is statistically rejected even though it is actually true (a false positive), whereas a <strong>Type II error</strong> refers to failing to reject <span class="math inline">\(H_0\)</span> when it is actually false (a false negative). In a post-hoc test, we compare each of the treatment pairs individually. For example, consider a situation in which three treatments A, B, and C are compared. They may form the following three pairs: A versus B, A versus C, and B versus C. The set of pairwise comparisons for a given experiment is called a <strong>family</strong>. The Type I error rate for the whole set of comparisons taken together is called the <strong>family-wise error rate</strong> (FWER) <span class="citation" data-cites="Lee">(<a href="references.html#ref-Lee" role="doc-biblioref">Lee and Lee 2018</a>)</span>.</p>
<p>For example, if one performs a pairwise test between two groups A and B at the 5% level of significance (<span class="math inline">\(\alpha\)</span>) and observes that they are not significantly different, then the chance that a correct decision is made (not committing a Type I error) is 95%. If a second pairwise test between groups B and C is also carried out and gives a non-significant result, then the probability of making a correct decision on both the A–B and B–C comparisons is <span class="math inline">\(0.95 \times 0.95 = 0.9025\)</span>, or 90.25%. Consequently, the actual Type I error rate for the family is <span class="math inline">\(1 - 0.9025 = 0.0975\)</span>, not 0.05. If the comparison between groups A and C is also non-significant, the probability of correctly declaring non-significance for all three pairs is <span class="math inline">\(0.95 \times 0.95 \times 0.95 = 0.857\)</span>, and the actual family-wise Type I error rate is <span class="math inline">\(1 - 0.857 = 0.143\)</span>, which is more than 14%. So the chance of a Type I error increases sharply when several treatment pairs are tested together. Multiple comparison tests are devised in such a way that a correction is incorporated to control this inflation in <span class="math inline">\(\alpha\)</span>, so that the actual level of significance remains at the prescribed rate (in our case 0.05).</p>
<p><span id="eq-inflated"><span class="math display">\[\text{Inflated } \alpha = 1 - \left( 1 - \alpha \right)^{N} \tag{19.1}\]</span></span></p>
<p>where <span class="math inline">\(N\)</span> is the number of hypotheses (comparisons) tested. As <a href="#eq-inflated" class="quarto-xref">Equation&nbsp;<span>19.1</span></a> shows, the inflation of the probability of a Type I error increases with the number of comparisons.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The number of possible pairwise comparisons among <span class="math inline">\(v\)</span> treatments is <span class="math inline">\(\binom{v}{2} = \dfrac{v(v-1)}{2}\)</span>. For example, with 5 treatments there are <span class="math inline">\(\dfrac{5 \times 4}{2} = 10\)</span> pairwise comparisons, and without any correction the family-wise error rate would rise to <span class="math inline">\(1 - (0.95)^{10} = 0.40\)</span>, or 40%.</p>
</div>
</div>
</section>
<section id="sec-lsd" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="sec-lsd"><span class="header-section-number">19.2</span> Fisher’s LSD test</h2>
<p>The first pairwise comparison technique was developed by Fisher in 1935 and is called the <strong>least significant difference (LSD) test</strong>. Fisher’s LSD procedure is a two-step testing procedure for pairwise comparisons of several treatment groups. In the first step, ANOVA is performed. If the null hypothesis can be rejected at the pre-specified level of significance, then in the second step all pairwise comparisons of treatment means are performed.</p>
<p><strong>Steps in Fisher’s LSD test</strong></p>
<ol type="1">
<li><p>ANOVA is performed, and if the null hypothesis is rejected, proceed to step 2. If the ANOVA does not show a significant effect, the analysis is not carried forward to pairwise comparisons.</p></li>
<li><p>An LSD (least significant difference) value is calculated. For each pair of treatments, if the absolute difference between the two treatment means is greater than the LSD value, we conclude that those treatment means are significantly different.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Among agricultural researchers in India, the term <strong>CD (Critical Difference)</strong> is used instead of LSD. Both terms mean the same thing and are used interchangeably.</p>
</div>
</div>
<section id="lsd-least-significant-difference" class="level3" data-number="19.2.1">
<h3 data-number="19.2.1" class="anchored" data-anchor-id="lsd-least-significant-difference"><span class="header-section-number">19.2.1</span> LSD (Least Significant Difference)</h3>
<p>Consider two treatments <span class="math inline">\(T_{i}\)</span> and <span class="math inline">\(T_{j}\)</span> with replications <span class="math inline">\(r_{i}\)</span> and <span class="math inline">\(r_{j}\)</span>. Then the LSD (or CD) is given by</p>
<p><span id="eq-lsd"><span class="math display">\[\text{LSD} = t_{\frac{\alpha}{2},\, edf} \cdot SE(d) \tag{19.2}\]</span></span></p>
<p><span id="eq-sed"><span class="math display">\[SE(d) = \sqrt{\text{MSE}\left( \frac{1}{r_{i}} + \frac{1}{r_{j}} \right)} \tag{19.3}\]</span></span></p>
<p>where MSE is the mean square error from the ANOVA, and <span class="math inline">\(t_{\frac{\alpha}{2},\, edf}\)</span> is the critical value of the two-tailed Student’s t distribution at the <span class="math inline">\(\alpha\)</span> level of significance and error degrees of freedom (<span class="math inline">\(edf\)</span>).</p>
<p>If the replications are equal, <span class="math inline">\(r_{i} = r_{j} = r\)</span>, then</p>
<p><span id="eq-sedequal"><span class="math display">\[SE(d) = \sqrt{\text{MSE}\left( \frac{1}{r} + \frac{1}{r} \right)} = \sqrt{\text{MSE}\left( \frac{2}{r} \right)} = \sqrt{\frac{2\,\text{MSE}}{r}} \tag{19.4}\]</span></span></p>
<p><span id="eq-lsdequal"><span class="math display">\[\text{LSD} = t_{\frac{\alpha}{2},\, edf} \cdot \sqrt{\frac{2\,\text{MSE}}{r}} \tag{19.5}\]</span></span></p>
<p>If the difference between the means of two treatments <span class="math inline">\(T_{i}\)</span> and <span class="math inline">\(T_{j}\)</span> is greater than the LSD, we say that <span class="math inline">\(T_{i}\)</span> and <span class="math inline">\(T_{j}\)</span> are significantly different at the specified level of significance <span class="math inline">\(\alpha\)</span>.</p>
</section>
<section id="logic-behind-the-lsd-test" class="level3" data-number="19.2.2">
<h3 data-number="19.2.2" class="anchored" data-anchor-id="logic-behind-the-lsd-test"><span class="header-section-number">19.2.2</span> Logic behind the LSD test</h3>
<p>Let <span class="math inline">\(\overline{T_{i}}\)</span> and <span class="math inline">\(\overline{T_{j}}\)</span> be the treatment means obtained from the experiment, and let <span class="math inline">\(\mu_{i}\)</span> and <span class="math inline">\(\mu_{j}\)</span> be the corresponding unknown population means. The null hypothesis for a pairwise comparison is</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{i} = \mu_{j}\)</span>, <em>i</em>.<em>e</em>. <span class="math inline">\(\mu_{i} - \mu_{j} = 0\)</span>.</p>
<p>A t-test can be used to test this hypothesis:</p>
<p><span id="eq-lsdt"><span class="math display">\[t = \frac{\overline{T_{i}} - \overline{T_{j}}}{SE(d)} \tag{19.6}\]</span></span></p>
<p>The <span class="math inline">\(100(1 - \alpha)\%\)</span> confidence interval for the mean difference <span class="math inline">\(\overline{T_{i}} - \overline{T_{j}}\)</span> is <span class="math inline">\(\left( \overline{T_{i}} - \overline{T_{j}} \right) \pm t_{\frac{\alpha}{2},\, edf}\, SE(d)\)</span>, which can be written as <span class="math inline">\(\left( \overline{T_{i}} - \overline{T_{j}} \right) \pm \text{LSD}\)</span>. So, if <span class="math inline">\(\left| \overline{T_{i}} - \overline{T_{j}} \right| &gt; \text{LSD}\)</span>, the confidence interval does not include 0, and we reject the null hypothesis and conclude that the two treatment means are different, with <span class="math inline">\(100(1 - \alpha)\%\)</span> confidence.</p>
</section>
<section id="advantages-and-disadvantages-of-lsd" class="level3" data-number="19.2.3">
<h3 data-number="19.2.3" class="anchored" data-anchor-id="advantages-and-disadvantages-of-lsd"><span class="header-section-number">19.2.3</span> Advantages and disadvantages of LSD</h3>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The LSD test is also known as the <strong>protected Fisher’s LSD test</strong>. “Protected” means that the pairwise calculations are performed only when the null hypothesis has already been rejected by the ANOVA. This first step helps to control the false positive rate (Type I error) for the entire family of comparisons <span class="citation" data-cites="Hayter">(<a href="references.html#ref-Hayter" role="doc-biblioref">Hayter 1986</a>)</span>.</p>
</div>
</div>
<p>While the protected Fisher’s LSD test was the first post-hoc test ever developed, it does not correct for <span class="math inline">\(\alpha\)</span> inflation as effectively as some other post-hoc tests. Fisher’s LSD procedure is known to preserve the experiment-wise Type I error rate at the nominal level only when the number of treatments is exactly three <span class="citation" data-cites="Meier">(<a href="references.html#ref-Meier" role="doc-biblioref">Meier 2006</a>)</span>. Nevertheless, the LSD is still the most commonly used post-hoc test in agricultural research. When the number of treatments is larger, it is advisable to also consider DMRT or Tukey’s test.</p>
</section>
</section>
<section id="duncans-multiple-range-test-dmrt" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="duncans-multiple-range-test-dmrt"><span class="header-section-number">19.3</span> Duncan’s Multiple Range Test (DMRT)</h2>
<p>When a comparison of all possible pairs of treatment means is required, we can use <strong>Duncan’s Multiple Range Test (DMRT)</strong>, devised by Duncan in 1955. It is especially useful when the number of treatments to be compared is large, and it is very popular in the plant sciences. In this test, the standard error of a mean is multiplied by tabulated values (<span class="math inline">\(r_{p}\)</span>) for different values of <span class="math inline">\(p\)</span>, where p is the number of ordered treatment means spanned by the comparison, including the two means being compared. For example, when comparing two adjacent means, p=2. If one mean lies between the two means being compared, then p=3. If two means lie between them, then p=4, and so on. The calculated critical value is then used to decide whether the difference between the two treatment means is significant. For given <span class="math inline">\(p\)</span>, the <span class="math inline">\(r_p\)</span> values are obtained from DMRT tables, a table is provided in <a href="appendix2.html" class="quarto-xref"><span>Chapter 24</span></a>.</p>
<p>Unlike Fisher’s LSD, which uses the same critical difference for every pair of means, DMRT uses progressively larger critical values as p increases. Consequently, treatment means that are farther apart in the ordered list are compared using a larger critical value.</p>
<p><strong>Steps in DMRT</strong></p>
<ol type="1">
<li><p>Arrange the treatment means in descending order, along with their ranks (highest value is given rank 1 and so on).</p></li>
<li><p>Calculate the standard error of a mean as</p></li>
</ol>
<p><span id="eq-sedmrt"><span class="math display">\[SE(\overline{Y}) = \sqrt{\frac{\text{MSE}}{r}} \tag{19.7}\]</span></span></p>
<ol start="3" type="1">
<li><p>From the statistical tables of <strong>Duncan’s multiple ranges</strong>, note the <span class="math inline">\(r_{p}\)</span> values for <span class="math inline">\(p = 2, 3, \ldots, v\)</span> treatments, corresponding to the error degrees of freedom.</p></li>
<li><p>Calculate the shortest significant ranges (<span class="math inline">\(R_{p}\)</span>), where</p></li>
</ol>
<p><span id="eq-rp"><span class="math display">\[R_{p} = r_{p} \cdot SE(\overline{Y}) \tag{19.8}\]</span></span></p>
<ol start="5" type="1">
<li><p>Compare the difference between each pair of means with the <span class="math inline">\(R_{p}\)</span> value corresponding to the number of steps <span class="math inline">\(p\)</span> separating them in the ranked order. If the difference exceeds the corresponding <span class="math inline">\(R_{p}\)</span>, the two means are significantly different.</p></li>
<li><p>Present the results using a letter (or line) notation to indicate which treatments are on par and which are significantly different.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The critical value <span class="math inline">\(R_{p}\)</span> in DMRT gradually increases as the means being compared are ranked further apart. This means the “protection level” of the test relaxes as the number of means spanned increases, making DMRT more powerful (more likely to declare a difference) than a test based on a single critical value like the LSD. It is, however, more liberal than Tukey’s test, so it may declare more pairs significant.</p>
</div>
</div>
</section>
<section id="tukeys-test" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="tukeys-test"><span class="header-section-number">19.4</span> Tukey’s test</h2>
<p><strong>Tukey’s test</strong>, also called the <strong>honestly significant difference (HSD) test</strong>, was proposed by John Tukey. It is used for making all possible pairwise comparisons among treatment means while controlling the family-wise error rate at the chosen level <span class="math inline">\(\alpha\)</span> for the <em>entire</em> set of comparisons. This is its key advantage over the LSD test, which controls only the error rate of each individual comparison.</p>
<p>Tukey’s test is based on the <strong>studentised range statistic</strong> <span class="math inline">\(q\)</span>. For equal replications, a single critical difference, called the honestly significant difference, is computed:</p>
<p><span id="eq-hsd"><span class="math display">\[\text{HSD} = q_{\alpha,\, (v,\, edf)} \cdot \sqrt{\frac{\text{MSE}}{r}} \tag{19.9}\]</span></span></p>
<p>where <span class="math inline">\(q_{\alpha,\, (v,\, edf)}\)</span> is the critical value of the studentised range distribution for <span class="math inline">\(v\)</span> treatments and error degrees of freedom <span class="math inline">\(edf\)</span>, MSE is the error mean square from the ANOVA, and <span class="math inline">\(r\)</span> is the number of replications. Any two treatment means whose absolute difference exceeds the HSD are declared significantly different. Tukey’s test is more conservative than the LSD and DMRT, meaning it is less likely to declare a difference significant, and it is recommended when all pairwise comparisons are of interest and strict control of the Type I error is desired.</p>
</section>
<section id="a-worked-example" class="level2" data-number="19.5">
<h2 data-number="19.5" class="anchored" data-anchor-id="a-worked-example"><span class="header-section-number">19.5</span> A worked example</h2>
<div id="exm-postdoc" class="theorem example">
<p><span class="theorem-title"><strong>Example 19.1</strong></span> A field experiment was conducted to compare the yield (in kg per plot) of five fertilizer treatments <span class="math inline">\(T_1\)</span>, <span class="math inline">\(T_2\)</span>, <span class="math inline">\(T_3\)</span>, <span class="math inline">\(T_4\)</span>, and <span class="math inline">\(T_5\)</span>, laid out in a completely randomized design with four replications (<span class="math inline">\(r = 4\)</span>). The ANOVA gave a significant treatment effect (<span class="math inline">\(F\)</span> significant at the 5% level), with an error mean square <span class="math inline">\(\text{MSE} = 0.5333\)</span> and error degrees of freedom <span class="math inline">\(edf = 15\)</span>. The treatment means are given below. Identify which treatments differ from one another using the LSD, DMRT, and Tukey’s tests at the 5% level of significance.</p>
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;"><span class="math inline">\(T_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(T_2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(T_3\)</span></th>
<th style="text-align: center;"><span class="math inline">\(T_4\)</span></th>
<th style="text-align: center;"><span class="math inline">\(T_5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Mean yield</td>
<td style="text-align: center;">21.0</td>
<td style="text-align: center;">24.0</td>
<td style="text-align: center;">25.5</td>
<td style="text-align: center;">22.5</td>
<td style="text-align: center;">31.0</td>
</tr>
</tbody>
</table>
<p><strong>Solution</strong></p>
<p>Since the ANOVA F test is significant, we may proceed to the post-hoc comparisons.</p>
<p><strong>(a) Fisher’s LSD test.</strong></p>
<p>The critical t value at <span class="math inline">\(\alpha/2 = 0.025\)</span> and <span class="math inline">\(edf = 15\)</span> is <span class="math inline">\(t_{0.025,\,15} = 2.131\)</span>. Using <a href="#eq-lsdequal" class="quarto-xref">Equation&nbsp;<span>19.5</span></a>,</p>
<p><span class="math display">\[\text{LSD} = t_{0.025,\,15} \cdot \sqrt{\frac{2\,\text{MSE}}{r}} = 2.131 \times \sqrt{\frac{2 \times 0.5333}{4}} = 2.131 \times 0.5164 = 1.10\]</span></p>
<p>Any two treatment means differing by more than 1.10 are significantly different.</p>
<p><strong>(b) Duncan’s Multiple Range Test.</strong></p>
<p>For DMRT first, arrange the means in descending order:</p>
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Rank</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Treatment</td>
<td style="text-align: center;"><span class="math inline">\(T_5\)</span></td>
<td style="text-align: center;"><span class="math inline">\(T_3\)</span></td>
<td style="text-align: center;"><span class="math inline">\(T_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(T_4\)</span></td>
<td style="text-align: center;"><span class="math inline">\(T_1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Mean</td>
<td style="text-align: center;">31.0</td>
<td style="text-align: center;">25.5</td>
<td style="text-align: center;">24.0</td>
<td style="text-align: center;">22.5</td>
<td style="text-align: center;">21.0</td>
</tr>
</tbody>
</table>
<p>The standard error of a mean, using <a href="#eq-sedmrt" class="quarto-xref">Equation&nbsp;<span>19.7</span></a>, is</p>
<p><span class="math display">\[SE(\overline{Y}) = \sqrt{\frac{\text{MSE}}{r}} = \sqrt{\frac{0.5333}{4}} = 0.3651\]</span></p>
<p>The Duncan’s range values <span class="math inline">\(r_{p}\)</span> at the 5% level for <span class="math inline">\(edf = 15\)</span>, <span class="math inline">\(r_{p}\)</span> can be obtained from DMRT table given in <a href="appendix2.html" class="quarto-xref"><span>Chapter 24</span></a> and the shortest significant ranges <span class="math inline">\(R_{p} = r_{p} \cdot SE(\overline{Y})\)</span> from <a href="#eq-rp" class="quarto-xref">Equation&nbsp;<span>19.8</span></a>, are</p>
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(p\)</span> (means apart)</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(r_{p}\)</span></td>
<td style="text-align: center;">3.014</td>
<td style="text-align: center;">3.160</td>
<td style="text-align: center;">3.250</td>
<td style="text-align: center;">3.312</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(R_{p}\)</span></td>
<td style="text-align: center;">1.10</td>
<td style="text-align: center;">1.15</td>
<td style="text-align: center;">1.19</td>
<td style="text-align: center;">1.21</td>
</tr>
</tbody>
</table>
<p><strong>(c) Tukey’s HSD test.</strong> The studentised range value at the 5% level for <span class="math inline">\(v = 5\)</span> treatments and <span class="math inline">\(edf = 15\)</span> is <span class="math inline">\(q_{0.05,\,(5,15)} = 4.367\)</span>. Using <a href="#eq-hsd" class="quarto-xref">Equation&nbsp;<span>19.9</span></a>,</p>
<p><span class="math display">\[\text{HSD} = q_{0.05,\,(5,15)} \cdot \sqrt{\frac{\text{MSE}}{r}} = 4.367 \times 0.3651 = 1.59\]</span></p>
<p>Any two treatment means differing by more than 1.59 are significantly different.</p>
<p>The pairwise comparisons under the three tests are summarised in <a href="#tbl-comparison" class="quarto-xref">Table&nbsp;<span>19.1</span></a>. For each pair, S denotes a significant difference and NS a non-significant one.</p>
<div id="tbl-comparison" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;19.1: Pairwise comparisons under the three tests
</figcaption>
<div aria-describedby="tbl-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 6%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Comparison</th>
<th style="text-align: center;">Mean difference</th>
<th style="text-align: center;">Steps apart (<span class="math inline">\(p\)</span>)</th>
<th style="text-align: center;">LSD (1.10)</th>
<th style="text-align: center;">DMRT (<span class="math inline">\(R_p\)</span>) used</th>
<th style="text-align: center;">DMRT</th>
<th style="text-align: center;">HSD (1.59)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(<span class="math inline">\(T_5 - T_3\)</span>)</td>
<td style="text-align: center;">5.5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.10</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">S</td>
</tr>
<tr class="even">
<td style="text-align: center;">(<span class="math inline">\(T_5 - T_2\)</span>)</td>
<td style="text-align: center;">7.0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.15</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">S</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(<span class="math inline">\(T_5 - T_4\)</span>)</td>
<td style="text-align: center;">8.5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.19</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">S</td>
</tr>
<tr class="even">
<td style="text-align: center;">(<span class="math inline">\(T_5 - T_1\)</span>)</td>
<td style="text-align: center;">10.0</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.21</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">S</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(<span class="math inline">\(T_3 - T_2\)</span>)</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.10</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">NS</td>
</tr>
<tr class="even">
<td style="text-align: center;">(<span class="math inline">\(T_3 - T_4\)</span>)</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.15</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">S</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(<span class="math inline">\(T_3 - T_1\)</span>)</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.19</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">S</td>
</tr>
<tr class="even">
<td style="text-align: center;">(<span class="math inline">\(T_2 - T_4\)</span>)</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.10</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">NS</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(<span class="math inline">\(T_2 - T_1\)</span>)</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.15</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">S</td>
</tr>
<tr class="even">
<td style="text-align: center;">(<span class="math inline">\(T_4 - T_1\)</span>)</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">1.10</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">NS</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Note:</strong> The “Steps apart <span class="math inline">\(p\)</span>” column indicates the number of ordered treatment means spanned by the comparison (including the two means being compared). The corresponding shortest significant range <span class="math inline">\(R_p\)</span> is selected from the DMRT table based on this value of (<span class="math inline">\(p\)</span>). This makes it clear why different critical values are used for different comparisons.</p>
<p>Notice the important difference between the tests. The LSD and DMRT declare every pair significant, because even the smallest difference (1.5) exceeds their critical values. Tukey’s HSD, being more conservative, uses a larger critical value (1.59), so the three pairs that differ by only 1.5 (<span class="math inline">\(T_3 - T_2\)</span>, <span class="math inline">\(T_2 - T_4\)</span>, and <span class="math inline">\(T_4 - T_1\)</span>) are judged <strong>not</strong> significant. This illustrates the general rule that Tukey’s test is stricter than the LSD and DMRT, and therefore detects fewer differences.</p>
</div>
</section>
<section id="letter-grouping-display-of-results" class="level2" data-number="19.6">
<h2 data-number="19.6" class="anchored" data-anchor-id="letter-grouping-display-of-results"><span class="header-section-number">19.6</span> Letter grouping (display of results)</h2>
<p>The results of a multiple comparison test are conventionally presented using a compact letter grouping (also called the alphabet notation). Treatments that are not significantly different from each other share at least one common letter, while treatments that do not share any letter are significantly different. This lets the reader see the whole pattern of significance at a glance, without reading the full table of pairwise comparisons. You can even use symbols to denote significance but usually alphabets are used because its easy and 26 letters are there.</p>
<p>The rule for assigning letters is as follows:</p>
<ol type="1">
<li><p>Arrange the treatment means in descending order.</p></li>
<li><p>Assign the letter <em>a</em> to the largest mean (This is not a stricter rule, but this convention is followed usually, you can even use any symbol instead of alphabets). Moving down the list, keep the same letter <em>a</em> for every following mean that is not significantly different from the largest one (<em>i</em>.<em>e</em>. whose difference from it is less than the critical value).</p></li>
<li><p>When a mean is reached that is significantly different from the first mean of the current letter, start a new letter (<em>b</em>) at that mean.</p></li>
<li><p>Repeat the process starting from this new mean, and continue with letters <em>c</em>, <em>d</em>, and so on. A treatment that is not significantly different from more than one group receives more than one letter (for example <em>bc</em>), showing that it belongs to both overlapping groups.</p></li>
</ol>
<p>Let us apply this to the results in <a href="#exm-postdoc" class="quarto-xref">Example&nbsp;<span>19.1</span></a>.</p>
<p>For the LSD and DMRT, every pair of treatments is significantly different, so no two treatments share a letter, and each receives its own letter:</p>
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">Grouping</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(T_5\)</span></td>
<td style="text-align: center;">31.0</td>
<td style="text-align: center;">a</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(T_3\)</span></td>
<td style="text-align: center;">25.5</td>
<td style="text-align: center;">b</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(T_2\)</span></td>
<td style="text-align: center;">24.0</td>
<td style="text-align: center;">c</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(T_4\)</span></td>
<td style="text-align: center;">22.5</td>
<td style="text-align: center;">d</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(T_1\)</span></td>
<td style="text-align: center;">21.0</td>
<td style="text-align: center;">e</td>
</tr>
</tbody>
</table>
<p>For Tukey’s HSD, the pairs <span class="math inline">\(T_3 - T_2\)</span>, <span class="math inline">\(T_2 - T_4\)</span>, and <span class="math inline">\(T_4 - T_1\)</span> are not significant, so those treatments share letters. Starting from the top: <span class="math inline">\(T_5\)</span> differs from all others and gets <em>a</em>. <span class="math inline">\(T_3\)</span> starts <em>b</em>; <span class="math inline">\(T_2\)</span> is not different from <span class="math inline">\(T_3\)</span>, so it also gets <em>b</em>, but <span class="math inline">\(T_2\)</span> is also not different from <span class="math inline">\(T_4\)</span>, so a new letter <strong>c</strong> begins at <span class="math inline">\(T_2\)</span>, giving it <em>bc</em>. <span class="math inline">\(T_4\)</span> is not different from <span class="math inline">\(T_2\)</span> (<em>c</em>) and not different from <span class="math inline">\(T_1\)</span>, so it takes <em>cd</em>. <span class="math inline">\(T_1\)</span> is not different from <span class="math inline">\(T_4\)</span>, so it takes <em>d</em>.</p>
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">Grouping</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(T_5\)</span></td>
<td style="text-align: center;">31.0</td>
<td style="text-align: center;">a</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(T_3\)</span></td>
<td style="text-align: center;">25.5</td>
<td style="text-align: center;">b</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(T_2\)</span></td>
<td style="text-align: center;">24.0</td>
<td style="text-align: center;">bc</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(T_4\)</span></td>
<td style="text-align: center;">22.5</td>
<td style="text-align: center;">cd</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(T_1\)</span></td>
<td style="text-align: center;">21.0</td>
<td style="text-align: center;">d</td>
</tr>
</tbody>
</table>
<p>Reading the Tukey grouping: <span class="math inline">\(T_5\)</span> (a) stands alone as the highest-yielding treatment, significantly better than all others. <span class="math inline">\(T_3\)</span> and <span class="math inline">\(T_2\)</span> share the letter b, so they are on par. <span class="math inline">\(T_2\)</span> and <span class="math inline">\(T_4\)</span> share c, and <span class="math inline">\(T_4\)</span> and <span class="math inline">\(T_1\)</span> share d, so those neighbouring pairs are also on par. But <span class="math inline">\(T_3\)</span> (b) and <span class="math inline">\(T_4\)</span> (cd) share no letter, so they are significantly different, and likewise <span class="math inline">\(T_2\)</span> (bc) and <span class="math inline">\(T_1\)</span> (d) are significantly different. This overlapping pattern is exactly what the letter notation is designed to convey.</p>
<p>An older but equivalent way of displaying the same information is the <strong>line (or underscore) notation</strong>. The treatment means are first arranged in order, and each group of adjacent means that are not significantly different from one another is joined by a common line. When groups overlap, the lines are drawn at different levels, some above and some below the row of means, so that they do not collide. Two treatments joined (directly or through a chain) by a common line are on par, while two treatments with no connecting line between them are significantly different. For the Tukey results in <a href="#exm-postdoc" class="quarto-xref">Example&nbsp;<span>19.1</span></a>, one line would join <span class="math inline">\(T_3\)</span> and <span class="math inline">\(T_2\)</span>, a second line (at a different level) would join <span class="math inline">\(T_2\)</span> and <span class="math inline">\(T_4\)</span>, and a third would join <span class="math inline">\(T_4\)</span> and <span class="math inline">\(T_1\)</span>, while <span class="math inline">\(T_5\)</span> has no line at all, since it differs significantly from every other treatment. This conveys exactly the same groupings as the letters a, b, bc, cd, and d.&nbsp;The letter notation is now more common in printed tables because it is easier to typeset, but the two notations carry identical meaning.</p>
<div id="fig-tukey1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tukey1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/line_notation.png" width="450" height="300" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tukey1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19.1: line (or underscore) notation illustration using <a href="#exm-postdoc" class="quarto-xref">Example&nbsp;<span>19.1</span></a>
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The letter grouping method is more common in modern statistical software (such as R, SAS, SPSS, GenStat, JMP and cloud platforms like RAISINS), whereas the line or underscore notation was frequently used in older agricultural statistics texts and research publications. Both methods are equivalent in interpretation.</p>
</div>
</div>
</section>
<section id="other-multiple-comparison-tests" class="level2" data-number="19.7">
<h2 data-number="19.7" class="anchored" data-anchor-id="other-multiple-comparison-tests"><span class="header-section-number">19.7</span> Other multiple comparison tests</h2>
<p>Besides the three tests discussed above, several other multiple comparison procedures exist, each designed for a particular situation. These include the <strong>Student-Newman-Keuls (SNK) test</strong>, the <strong>Bonferroni method</strong>, the <strong>Dunnett method</strong> (used when every treatment is compared only against a single control), and <strong>Scheffé’s test</strong> (used for testing general contrasts among means). A detailed treatment of these methods is beyond the scope of this book; the interested reader may refer to a specialised text on the design and analysis of experiments.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Quotes to Inspire">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quotes to Inspire
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>“The method of difference is the most potent of all methods in experimental inquiry.” - John Stuart Mill</strong></p>
</div>
</div>
</section>
<section id="chapter-summary" class="level2" data-number="19.8">
<h2 data-number="19.8" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">19.8</span> Chapter Summary</h2>
<section id="fill-in-the-blanks" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fill-in-the-blanks">Fill in the blanks</h3>
<p>Answers are given at the end of the chapter.</p>
<ol type="1">
<li><p>ANOVA is an __________ test that determines whether there is an overall significant difference among treatment means.</p></li>
<li><p>ANOVA does not identify which specific treatment __________ are significantly different.</p></li>
<li><p>Tests used to identify specific differences among treatment means after a significant ANOVA are called __________ comparison tests.</p></li>
<li><p>Multiple comparison tests are also called __________ tests.</p></li>
<li><p>A significant omnibus __________ test is a prerequisite before conducting post-hoc comparisons.</p></li>
<li><p>Rejecting the null hypothesis in ANOVA indicates that at least one pair of treatment means is __________.</p></li>
<li><p>Rejecting a true null hypothesis is called a Type __________ error.</p></li>
<li><p>Failing to reject a false null hypothesis is called a Type __________ error.</p></li>
<li><p>The collection of all pairwise comparisons in an experiment is called a __________.</p></li>
<li><p>The probability of making at least one Type I error among a family of comparisons is called the __________ error rate.</p></li>
<li><p>The number of possible pairwise comparisons among <span class="math inline">\(v\)</span> treatments is __________.</p></li>
<li><p>Fisher’s Least Significant Difference test is abbreviated as __________.</p></li>
<li><p>Fisher’s LSD test was developed by __________.</p></li>
<li><p>In India, LSD is commonly referred to as the __________ Difference or CD.</p></li>
<li><p>In Fisher’s LSD procedure, pairwise comparisons are performed only after the ANOVA is found to be __________.</p></li>
<li><p>Fisher’s LSD is therefore also called __________ Fisher’s LSD.</p></li>
<li><p>The LSD is calculated using the error mean square obtained from the __________.</p></li>
<li><p>The standard error of the difference between two treatment means depends on the __________ and the number of replications.</p></li>
<li><p>If the difference between two treatment means is greater than the LSD, the means are considered significantly __________.</p></li>
<li><p>Duncan’s Multiple Range Test is abbreviated as __________.</p></li>
<li><p>DMRT was developed by __________ in 1955.</p></li>
<li><p>In DMRT, treatment means are first arranged in __________ order.</p></li>
<li><p>In DMRT, <span class="math inline">\(p\)</span> represents the number of ordered treatment means __________ by the comparison.</p></li>
<li><p>The critical values used in DMRT are denoted by __________.</p></li>
<li><p>The shortest significant range in DMRT is denoted by __________.</p></li>
<li><p>The shortest significant range is calculated as <span class="math inline">\(R_p=\)</span> __________.</p></li>
<li><p>Unlike LSD, DMRT uses progressively __________ critical values as the number of means spanned increases.</p></li>
<li><p>Tukey’s test is also called the Honestly Significant __________ test.</p></li>
<li><p>Tukey’s HSD test was proposed by __________.</p></li>
<li><p>Tukey’s test is based on the __________ range statistic.</p></li>
<li><p>For equal replications, Tukey’s test uses a single critical value called the __________.</p></li>
<li><p>Tukey’s test controls the family-wise error rate for the __________ set of pairwise comparisons.</p></li>
<li><p>Compared with LSD and DMRT, Tukey’s test is more __________.</p></li>
<li><p>A treatment grouping in which treatments that are not significantly different share a common letter is called __________ grouping.</p></li>
<li><p>In letter notation, treatments that do not share any common letter are significantly __________.</p></li>
<li><p>The older method of displaying groups of treatment means using connecting lines is called __________ notation.</p></li>
<li><p>A treatment that belongs to two overlapping non-significant groups may receive __________ letters.</p></li>
<li><p>The Bonferroni method, Dunnett method, Scheffé’s test, and SNK test are examples of other __________ comparison procedures.</p></li>
<li><p>Dunnett’s test is particularly useful when each treatment is compared with a single __________.</p></li>
<li><p>Scheffé’s test is used for testing general __________ among means.</p></li>
</ol>
</section>
<section id="short-answer-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="short-answer-questions">Short-answer questions</h3>
<ol type="1">
<li><p>What is an omnibus test?</p></li>
<li><p>Why is ANOVA called an omnibus test?</p></li>
<li><p>Why are multiple comparison tests required after ANOVA?</p></li>
<li><p>When should post-hoc comparisons be conducted after ANOVA?</p></li>
<li><p>Explain Type I and Type II errors.</p></li>
<li><p>What is family-wise error rate?</p></li>
<li><p>Why does the probability of Type I error increase when several pairwise comparisons are performed?</p></li>
<li><p>Derive the expression for inflated <span class="math inline">\(\alpha\)</span> when <span class="math inline">\(N\)</span> independent comparisons are performed.</p></li>
<li><p>How many pairwise comparisons are possible among <span class="math inline">\(v\)</span> treatments?</p></li>
<li><p>Explain Fisher’s LSD test.</p></li>
<li><p>State the steps involved in Fisher’s LSD test.</p></li>
<li><p>What is meant by protected Fisher’s LSD?</p></li>
<li><p>Why is LSD also called Critical Difference in agricultural research?</p></li>
<li><p>Explain the logic behind Fisher’s LSD test.</p></li>
<li><p>State the advantages and disadvantages of Fisher’s LSD test.</p></li>
<li><p>What is Duncan’s Multiple Range Test?</p></li>
<li><p>State the steps involved in DMRT.</p></li>
<li><p>What is meant by <span class="math inline">\(p\)</span> in DMRT?</p></li>
<li><p>Explain the meaning of <span class="math inline">\(R_p\)</span> in DMRT.</p></li>
<li><p>Why does the critical range increase as <span class="math inline">\(p\)</span> increases in DMRT?</p></li>
<li><p>How does DMRT differ from LSD?</p></li>
<li><p>What is Tukey’s HSD test?</p></li>
<li><p>Explain the principle of Tukey’s test.</p></li>
<li><p>What is the studentised range statistic?</p></li>
<li><p>State the advantages of Tukey’s HSD test.</p></li>
<li><p>Compare LSD, DMRT, and Tukey’s HSD test.</p></li>
<li><p>Why is Tukey’s test considered more conservative than LSD and DMRT?</p></li>
<li><p>What is compact letter grouping?</p></li>
<li><p>Explain the rules for assigning letters to treatment means.</p></li>
<li><p>What does it mean when two treatments share a common letter?</p></li>
<li><p>What does it mean when two treatments do not share a common letter?</p></li>
<li><p>Explain overlapping letter groups using an example.</p></li>
<li><p>What is line or underscore notation?</p></li>
<li><p>Explain the relationship between letter grouping and line notation.</p></li>
<li><p>Explain the purpose of presenting treatment means using letters rather than a complete pairwise comparison table.</p></li>
<li><p>Name some multiple comparison procedures other than LSD, DMRT, and Tukey’s test.</p></li>
<li><p>When is Dunnett’s test particularly useful?</p></li>
<li><p>What is the purpose of the Bonferroni method?</p></li>
<li><p>What is the purpose of Scheffé’s test?</p></li>
<li><p>Explain why the choice of a multiple comparison test affects the conclusions of an experiment.</p></li>
</ol>
</section>
<section id="numerical-and-conceptual-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="numerical-and-conceptual-questions">Numerical and conceptual questions</h3>
<p>Answers are given at the end of the chapter.</p>
<ol type="1">
<li><p>Explain why a significant ANOVA result does not identify which treatment means differ.</p></li>
<li><p>For 5 treatments, calculate the total number of possible pairwise comparisons.</p></li>
<li><p>If each of 10 pairwise comparisons is performed at <span class="math inline">\(\alpha=0.05\)</span> without correction, calculate the approximate family-wise Type I error rate using the formula given in the chapter.</p></li>
<li><p>An ANOVA gives a non-significant treatment effect. Should Fisher’s LSD, DMRT, or Tukey’s test be conducted? Give a reason.</p></li>
<li><p>An experiment has four treatments with equal replications. The MSE is 0.5333, <span class="math inline">\(r=4\)</span>, and <span class="math inline">\(edf=15\)</span>. Calculate the LSD at the 5% level using <span class="math inline">\(t_{0.025,15}=2.131\)</span>.</p></li>
<li><p>Two treatment means are 25.5 and 24.0, and the LSD is 1.10. Determine whether the two treatments differ significantly.</p></li>
<li><p>Two treatment means are 25.5 and 24.0, and Tukey’s HSD is 1.59. Determine whether the two treatments differ significantly.</p></li>
<li><p>Explain why a treatment difference of 1.5 is significant under LSD but not significant under Tukey’s HSD in the worked example.</p></li>
<li><p>Calculate the standard error of a treatment mean when MSE = 0.5333 and <span class="math inline">\(r=4\)</span>.</p></li>
<li><p>In a DMRT analysis, two means are separated by one intermediate mean. What value of <span class="math inline">\(p\)</span> should be used?</p></li>
<li><p>In a DMRT analysis, two adjacent means are being compared. What value of <span class="math inline">\(p\)</span> should be used?</p></li>
<li><p>If two treatment means are separated by two intermediate means, determine the appropriate <span class="math inline">\(p\)</span> value.</p></li>
<li><p>Given <span class="math inline">\(SE(\overline{Y})=0.3651\)</span> and <span class="math inline">\(r_p=3.160\)</span>, calculate <span class="math inline">\(R_p\)</span>.</p></li>
<li><p>In a DMRT analysis, a difference between two means is 1.20 and the corresponding <span class="math inline">\(R_p\)</span> is 1.15. State the conclusion.</p></li>
<li><p>In a DMRT analysis, a difference between two means is 1.10 and the corresponding <span class="math inline">\(R_p\)</span> is 1.15. State the conclusion.</p></li>
<li><p>Arrange the following treatment means in descending order for DMRT: 21.0, 31.0, 24.0, 25.5, and 22.5.</p></li>
<li><p>Explain why DMRT uses different critical ranges for different pairs of means.</p></li>
<li><p>For 5 treatments with <span class="math inline">\(MSE=0.5333\)</span>, <span class="math inline">\(r=4\)</span>, and <span class="math inline">\(q=4.367\)</span>, calculate Tukey’s HSD.</p></li>
<li><p>Using an HSD of 1.59, identify which of the following differences are significant: 5.5, 7.0, 8.5, 10.0, 1.5, 3.0.</p></li>
<li><p>In the worked example, explain why <span class="math inline">\(T_3\)</span> and <span class="math inline">\(T_2\)</span> share a letter under Tukey’s test.</p></li>
<li><p>Explain why <span class="math inline">\(T_2\)</span> receives the grouping <span class="math inline">\(bc\)</span> in the Tukey example.</p></li>
<li><p>Explain why <span class="math inline">\(T_4\)</span> receives the grouping <span class="math inline">\(cd\)</span> in the Tukey example.</p></li>
<li><p>Construct the compact letter grouping for the Tukey results in the worked example.</p></li>
<li><p>Construct the compact letter grouping for the LSD results in the worked example.</p></li>
<li><p>Explain why every treatment receives a different letter under LSD and DMRT in the worked example.</p></li>
</ol>
</section>
<section id="important-formulae" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="important-formulae">Important formulae</h3>
<p>Number of pairwise comparisons among <span class="math inline">\(v\)</span> treatments:</p>
<p><span class="math display">\[
N=\binom{v}{2}=\frac{v(v-1)}{2}
\]</span></p>
<p>Inflated Type I error rate:</p>
<p><span class="math display">\[
\text{Inflated }\alpha=1-(1-\alpha)^N
\]</span></p>
<p>Standard error of the difference between two treatment means:</p>
<p><span class="math display">\[
SE(d)=\sqrt{\text{MSE}\left(\frac{1}{r_i}+\frac{1}{r_j}\right)}
\]</span></p>
<p>Fisher’s LSD:</p>
<p><span class="math display">\[
\text{LSD}=t_{\frac{\alpha}{2},\,edf}\cdot SE(d)
\]</span></p>
<p>LSD for equal replications:</p>
<p><span class="math display">\[
\text{LSD}=t_{\frac{\alpha}{2},\,edf}\cdot\sqrt{\frac{2\text{MSE}}{r}}
\]</span></p>
<p>Test statistic for pairwise comparison:</p>
<p><span class="math display">\[
t=\frac{\overline{T_i}-\overline{T_j}}{SE(d)}
\]</span></p>
<p>Standard error of a treatment mean in DMRT:</p>
<p><span class="math display">\[
SE(\overline{Y})=\sqrt{\frac{\text{MSE}}{r}}
\]</span></p>
<p>Shortest significant range in DMRT:</p>
<p><span class="math display">\[
R_p=r_p\cdot SE(\overline{Y})
\]</span></p>
<p>Tukey’s honestly significant difference:</p>
<p><span class="math display">\[
\text{HSD}=q_{\alpha,(v,edf)}\cdot\sqrt{\frac{\text{MSE}}{r}}
\]</span></p>
</section>
<section id="quick-revision" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="quick-revision">Quick revision</h3>
<ul>
<li><p>ANOVA → omnibus test for detecting an overall treatment effect.</p></li>
<li><p>Significant ANOVA → indicates that at least one pair of treatment means differs.</p></li>
<li><p>ANOVA alone → does not identify which specific treatment pairs differ.</p></li>
<li><p>Multiple comparison tests → used to identify specific differences among treatment means.</p></li>
<li><p>Post-hoc tests → should generally be conducted after a significant ANOVA.</p></li>
<li><p>Type I error → rejecting a true null hypothesis.</p></li>
<li><p>Type II error → failing to reject a false null hypothesis.</p></li>
<li><p>Family → complete set of pairwise comparisons in an experiment.</p></li>
<li><p>FWER → probability of making at least one Type I error within the family of comparisons.</p></li>
<li><p>Number of pairwise comparisons → <span class="math inline">\(v(v-1)/2\)</span>.</p></li>
<li><p>Fisher’s LSD → two-step procedure involving significant ANOVA followed by pairwise comparisons.</p></li>
<li><p>LSD → Least Significant Difference.</p></li>
<li><p>CD → Critical Difference; commonly used term for LSD in Indian agricultural research.</p></li>
<li><p>Protected LSD → pairwise comparisons are performed only after a significant ANOVA.</p></li>
<li><p>Decision under LSD → if <span class="math inline">\(|\overline{T_i}-\overline{T_j}|&gt;\text{LSD}\)</span>, the means differ significantly.</p></li>
<li><p>Equal replications → <span class="math inline">\(\text{LSD}=t_{\alpha/2,edf}\sqrt{2\text{MSE}/r}\)</span>.</p></li>
<li><p>LSD is relatively liberal compared with Tukey’s test.</p></li>
<li><p>Fisher’s LSD controls experiment-wise Type I error effectively only when the number of treatments is exactly three, as discussed in the chapter.</p></li>
<li><p>DMRT → Duncan’s Multiple Range Test.</p></li>
<li><p>DMRT → useful when comparing many treatment means and widely used in plant sciences.</p></li>
<li><p>DMRT procedure → rank means, calculate standard error, obtain <span class="math inline">\(r_p\)</span>, calculate <span class="math inline">\(R_p\)</span>, and compare differences with the appropriate <span class="math inline">\(R_p\)</span>.</p></li>
<li><p>In DMRT, <span class="math inline">\(p\)</span> → number of ordered treatment means spanned by the comparison, including the two means being compared.</p></li>
<li><p>Adjacent means → <span class="math inline">\(p=2\)</span>.</p></li>
<li><p>One mean between the two means → <span class="math inline">\(p=3\)</span>.</p></li>
<li><p>Two means between the two means → <span class="math inline">\(p=4\)</span>.</p></li>
<li><p>DMRT critical range → increases as <span class="math inline">\(p\)</span> increases.</p></li>
<li><p>DMRT → generally more powerful and more liberal than Tukey’s test.</p></li>
<li><p>Tukey’s HSD → compares all possible pairs while controlling the family-wise error rate.</p></li>
<li><p>Tukey’s test → based on the studentised range statistic <span class="math inline">\(q\)</span>.</p></li>
<li><p>HSD → single critical difference for equal replications.</p></li>
<li><p>Decision under Tukey → if <span class="math inline">\(|\overline{T_i}-\overline{T_j}|&gt;\text{HSD}\)</span>, the means differ significantly.</p></li>
<li><p>Tukey’s test → more conservative than LSD and DMRT.</p></li>
<li><p>More conservative test → less likely to declare a difference significant.</p></li>
<li><p>In the worked example → LSD = 1.10.</p></li>
<li><p>In the worked example → DMRT <span class="math inline">\(R_p\)</span> values range from 1.10 to 1.21.</p></li>
<li><p>In the worked example → Tukey HSD = 1.59.</p></li>
<li><p>Under LSD and DMRT → all treatment pairs are significant.</p></li>
<li><p>Under Tukey → differences of 1.5 are not significant.</p></li>
<li><p>Tukey therefore identifies fewer significant differences than LSD and DMRT in the example.</p></li>
<li><p>Compact letter grouping → convenient presentation of multiple comparison results.</p></li>
<li><p>Same letter → treatments are not significantly different.</p></li>
<li><p>No common letter → treatments are significantly different.</p></li>
<li><p>A treatment can have more than one letter when it belongs to overlapping non-significant groups.</p></li>
<li><p>Letter grouping is also called alphabet notation.</p></li>
<li><p>Line or underscore notation → older method of presenting groups of means.</p></li>
<li><p>Letter and line notation → convey the same statistical information.</p></li>
<li><p>Dunnett’s test → useful when every treatment is compared with a single control.</p></li>
<li><p>Bonferroni method → adjusts significance for multiple comparisons.</p></li>
<li><p>Scheffé’s test → useful for general contrasts among means.</p></li>
<li><p>SNK → Student-Newman-Keuls multiple comparison procedure.</p></li>
</ul>
</section>
<section id="answers-to-fill-in-the-blanks" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="answers-to-fill-in-the-blanks">Answers to fill in the blanks</h3>
<div class="answer-key">
<p><code>1.</code> Omnibus <code>2.</code> Pairs <code>3.</code> Multiple <code>4.</code> Post-hoc <code>5.</code> F <code>6.</code> Different <code>7.</code> I <code>8.</code> II <code>9.</code> Family <code>10.</code> Family-wise <code>11.</code> <span class="math inline">\(\dfrac{v(v-1)}{2}\)</span> <code>12.</code> LSD <code>13.</code> Fisher <code>14.</code> Critical <code>15.</code> Significant <code>16.</code> Protected <code>17.</code> ANOVA <code>18.</code> MSE <code>19.</code> Different <code>20.</code> DMRT <code>21.</code> Duncan <code>22.</code> Descending <code>23.</code> Spanned <code>24.</code> <span class="math inline">\(r_p\)</span> <code>25.</code> <span class="math inline">\(R_p\)</span> <code>26.</code> <span class="math inline">\(r_p \cdot SE(\overline{Y})\)</span> <code>27.</code> Larger <code>28.</code> Difference <code>29.</code> John Tukey <code>30.</code> Studentised <code>31.</code> HSD <code>32.</code> Entire <code>33.</code> Conservative <code>34.</code> Compact letter <code>35.</code> Different <code>36.</code> Line <code>37.</code> Multiple <code>38.</code> Multiple <code>39.</code> Control <code>40.</code> Contrasts</p>
</div>
</section>
<section id="solutions-to-numerical-and-conceptual-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="solutions-to-numerical-and-conceptual-questions">Solutions to numerical and conceptual questions</h3>
<ol type="1">
<li><p>A significant ANOVA rejects the overall null hypothesis, showing that at least one pair of treatment means differs, but because it is an omnibus test it does not indicate which specific pair or pairs are responsible, so pairwise post-hoc tests are required.</p></li>
<li><p>Using <a href="#eq-inflated" class="quarto-xref">Equation&nbsp;<span>19.1</span></a> context, the number of pairwise comparisons is <span class="math inline">\(\dfrac{v(v-1)}{2} = \dfrac{5 \times 4}{2} = 10\)</span>.</p></li>
<li><p>Using <a href="#eq-inflated" class="quarto-xref">Equation&nbsp;<span>19.1</span></a>, inflated <span class="math inline">\(\alpha = 1-(1-0.05)^{10} = 1-(0.95)^{10} = 0.40\)</span>, about 40%.</p></li>
<li><p>None of them should be conducted, since a non-significant ANOVA means there is no overall treatment effect, and post-hoc tests require a significant omnibus F test first.</p></li>
<li><p>Using <a href="#eq-lsdequal" class="quarto-xref">Equation&nbsp;<span>19.5</span></a>, <span class="math inline">\(\text{LSD} = 2.131 \times \sqrt{\dfrac{2 \times 0.5333}{4}} = 2.131 \times 0.5164 = 1.10\)</span>.</p></li>
<li><p>The difference is <span class="math inline">\(25.5-24.0 = 1.5\)</span>, which exceeds the LSD of 1.10, so the two treatments differ significantly.</p></li>
<li><p>The difference is <span class="math inline">\(25.5-24.0 = 1.5\)</span>, which is less than the HSD of 1.59, so the two treatments do not differ significantly.</p></li>
<li><p>The difference 1.5 exceeds the LSD (1.10) but not the HSD (1.59); Tukey’s test uses a larger critical value because it controls the family-wise error rate over all comparisons, so it is more conservative than the LSD.</p></li>
<li><p>Using <a href="#eq-sedmrt" class="quarto-xref">Equation&nbsp;<span>19.7</span></a>, <span class="math inline">\(SE(\overline{Y}) = \sqrt{\dfrac{0.5333}{4}} = 0.3651\)</span>.</p></li>
<li><p>When one mean lies between the two means being compared, <span class="math inline">\(p = 3\)</span>.</p></li>
<li><p>For two adjacent means, <span class="math inline">\(p = 2\)</span>.</p></li>
<li><p>When two means lie between the two being compared, <span class="math inline">\(p = 4\)</span>.</p></li>
<li><p>Using <a href="#eq-rp" class="quarto-xref">Equation&nbsp;<span>19.8</span></a>, <span class="math inline">\(R_p = 3.160 \times 0.3651 = 1.15\)</span>.</p></li>
<li><p>The difference 1.20 exceeds <span class="math inline">\(R_p = 1.15\)</span>, so the two means differ significantly.</p></li>
<li><p>The difference 1.10 is less than <span class="math inline">\(R_p = 1.15\)</span>, so the two means do not differ significantly (they are at par).</p></li>
<li><p>In descending order: 31.0, 25.5, 24.0, 22.5, 21.0 (that is, <span class="math inline">\(T_5, T_3, T_2, T_4, T_1\)</span>).</p></li>
<li><p>DMRT uses the shortest significant range <span class="math inline">\(R_p = r_p \cdot SE(\overline{Y})\)</span>, and since <span class="math inline">\(r_p\)</span> increases with <span class="math inline">\(p\)</span>, means that are farther apart in the ranked order are compared against a larger critical value.</p></li>
<li><p>Using <a href="#eq-hsd" class="quarto-xref">Equation&nbsp;<span>19.9</span></a>, <span class="math inline">\(\text{HSD} = 4.367 \times \sqrt{\dfrac{0.5333}{4}} = 4.367 \times 0.3651 = 1.59\)</span>.</p></li>
<li><p>With HSD <span class="math inline">\(= 1.59\)</span>: the differences 5.5, 7.0, 8.5, 10.0, and 3.0 exceed 1.59 and are significant, while 1.5 is less than 1.59 and is not significant.</p></li>
<li><p>Their means (25.5 and 24.0) differ by 1.5, which is less than the HSD of 1.59, so <span class="math inline">\(T_3\)</span> and <span class="math inline">\(T_2\)</span> are not significantly different and share the letter b.</p></li>
<li><p><span class="math inline">\(T_2\)</span> is not significantly different from <span class="math inline">\(T_3\)</span> (so it shares b) and also not significantly different from <span class="math inline">\(T_4\)</span> (so a new letter c begins at <span class="math inline">\(T_2\)</span>), giving it the overlapping grouping <span class="math inline">\(bc\)</span>.</p></li>
<li><p><span class="math inline">\(T_4\)</span> is not significantly different from <span class="math inline">\(T_2\)</span> (sharing c) and not significantly different from <span class="math inline">\(T_1\)</span> (starting d), giving it the overlapping grouping <span class="math inline">\(cd\)</span>.</p></li>
<li><p>The Tukey grouping is <span class="math inline">\(T_5\)</span>: a, <span class="math inline">\(T_3\)</span>: b, <span class="math inline">\(T_2\)</span>: bc, <span class="math inline">\(T_4\)</span>: cd, <span class="math inline">\(T_1\)</span>: d.</p></li>
<li><p>Under LSD every pair differs significantly, so each treatment gets its own letter: <span class="math inline">\(T_5\)</span>: a, <span class="math inline">\(T_3\)</span>: b, <span class="math inline">\(T_2\)</span>: c, <span class="math inline">\(T_4\)</span>: d, <span class="math inline">\(T_1\)</span>: e.</p></li>
<li><p>Under LSD and DMRT the critical values (1.10 to 1.21) are smaller than every pairwise difference (the smallest being 1.5), so all pairs are significant and no two treatments share a letter.</p></li>
</ol>



<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Hayter" class="csl-entry" role="listitem">
Hayter, Anthony J. 1986. <span>“The Maximum Familywise Error Rate of Fisher’s Least Significant Difference Test.”</span> <em>Journal of the American Statistical Association</em> 81 (396): 1000–1004. <a href="https://doi.org/10.1080/01621459.1986.10478364">https://doi.org/10.1080/01621459.1986.10478364</a>.
</div>
<div id="ref-Lee" class="csl-entry" role="listitem">
Lee, Sangseok, and Dong Kyu Lee. 2018. <span>“What Is the Proper Way to Apply the Multiple Comparison Test?”</span> <em>Korean Journal of Anesthesiology</em> 71 (5): 353–60. <a href="https://doi.org/10.4097/kja.d.18.00242">https://doi.org/10.4097/kja.d.18.00242</a>.
</div>
<div id="ref-Meier" class="csl-entry" role="listitem">
Meier, Ulrich. 2006. <span>“A Note on the Power of Fisher’s Least Significant Difference Procedure.”</span> <em>Pharmaceutical Statistics</em> 5 (4): 253–63. <a href="https://doi.org/10.1002/pst.210">https://doi.org/10.1002/pst.210</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.agrinoteskau\.com\/agstat-textbook\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./anova.html" class="pagination-link" aria-label="Analysis of variance">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analysis of variance</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./singleFactor.html" class="pagination-link" aria-label="Single factor experiments">
        <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Single factor experiments</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Published by PAPAYA publishing division of <a href="https://www.statoberry.com/papaya"><img src=".\images/statoberry.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>   
    <div class="nav-footer-center">
<p><a href="https://www.statoberry.com/papaya"><img src=".\images/papayalogo.png" class="img-fluid" style="width: auto; height: 90px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>
    <div class="nav-footer-right">
<p>Licenced under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC-BY-NC-ND 4.0 Int License</a> <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img src=".\images/cclogo.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a> Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>