<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>20&nbsp; Single factor experiments – TEXTBOOK OF AGRICULTURAL STATISTICS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./factorial.html" rel="next">
<link href="./multipleComparison.html" rel="prev">
<link href="./images/cover.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d166b450ba5a8e9f7a0ab969bf6592c1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9fe799a8b491b95f8638fac26051bc8e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-bad6a7b64396174f9e6ce9f1aaf6e4b8.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="20&nbsp; Single factor experiments – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:description" content="">
<meta property="og:image" content="https://www.agrinoteskau.com/agstat-textbook.html/images/cover.jpg">
<meta property="og:site_name" content="TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:title" content="20&nbsp; Single factor experiments – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://www.agrinoteskau.com/agstat-textbook.html/images/papayalogo.png">
<meta name="twitter:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="541">
<meta name="twitter:image-width" content="956">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./singleFactor.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Single factor experiments</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/sidebarcover.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEXTBOOK OF AGRICULTURAL STATISTICS</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basics of statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agstatindia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Official agricultural statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical representation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Central tendency I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Central tendency II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dispersion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measures of dispersion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./skewness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Skewness and kurtosis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./association.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of association</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probabilitydist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampleSurvey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Sample survey</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesisTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./largeSampletest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Large sample test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smallsampleTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Small sample tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./designofexperiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Design of experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uniformityTrials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Uniformity trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analysis of variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multipleComparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple comparison tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleFactor.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Single factor experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./factorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Factorial experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analysis of covariance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./missingPlot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Missing plot analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Appendix 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Appendix 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Appendix 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Appendix 4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Appendix 5</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_personalities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Appendix 6</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-crd" id="toc-sec-crd" class="nav-link active" data-scroll-target="#sec-crd"><span class="header-section-number">20.1</span> Completely Randomized Design (CRD)</a>
  <ul class="collapse">
  <li><a href="#sec-random1" id="toc-sec-random1" class="nav-link" data-scroll-target="#sec-random1"><span class="header-section-number">20.1.1</span> Randomization procedure</a></li>
  <li><a href="#layout-of-crd" id="toc-layout-of-crd" class="nav-link" data-scroll-target="#layout-of-crd"><span class="header-section-number">20.1.2</span> Layout of CRD</a></li>
  <li><a href="#statistical-model-for-crd" id="toc-statistical-model-for-crd" class="nav-link" data-scroll-target="#statistical-model-for-crd"><span class="header-section-number">20.1.3</span> Statistical model for CRD</a></li>
  <li><a href="#analysis-of-crd" id="toc-analysis-of-crd" class="nav-link" data-scroll-target="#analysis-of-crd"><span class="header-section-number">20.1.4</span> Analysis of CRD</a></li>
  <li><a href="#sec-replical" id="toc-sec-replical" class="nav-link" data-scroll-target="#sec-replical"><span class="header-section-number">20.1.5</span> Replications in CRD</a></li>
  <li><a href="#advantages-of-a-crd" id="toc-advantages-of-a-crd" class="nav-link" data-scroll-target="#advantages-of-a-crd"><span class="header-section-number">20.1.6</span> Advantages of a CRD</a></li>
  <li><a href="#disadvantages-of-a-crd" id="toc-disadvantages-of-a-crd" class="nav-link" data-scroll-target="#disadvantages-of-a-crd"><span class="header-section-number">20.1.7</span> Disadvantages of a CRD</a></li>
  </ul></li>
  <li><a href="#randomized-complete-block-designs-rcbd" id="toc-randomized-complete-block-designs-rcbd" class="nav-link" data-scroll-target="#randomized-complete-block-designs-rcbd"><span class="header-section-number">20.2</span> Randomized Complete Block Designs (RCBD)</a>
  <ul class="collapse">
  <li><a href="#blocking-technique" id="toc-blocking-technique" class="nav-link" data-scroll-target="#blocking-technique"><span class="header-section-number">20.2.1</span> Blocking technique</a></li>
  <li><a href="#sec-rcbdrandom" id="toc-sec-rcbdrandom" class="nav-link" data-scroll-target="#sec-rcbdrandom"><span class="header-section-number">20.2.2</span> Randomization in RCBD</a></li>
  <li><a href="#layout-of-rcbd" id="toc-layout-of-rcbd" class="nav-link" data-scroll-target="#layout-of-rcbd"><span class="header-section-number">20.2.3</span> Layout of RCBD</a></li>
  <li><a href="#statistical-model-for-rcbd" id="toc-statistical-model-for-rcbd" class="nav-link" data-scroll-target="#statistical-model-for-rcbd"><span class="header-section-number">20.2.4</span> Statistical Model for RCBD</a></li>
  <li><a href="#analysis-of-rcbd" id="toc-analysis-of-rcbd" class="nav-link" data-scroll-target="#analysis-of-rcbd"><span class="header-section-number">20.2.5</span> Analysis of RCBD</a></li>
  <li><a href="#post-hoc-test-in-rcbd" id="toc-post-hoc-test-in-rcbd" class="nav-link" data-scroll-target="#post-hoc-test-in-rcbd"><span class="header-section-number">20.2.6</span> Post-hoc test in RCBD</a></li>
  <li><a href="#replications-in-rcbd" id="toc-replications-in-rcbd" class="nav-link" data-scroll-target="#replications-in-rcbd"><span class="header-section-number">20.2.7</span> Replications in RCBD</a></li>
  <li><a href="#advantages-of-rcbd" id="toc-advantages-of-rcbd" class="nav-link" data-scroll-target="#advantages-of-rcbd"><span class="header-section-number">20.2.8</span> Advantages of RCBD</a></li>
  <li><a href="#disadvantages-of-rcbd" id="toc-disadvantages-of-rcbd" class="nav-link" data-scroll-target="#disadvantages-of-rcbd"><span class="header-section-number">20.2.9</span> Disadvantages of RCBD</a></li>
  </ul></li>
  <li><a href="#latin-square-design-lsd" id="toc-latin-square-design-lsd" class="nav-link" data-scroll-target="#latin-square-design-lsd"><span class="header-section-number">20.3</span> Latin Square Design (LSD)</a>
  <ul class="collapse">
  <li><a href="#sec-lsdrandom" id="toc-sec-lsdrandom" class="nav-link" data-scroll-target="#sec-lsdrandom"><span class="header-section-number">20.3.1</span> Randomization</a></li>
  <li><a href="#layout" id="toc-layout" class="nav-link" data-scroll-target="#layout"><span class="header-section-number">20.3.2</span> Layout</a></li>
  <li><a href="#statistical-model-for-lsd" id="toc-statistical-model-for-lsd" class="nav-link" data-scroll-target="#statistical-model-for-lsd"><span class="header-section-number">20.3.3</span> Statistical model for LSD</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">20.3.4</span> Analysis</a></li>
  <li><a href="#post-hoc-test-lsd" id="toc-post-hoc-test-lsd" class="nav-link" data-scroll-target="#post-hoc-test-lsd"><span class="header-section-number">20.3.5</span> Post hoc test (LSD)</a></li>
  <li><a href="#replications-in-lsd" id="toc-replications-in-lsd" class="nav-link" data-scroll-target="#replications-in-lsd"><span class="header-section-number">20.3.6</span> Replications in LSD</a></li>
  <li><a href="#advantages-of-lsd" id="toc-advantages-of-lsd" class="nav-link" data-scroll-target="#advantages-of-lsd"><span class="header-section-number">20.3.7</span> Advantages of LSD</a></li>
  <li><a href="#disadvantages-of-lsd" id="toc-disadvantages-of-lsd" class="nav-link" data-scroll-target="#disadvantages-of-lsd"><span class="header-section-number">20.3.8</span> Disadvantages of LSD</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">20.4</span> Chapter Summary</a>
  <ul class="collapse">
  <li><a href="#fill-in-the-blanks" id="toc-fill-in-the-blanks" class="nav-link" data-scroll-target="#fill-in-the-blanks">Fill in the blanks</a></li>
  <li><a href="#short-answer-questions" id="toc-short-answer-questions" class="nav-link" data-scroll-target="#short-answer-questions">Short-answer questions</a></li>
  <li><a href="#numerical-and-conceptual-questions" id="toc-numerical-and-conceptual-questions" class="nav-link" data-scroll-target="#numerical-and-conceptual-questions">Numerical and conceptual questions</a></li>
  <li><a href="#important-formulae" id="toc-important-formulae" class="nav-link" data-scroll-target="#important-formulae">Important formulae</a></li>
  <li><a href="#quick-revision" id="toc-quick-revision" class="nav-link" data-scroll-target="#quick-revision">Quick revision</a></li>
  <li><a href="#answers-to-fill-in-the-blanks" id="toc-answers-to-fill-in-the-blanks" class="nav-link" data-scroll-target="#answers-to-fill-in-the-blanks">Answers to fill in the blanks</a></li>
  <li><a href="#solutions-to-numerical-and-conceptual-questions" id="toc-solutions-to-numerical-and-conceptual-questions" class="nav-link" data-scroll-target="#solutions-to-numerical-and-conceptual-questions">Solutions to numerical and conceptual questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Single factor experiments</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Experiments in which only a single factor varies while all others are kept constant are called single-factor experiments. In such experiments, the treatments consist solely of the different levels of the single variable factor. All other factors are maintained uniformly across all experimental units.</p>
<p><strong>Examples:</strong></p>
<ol type="1">
<li><p>An experiment to find the best nitrogen level for getting a high yield, where 5 different nitrogen levels are tested. Here, the nitrogen levels are the treatments, and all other factors like irrigation, light, and fertility gradient are assumed to be homogeneous in all experimental units (here the plots are the experimental units).</p></li>
<li><p>An experiment to find the best feed formulation for milk yield in cows from 4 feed formulas. Here, the feed formula is the only factor that varies, with 4 levels. All other factors like breed of cow, age, and so on are kept constant.</p></li>
</ol>
<section id="sec-crd" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="sec-crd"><span class="header-section-number">20.1</span> Completely Randomized Design (CRD)</h2>
<p>Completely Randomized Design is the basic single factor design. In this design the treatments are assigned completely at random so that each experimental unit has the same chance of receiving any one treatment. CRD is only appropriate for experiments with homogeneous experimental units, such as laboratory and green house experiments, where environmental effects are relatively easy to control. For field experiments, where there is generally large variation among experimental plots, CRD is rarely used.</p>
<p>CRD provides a layout for conducting experiments, when experimental units are homogeneous. Only two basic principles of design, randomization <a href="designofexperiments.html#sec-rand" class="quarto-xref"><span>Section 16.7.1</span></a> and replication <a href="designofexperiments.html#sec-rep" class="quarto-xref"><span>Section 16.7.2</span></a> are followed in CRD. Local control <a href="designofexperiments.html#sec-local" class="quarto-xref"><span>Section 16.7.3</span></a> is not required as all the experimental units are homogeneous. Treatments can have unequal replications in CRD.</p>
<section id="sec-random1" class="level3" data-number="20.1.1">
<h3 data-number="20.1.1" class="anchored" data-anchor-id="sec-random1"><span class="header-section-number">20.1.1</span> Randomization procedure</h3>
<p>Consider an experiment involving four treatments A, B, C, D in CRD. Each treatment is replicated 5 times. Randomization procedure is as explained below.</p>
<ol type="1">
<li><p>Determine the total number of experimental units (<span class="math inline">\(n\)</span>) as the product of the number of treatments (<span class="math inline">\(v\)</span>) and the number of replications (<span class="math inline">\(r\)</span>); that is, <span class="math inline">\(n = r\ \times v\)</span>. For our example, <span class="math inline">\(n = 5 \times 4 = 20\)</span></p></li>
<li><p>Assign a unit number to each experimental units in any convenient manner; for example, consecutively from 1 to n.&nbsp;For our example, the unit numbers 1, 2,... , 20 are assigned to the 20 experimental units as shown in Figure <a href="#fig-crdnumbered" class="quarto-xref">Figure&nbsp;<span>20.1</span></a></p></li>
<li><p>Assign the treatments to the experimental plots by using any randomization schemes. Here we explain a simple randomization scheme in section <a href="#sec-random" class="quarto-xref"><span>Section 20.1.1.1</span></a>.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-crdnumbered" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-crdnumbered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/crdnumbered.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-crdnumbered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.1: Numbered experimental units
</figcaption>
</figure>
</div>
</div>
</div>
<section id="sec-random" class="level4">
<h4 class="anchored" data-anchor-id="sec-random">Randomization by drawing lots</h4>
<ol type="1">
<li><p>Prepare <span class="math inline">\(n\)</span> identical pieces of paper and divide them into <span class="math inline">\(v\)</span> groups, each group with <span class="math inline">\(r\)</span> pieces of paper. Label each piece of paper of the same group with the same letter (or number) corresponding to a treatment. Uniformly fold each of the <span class="math inline">\(n\)</span> labeled pieces of paper, mix them thoroughly, and place them in a container. For our example, there should be 20 pieces of paper, five each with treatments A, B, C, and D appearing on them.</p></li>
<li><p>Draw one piece of paper at a time, without replacement and with constant shaking of the container after each draw to mix its content. For our example, the label and the corresponding sequence in which each piece of paper is drawn. The sequence number can be considered as the experimental unit number to which the treatment is to be assigned.</p></li>
</ol>
<div id="tbl-sequence" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Sequence in which labelled lots are drawn" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.1: Sequence in which labelled lots are drawn
</figcaption>
<div aria-describedby="tbl-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:center;width: 2.8cm; font-weight: bold;font-weight: bold;">
Treatment Label
</td>
<td style="text-align:center;font-weight: bold;">
D
</td>
<td style="text-align:center;font-weight: bold;">
B
</td>
<td style="text-align:center;font-weight: bold;">
A
</td>
<td style="text-align:center;font-weight: bold;">
B
</td>
<td style="text-align:center;font-weight: bold;">
C
</td>
<td style="text-align:center;font-weight: bold;">
A
</td>
<td style="text-align:center;font-weight: bold;">
D
</td>
<td style="text-align:center;font-weight: bold;">
A
</td>
<td style="text-align:center;font-weight: bold;">
A
</td>
<td style="text-align:center;font-weight: bold;">
B
</td>
</tr>
<tr>
<td style="text-align:center;width: 2.8cm; font-weight: bold;">
Sequence
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
10
</td>
</tr>
<tr>
<td style="text-align:center;width: 2.8cm; font-weight: bold;font-weight: bold;">
Treatment Label
</td>
<td style="text-align:center;font-weight: bold;">
C
</td>
<td style="text-align:center;font-weight: bold;">
D
</td>
<td style="text-align:center;font-weight: bold;">
C
</td>
<td style="text-align:center;font-weight: bold;">
D
</td>
<td style="text-align:center;font-weight: bold;">
B
</td>
<td style="text-align:center;font-weight: bold;">
B
</td>
<td style="text-align:center;font-weight: bold;">
A
</td>
<td style="text-align:center;font-weight: bold;">
C
</td>
<td style="text-align:center;font-weight: bold;">
D
</td>
<td style="text-align:center;font-weight: bold;">
C
</td>
</tr>
<tr>
<td style="text-align:center;width: 2.8cm; font-weight: bold;">
Sequence
</td>
<td style="text-align:center;">
11
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
20
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="layout-of-crd" class="level3" data-number="20.1.2">
<h3 data-number="20.1.2" class="anchored" data-anchor-id="layout-of-crd"><span class="header-section-number">20.1.2</span> Layout of CRD</h3>
<p>After allotting the treatment according to the randomization procedure explained in section <a href="#sec-random1" class="quarto-xref"><span>Section 20.1.1</span></a>. The final layout will look like in the figure <a href="#fig-layout" class="quarto-xref">Figure&nbsp;<span>20.2</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-layout" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-layout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/layoutcrd.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-layout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.2: Layout of Completely Randomized Design
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="statistical-model-for-crd" class="level3" data-number="20.1.3">
<h3 data-number="20.1.3" class="anchored" data-anchor-id="statistical-model-for-crd"><span class="header-section-number">20.1.3</span> Statistical model for CRD</h3>
<p>Consider a CRD with <em>v</em> treatments with <em>r</em> replications. Statistical model for CRD is same as that of one-way ANOVA (<a href="anova.html#sec-onewaymodel" class="quarto-xref"><span>Section 18.6.1.1</span></a>).<br>
<span class="math display">\[Y_{\text{ij}} = \mu + \tau_{i} + e_{\text{ij}}\]</span><br>
Where <em>i</em> = 1,2, …, <em>v</em> and <em>j</em> =1,2, …, <em>r</em><sub>i</sub>. <span class="math inline">\(Y_{\text{ij}}\)</span> is the observed value of <span class="math inline">\(i^{\text{th}}\)</span> treatment from <span class="math inline">\(j^{\text{th}}\)</span> replication, <span class="math inline">\(\tau_{i}\)</span> is the effect of <span class="math inline">\(i^{\text{th}}\)</span> treatment. <span class="math inline">\(\mu\)</span> is the general effect which is common for all treatments. <span class="math inline">\(e_{\text{ij}}\)</span> is the error effects.<span class="math inline">\(e_{ij}\)</span> <span class="math inline">\(\sim iid\ N(0,\sigma^{2})\)</span></p>
</section>
<section id="analysis-of-crd" class="level3" data-number="20.1.4">
<h3 data-number="20.1.4" class="anchored" data-anchor-id="analysis-of-crd"><span class="header-section-number">20.1.4</span> Analysis of CRD</h3>
<p>Analysis of CRD is same as that explained in section <a href="anova.html#sec-onewaycalc" class="quarto-xref"><span>Section 18.6.1.5</span></a> of one-way ANOVA.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Unequal replication (<em>i</em>.<em>e</em>. each treatment can have a different number of replications) is possible in CRD. So while calculating the treatment sum of squares, each treatment total is squared and divided by its corresponding replication, and then the sum is taken. If the replication is the same for all treatments, the treatment sum of squares is obtained by taking the sum of the squares of the treatment totals and dividing by the common replication number.</p>
</div>
</div>
<div id="tbl-crdanova" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="ANOVA table of CRD" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crdanova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.2: ANOVA table of CRD
</figcaption>
<div aria-describedby="tbl-crdanova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Source
</th>
<th style="text-align:center;font-weight: bold;">
D.F.
</th>
<th style="text-align:center;font-weight: bold;">
S.S
</th>
<th style="text-align:center;font-weight: bold;">
M.S.S
</th>
<th style="text-align:center;font-weight: bold;">
F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Treatments
</td>
<td style="text-align:center;">
<span class="math inline">\(v-1\)</span>
</td>
<td style="text-align:center;width: 5.5cm; padding-right: 22px;">
<span class="math inline">\(\text{SST} = \sum_{i=1}^{v}\dfrac{T_i^2}{r_i} - \text{C.F.}\)</span>
</td>
<td style="text-align:center;width: 4cm; padding-left: 22px;">
<span class="math inline">\(\text{MST}=\dfrac{\text{SST}}{v-1}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(F = \dfrac{\text{MST}}{\text{MSE}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Error
</td>
<td style="text-align:center;">
<span class="math inline">\(n-v\)</span>
</td>
<td style="text-align:center;width: 5.5cm; padding-right: 22px;">
<span class="math inline">\(\text{Total SS} - \text{SST}\)</span>
</td>
<td style="text-align:center;width: 4cm; padding-left: 22px;">
<span class="math inline">\(\text{MSE}=\dfrac{\text{SSE}}{v(r-1)}\)</span>
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;">
Total
</td>
<td style="text-align:center;">
<span class="math inline">\(n-1\)</span>
</td>
<td style="text-align:center;width: 5.5cm; padding-right: 22px;">
<span class="math inline">\(\sum_{i=1}^{v}\sum_{j=1}^{r} y_{ij}^2 - \text{C.F.}\)</span>
</td>
<td style="text-align:center;width: 4cm; padding-left: 22px;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="sec-postcrd" class="level4">
<h4 class="anchored" data-anchor-id="sec-postcrd">Post hoc test (LSD)</h4>
<p>If the null hypothesis is rejected in ANOVA; we proceed to post-hoc test explained in section <a href="multipleComparison.html#sec-lsd" class="quarto-xref"><span>Section 19.2</span></a>. Fisher’s Least significant difference (LSD) test explained in section <a href="multipleComparison.html#sec-lsd" class="quarto-xref"><span>Section 19.2</span></a> is the commonly employed test in agricultural experiments.<br>
Arrange the treatment means in descending order. Critical difference (CD) is calculated for each treatment pair <span class="math inline">\(T_{i},\ T_{j}\)</span> using the following formula.</p>
<p><span class="math display">\[C.D. = t_{\left( \frac{\alpha}{2},\ error\ df \right)}\sqrt{\text{MSE}\left( \frac{1}{r_{i}} + \frac{1}{r_{j}} \right)}\]</span></p>
<p>(for CRD with unequal replication)</p>
<p><span class="math display">\[C.D. = t_{\left( \frac{\alpha}{2},\ error\ df \right)}\sqrt{\frac{2\,MSE}{r}}\]</span></p>
<p>(for CRD with equal replication)</p>
<p>Here <span class="math inline">\(t_{\left( \frac{\alpha}{2},\ \ \ error\ df \right)}\)</span> denotes the critical value of Student’s t for a two tailed test at α level of significance and error degrees of freedom. <span class="math inline">\(r_{i}\)</span> and <span class="math inline">\(r_{j}\)</span> are replications of <span class="math inline">\(T_{i},\ T_{j}\)</span> respectively. If the difference of any two treatment means is greater than the critical difference, they are significantly different. If the difference of any two treatment means is less than <span class="math inline">\(\text{C.D}\)</span>. they are said to be on par. (<em>i</em>.<em>e</em>., there is no any statistically significant difference). Those treatments which are at par is given same symbols or letters, such that treatment means without any common letters or symbols are significantly different at corresponding level of significance (<span class="math inline">\(\alpha\)</span>).</p>
</section>
</section>
<section id="sec-replical" class="level3" data-number="20.1.5">
<h3 data-number="20.1.5" class="anchored" data-anchor-id="sec-replical"><span class="header-section-number">20.1.5</span> Replications in CRD</h3>
<p>An experimenter is free to choose any number of replications in the experiment. The precision in estimating experimental error variance increases as the number of replications increases. But the design should be such that the number of replications should be optimum, since increasing the replications will increase the experiment cost. So, there is a rule of thumb that says, error degrees of freedom should be at least 12 to keep type II error in check. One can easily find the number of replications required in a design by using the equation for error degrees of freedom of that design.</p>
<p>It is assumed that <em>edf</em> <span class="math inline">\(\geq 12\)</span>. For CRD it is given by</p>
<p><span id="eq-crdrep"><span class="math display">\[n - v = rv - v = v\left( r - 1 \right) \geq 12 \tag{20.1}\]</span></span></p>
<p>where <span class="math inline">\(v\)</span> is the number of treatments, <span class="math inline">\(r\)</span> is the replication and <span class="math inline">\(n\)</span> is the total number of experimental units, <span class="math inline">\(n = vr\)</span>.</p>
<div id="exm-ct42" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.1</strong></span> You have 5 treatments; you are planning to conduct the experiment in CRD. Find the minimum number of replications required.</p>
<p><strong>Solution</strong></p>
<p>from <a href="#eq-crdrep" class="quarto-xref">Equation&nbsp;<span>20.1</span></a>, since v = 5, <em>edf</em> <span class="math inline">\(= 5\left( r - 1 \right) \geq 12\)</span></p>
<p><span class="math inline">\(r \geq 3.4\)</span>, since <span class="math inline">\(r\)</span> cannot be a fraction, <span class="math inline">\(r =\)</span> 4</p>
<p>The minimum number of replications required is 4.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Why is the minimum error degrees of freedom for a design taken as 12?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why is the minimum error degrees of freedom for a design taken as 12?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The error degrees of freedom play an important role in determining the critical value of F. As the error degrees of freedom (the denominator degrees of freedom) decrease, the critical value of F increases, making it more difficult to reject the null hypothesis. Consequently, the risk of a Type II error (β) increases, as a true treatment difference may go undetected unless the observed treatment effect is sufficiently large. As the denominator degrees of freedom increase, the critical value of F decreases and becomes relatively stable beyond about 10–12 degrees of freedom. Therefore, 12 error degrees of freedom is commonly taken as a practical minimum when determining the number of replications, providing a reasonable balance between statistical precision and experimental resources.</p>
<div id="fig-fcritical" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" style="text-align:center;">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fcritical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/fcritical.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="text-align:center;;width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fcritical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.3: Critical value of F against error degrees of freedom, showing stabilization beyond about 12 degrees of freedom.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="exm-ct43" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.2</strong></span> In order to find the yielding abilities of five varieties of sesame an experiment was conducted in the green house using a CRD with four pots per variety. The results are given in the following table below.</p>
<div id="tbl-crdex" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Yield data of five varieties of sesame under CRD" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crdex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.3: Yield data of five varieties of sesame under CRD
</figcaption>
<div aria-describedby="tbl-crdex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;" colspan="1">
</th>
<th style="padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; " colspan="5">
<div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
Variety
</div>
</th>
</tr>
<tr>
<th style="text-align:center;font-weight: bold;">
Replication
</th>
<th style="text-align:center;font-weight: bold;">
V1
</th>
<th style="text-align:center;font-weight: bold;">
V2
</th>
<th style="text-align:center;font-weight: bold;">
V3
</th>
<th style="text-align:center;font-weight: bold;">
V4
</th>
<th style="text-align:center;font-weight: bold;">
V5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;font-weight: bold;">
1
</td>
<td style="text-align:center;">
25.00
</td>
<td style="text-align:center;">
25.0
</td>
<td style="text-align:center;">
24.00
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
14.00
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
2
</td>
<td style="text-align:center;">
21.00
</td>
<td style="text-align:center;">
28.0
</td>
<td style="text-align:center;">
24.00
</td>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
15.00
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
3
</td>
<td style="text-align:center;">
21.00
</td>
<td style="text-align:center;">
24.0
</td>
<td style="text-align:center;">
16.00
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
13.00
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
4
</td>
<td style="text-align:center;">
18.00
</td>
<td style="text-align:center;">
25.0
</td>
<td style="text-align:center;">
21.00
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
11.00
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;font-weight: bold;">
Total
</td>
<td style="text-align:center;font-weight: bold;">
85.00
</td>
<td style="text-align:center;font-weight: bold;">
102.0
</td>
<td style="text-align:center;font-weight: bold;">
85.00
</td>
<td style="text-align:center;font-weight: bold;">
72
</td>
<td style="text-align:center;font-weight: bold;">
53.00
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;font-weight: bold;">
Mean
</td>
<td style="text-align:center;font-weight: bold;">
21.25
</td>
<td style="text-align:center;font-weight: bold;">
25.5
</td>
<td style="text-align:center;font-weight: bold;">
21.25
</td>
<td style="text-align:center;font-weight: bold;">
18
</td>
<td style="text-align:center;font-weight: bold;">
13.25
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Solution</strong></p>
<p><strong>Correction Factor</strong>:</p>
<p><span class="math inline">\(= \frac{G^{2}}{n} = \frac{\left( 397 \right)^{2}}{20}\)</span>=7880.45</p>
<p><strong>Total Sum of squares</strong>:</p>
<p><span class="math inline">\(= \left( 25^{2} + 21^{2} + .... + 11^{2} \right) - CF\)</span></p>
<p><span class="math inline">\(= 8307 - CF = 426.55\)</span></p>
<p><strong>Treatment Sum of Squares</strong>:</p>
<p><span class="math inline">\(\frac{1}{4}(85^{2} + 102^{2} + ... + 53^{2}) - CF\)</span> <span class="math inline">\(= 8211.75 - CF = 331.30\)</span></p>
<p><strong>Error Sum of Square</strong>: <span class="math inline">\(426.55 - 331.30 = 95.25\)</span></p>
<div id="tbl-crdanovaex" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="ANOVA table for the sesame variety trial" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crdanovaex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.4: ANOVA table for the sesame variety trial
</figcaption>
<div aria-describedby="tbl-crdanovaex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Sources
</th>
<th style="text-align:center;font-weight: bold;">
DF
</th>
<th style="text-align:center;font-weight: bold;">
SS
</th>
<th style="text-align:center;font-weight: bold;">
MSS
</th>
<th style="text-align:center;font-weight: bold;">
F (Calculated)
</th>
<th style="text-align:center;font-weight: bold;">
F (Tabulated)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;font-weight: bold;">
Varieties
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
331.30
</td>
<td style="text-align:center;">
82.825
</td>
<td style="text-align:center;">
13.043**
</td>
<td style="text-align:center;">
F(4,15) = 3.06 (5% level)
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Error
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
95.25
</td>
<td style="text-align:center;">
6.35
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Total
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
426.55
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Since the F value calculated is greater than table value of F, we can reject the null hypothesis and conclude that there is a significant difference between at least a pair of treatments. So in order to find which treatments are significantly different, we perform Fisher’s LSD test.</p>
<p><span class="math display">\[\text{CD} = t_{\frac{\alpha}{2}}\sqrt{\frac{2 \times \text{MSE}}{r}} = 2.131\sqrt{\frac{2(6.350)}{4}} = 2.131 \times 1.7819 = 3.7972\]</span></p>
<p><span class="math inline">\(t_{0.025\text{ at }15 \text{ edf}} = 2.131\)</span> (Just look for the critical value of <em>t</em> for a two tailed test at α = 0.05 in the statistical table, see <span class="quarto-unresolved-ref">?tbl-ttable</span> in Appendix 4.</p>
<p>It is shown as <span class="math inline">\(t_{\frac{\alpha}{2}}\)</span>, since it is a two tailed test in the one side of the t-distribution curve the probability will be <span class="math inline">\(\frac{\alpha}{2}\)</span>, so that combined probability is α.)</p>
<p>Treatment means arranged in descending order. Those treatment pairs whose difference in means is greater than C.D. is labelled with a different letters.</p>
<div id="tbl-crdgroupletters" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crdgroupletters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.5: Grouping of treatment means using letters
</figcaption>
<div aria-describedby="tbl-crdgroupletters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Treatments</th>
<th style="text-align: center;">means</th>
<th style="text-align: center;">Grouping using alphabets</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_{2}\)</span></td>
<td style="text-align: center;">25.5</td>
<td style="text-align: center;">a</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(V_{1}\)</span></td>
<td style="text-align: center;">21.25</td>
<td style="text-align: center;">b</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_{3}\)</span></td>
<td style="text-align: center;">21.25</td>
<td style="text-align: center;">b</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(V_{4}\)</span></td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">b</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_{5}\)</span></td>
<td style="text-align: center;">13.25</td>
<td style="text-align: center;">c</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In the above table we can see that the difference between the means of <span class="math inline">\(V_{2}\)</span> and <span class="math inline">\(V_{1}\)</span> is 4.25, which is greater than the C.D. value. So <span class="math inline">\(V_{2}\)</span> and <span class="math inline">\(V_{1}\)</span> are significantly different, and different letters are assigned to each of them. Instead of letters one can also use symbols as shown below. Those treatments with the same letters/symbols are not significantly different.</p>
<div id="tbl-crdgroupsymbols" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crdgroupsymbols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.6: Grouping of treatment means using symbols
</figcaption>
<div aria-describedby="tbl-crdgroupsymbols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Treatments</th>
<th style="text-align: center;">means</th>
<th style="text-align: center;">Grouping using symbols</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_{2}\)</span></td>
<td style="text-align: center;">25.5</td>
<td style="text-align: center;">@</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(V_{1}\)</span></td>
<td style="text-align: center;">21.25</td>
<td style="text-align: center;">*</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_{3}\)</span></td>
<td style="text-align: center;">21.25</td>
<td style="text-align: center;">*</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(V_{4}\)</span></td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">*</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_{5}\)</span></td>
<td style="text-align: center;">13.25</td>
<td style="text-align: center;">&amp;</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>So, in our example we can conclude that <span class="math inline">\(V_{2}\)</span> is the best variety because it is having the highest mean and is significantly different from others.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In some cases, more than one alphabet can appear against a treatment mean, see the hypothetical example below.</p>
</div>
</div>
<div id="tbl-groupingcrd" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-groupingcrd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.7: A hypothetical example of treatment grouping
</figcaption>
<div aria-describedby="tbl-groupingcrd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Treatments</th>
<th style="text-align: center;">Grouping</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_2\)</span></td>
<td style="text-align: center;">a</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(V_1\)</span></td>
<td style="text-align: center;">ab</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_3\)</span></td>
<td style="text-align: center;">bc</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(V_4\)</span></td>
<td style="text-align: center;">c</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(V_5\)</span></td>
<td style="text-align: center;">d</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Here <span class="math inline">\(V_1\)</span> carries two letters (ab), meaning it is not significantly different from <span class="math inline">\(V_2\)</span> (they share <strong>a</strong>) and also not significantly different from <span class="math inline">\(V_3\)</span> (they share <strong>b</strong>), while <span class="math inline">\(V_2\)</span> and <span class="math inline">\(V_3\)</span> do not share a letter and so are significantly different from each other.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>When a lettering like this appears, treatments having common alphabets are not significantly different. In the above table <span class="math inline">\(V_{2}\)</span> and <span class="math inline">\(V_{1}\)</span> are not significantly different, as both of them have the common letter <em>a</em>. At the same time you can see <span class="math inline">\(V_{5}\)</span> and <span class="math inline">\(V_{4}\)</span> are significantly different, as they don’t have any common letters.</p>
</div>
</div>
</div>
</section>
<section id="advantages-of-a-crd" class="level3" data-number="20.1.6">
<h3 data-number="20.1.6" class="anchored" data-anchor-id="advantages-of-a-crd"><span class="header-section-number">20.1.6</span> Advantages of a CRD</h3>
<ol type="1">
<li><p>Its layout is very easy.</p></li>
<li><p>There is complete flexibility in this design <em>i</em>.<em>e</em>. any number of treatments and replications for each treatment can be tried.</p></li>
<li><p>Whole experimental material can be utilized in this design.</p></li>
<li><p>This design yields maximum degrees of freedom for experimental error.</p></li>
<li><p>The analysis of data is simplest as compared to any other design.</p></li>
<li><p>Even if some values are missing the analysis can be done.</p></li>
</ol>
</section>
<section id="disadvantages-of-a-crd" class="level3" data-number="20.1.7">
<h3 data-number="20.1.7" class="anchored" data-anchor-id="disadvantages-of-a-crd"><span class="header-section-number">20.1.7</span> Disadvantages of a CRD</h3>
<ol type="1">
<li><p>Not suitable for field experiments.</p></li>
<li><p>Relatively low accuracy due to lack of local control. Completely homogeneous experimental units are practically difficult in many situations.</p></li>
</ol>
</section>
</section>
<section id="randomized-complete-block-designs-rcbd" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="randomized-complete-block-designs-rcbd"><span class="header-section-number">20.2</span> Randomized Complete Block Designs (RCBD)</h2>
<p>In field experiments, the plots on which treatments are applied may not be uniform and there may be difference in plot-to-plot fertility. In such cases CRD cannot be recommended. If there is only one source constituting the difference between the plots then we can recommend randomized block design.</p>
<p>The randomized complete block design (RCBD) is one of the most widely used experimental designs in agricultural research. The design is especially suited for field experiments where the number of treatments is not large and the experimental area has a predictable fertility gradient. It is also termed as RBD (Randomized Block Design) in some textbooks.</p>
<p>When the experimental material is heterogeneous, the experimental material is grouped into homogeneous sub-groups called <strong>blocks</strong>. As each block consists of the entire set of treatments a block is equivalent to a replication. For example, in a field with known fertility gradient in one direction, plots perpendicular to this gradient will be considered as a block. In RCBD blocks are of equal size and contains all the treatments. Since the block contains all the treatments, the term ‘complete block design’ is used. See <a href="#fig-rcbd1" class="quarto-xref">Figure&nbsp;<span>20.4</span></a> to see how blocks are formed in a field.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In RCBD, number of replications, <span class="math inline">\(r\)</span> = number of blocks. Number of plots within a block = number of treatments, <span class="math inline">\(v\)</span>.</p>
</div>
</div>
<section id="blocking-technique" class="level3" data-number="20.2.1">
<h3 data-number="20.2.1" class="anchored" data-anchor-id="blocking-technique"><span class="header-section-number">20.2.1</span> Blocking technique</h3>
<p>Blocking or local control, one of the basic principles of design is effectively implemented in RCBD. The primary purpose of blocking is to reduce experimental error by eliminating the contribution of known sources of variation among experimental units. This is achieved by grouping homogeneous units together, so that variability with in blocks is minimized, between blocks is maximized.</p>
<p>Two important factors to be considered for blocking</p>
<ul>
<li><p>The selection of the source of variability to be used as the basis for blocking, in field experiments usually fertility gradient or productivity gradient is used as the identified source of variability.</p></li>
<li><p>Proper selection of the block shape and orientation. For example, when the gradient is unidirectional, use long and narrow blocks. Use square blocks for strong fertility gradient in both directions. An experimenter should use his common sense to identify the shape and orientation of the block after examining the field conditions, such that plots in a block are homogeneous.</p></li>
</ul>
</section>
<section id="sec-rcbdrandom" class="level3" data-number="20.2.2">
<h3 data-number="20.2.2" class="anchored" data-anchor-id="sec-rcbdrandom"><span class="header-section-number">20.2.2</span> Randomization in RCBD</h3>
<p>Consider an experiment involving four treatments A, B, C, D in RCBD. Each treatment is replicated 5 times. Randomization procedure is as explained below. The randomization process for a RCB design is applied separately and independently to each of the blocks.</p>
<p>STEP 1. Divide the experimental area into <span class="math inline">\(r\)</span> equal blocks, where <span class="math inline">\(r\)</span> is the number of replications. In our example <span class="math inline">\(r =\)</span> 5.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-rcbd1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rcbd1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/rcbd1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rcbd1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.4: Division of an experimental field into five blocks, each consisting of four plots, for a RCBD with four treatments and five replications. Blocking is done such that blocks are rectangular and perpendicular to the direction of the unidirectional fertility gradient
</figcaption>
</figure>
</div>
</div>
</div>
<p>STEP 2. Subdivide each block into <span class="math inline">\(v\)</span> experimental plots, where <span class="math inline">\(v\)</span> is the number of treatments. Number the <span class="math inline">\(v\)</span> plots consecutively from 1 to <span class="math inline">\(v\)</span>, and assign <span class="math inline">\(v\)</span> treatments at random to the <span class="math inline">\(v\)</span> plots following the randomization scheme for the CRD described in Section <a href="#sec-random" class="quarto-xref"><span>Section 20.1.1.1</span></a>. In our example each of the 5 blocks are divided into 4 plots. Plots are numbered 1 to 4 in each block. Now for each block, paper lots of 1 to 4 is prepared. Treatment names are written in order and plot number from each lot is recorded in order as shown below.</p>
<div id="tbl-crdlotdraw" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crdlotdraw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.8: Plot numbers drawn for each treatment in a single block
</figcaption>
<div aria-describedby="tbl-crdlotdraw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Treatments</th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Plot number from lot</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>STEP 3. All the treatments are allotted to the randomly selected plots. Step 2 is repeated in all blocks.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-rcbd2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rcbd2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/rcbd2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rcbd2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.5: Allotment of treatments in all blocks. In RCBD each block will have all the treatments and each treatment appear in a block exactly once.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="layout-of-rcbd" class="level3" data-number="20.2.3">
<h3 data-number="20.2.3" class="anchored" data-anchor-id="layout-of-rcbd"><span class="header-section-number">20.2.3</span> Layout of RCBD</h3>
<p>In RCBD each block will have all the treatments and each treatment appear in a block exactly once. After allotting the treatment according to the randomization procedure explained in section <a href="#sec-rcbdrandom" class="quarto-xref"><span>Section 20.2.2</span></a>. The final layout will look like in the figure <a href="#fig-rcbd3" class="quarto-xref">Figure&nbsp;<span>20.6</span></a>.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In RCBD every treatment will have the same number of replications (all treatments are equally replicated, say, <span class="math inline">\(r\)</span> times). So we need a total of <span class="math inline">\(v \times r\)</span> plots for conducting that experiment. Each of <span class="math inline">\(r\)</span> blocks will contain <span class="math inline">\(v\)</span> plots. So in this design, the number of blocks = number of replications of the treatments = <span class="math inline">\(r\)</span>, and number of plots within a block = number of treatments = <span class="math inline">\(v\)</span>.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-rcbd3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rcbd3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/rcbd3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rcbd3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.6: Layout of RCBD with four treatments and five replications
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="statistical-model-for-rcbd" class="level3" data-number="20.2.4">
<h3 data-number="20.2.4" class="anchored" data-anchor-id="statistical-model-for-rcbd"><span class="header-section-number">20.2.4</span> Statistical Model for RCBD</h3>
<p>Consider a RCBD with&nbsp;<span class="math inline">\(v\)</span> treatments with&nbsp;<span class="math inline">\(r\)</span>&nbsp;replications (Blocks). Statistical model for RCBD is same as that of two-way ANOVA&nbsp;described in section <a href="anova.html#sec-twowaymodel" class="quarto-xref"><span>Section 18.6.2.1</span></a>.</p>
<p><span class="math display">\[Y_{\text{ij}} = \mu + \tau_{i} +  \gamma_{j}+ e_{\text{ij}}\]</span><br>
where, <em>i</em> = 1,2, …, <em>v</em> and <em>j</em> =1,2, …, <em>r</em>. <span class="math inline">\(Y_{\text{ij}}\)</span> is the observed value of response under <span class="math inline">\(i^{\text{th}}\)</span> treatment and <span class="math inline">\(j^{\text{th}}\)</span> block, <span class="math inline">\(\tau_{i}\)</span> is the effect of <span class="math inline">\(i^{\text{th}}\)</span> factor,<span class="math inline">\(\gamma_{j}\)</span> is the effect of <span class="math inline">\(j^{\text{th}}\)</span> block . <span class="math inline">\(\mu\)</span> is the general effect which is common for all treatments. <span class="math inline">\(e_{\text{ij}}\)</span> is the error effects.<span class="math inline">\(e_{ij}\)</span> <span class="math inline">\(\sim iid\ N(0,\sigma^{2})\)</span></p>
</section>
<section id="analysis-of-rcbd" class="level3" data-number="20.2.5">
<h3 data-number="20.2.5" class="anchored" data-anchor-id="analysis-of-rcbd"><span class="header-section-number">20.2.5</span> Analysis of RCBD</h3>
<p>Analysis of RCBD is same as that explained in section <a href="anova.html#sec-twowaycalc" class="quarto-xref"><span>Section 18.6.2.3</span></a> of two-way ANOVA.</p>
<p>Observation from <span class="math inline">\(v\)</span> treatments in <span class="math inline">\(r\)</span> blocks is arranged as shown below.</p>
<div id="tbl-rcbd4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rcbd4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.9: Two-way arrangement of observations in RCBD
</figcaption>
<div aria-describedby="tbl-rcbd4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;">Block 1</th>
<th style="text-align: center;">Block 2</th>
<th style="text-align: center;">Block 3</th>
<th style="text-align: center;"><span class="math inline">\(\cdots\)</span></th>
<th style="text-align: center;">Block <span class="math inline">\(r\)</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(Y_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{13}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{1r}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(T_1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(Y_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{22}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{23}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{2r}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(T_2\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;"><span class="math inline">\(Y_{31}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{32}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{33}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{3r}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(T_3\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(v\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{v1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{v2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{v3}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(Y_{vr}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(T_v\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><span class="math inline">\(B_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(B_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(B_3\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\cdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(B_r\)</span></td>
<td style="text-align: center;"><span class="math inline">\(G\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The ANOVA table, following the calculations as in section <a href="anova.html#sec-twowaycalc" class="quarto-xref"><span>Section 18.6.2.3</span></a>, is</p>
<div id="tbl-rcbd5" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="ANOVA table of RCBD" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rcbd5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.10: ANOVA table of RCBD
</figcaption>
<div aria-describedby="tbl-rcbd5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Source
</th>
<th style="text-align:center;font-weight: bold;">
d.f
</th>
<th style="text-align:center;font-weight: bold;">
S.S
</th>
<th style="text-align:center;font-weight: bold;">
M.S.S
</th>
<th style="text-align:center;font-weight: bold;">
F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Treatments
</td>
<td style="text-align:center;">
<span class="math inline">\(v-1\)</span>
</td>
<td style="text-align:center;width: 5cm; ">
<span class="math inline">\(\text{SST} = \dfrac{\sum_{i=1}^{v} T_i^2}{r} - \text{C.F.}\)</span>
</td>
<td style="text-align:center;width: 3.2cm; ">
<span class="math inline">\(\dfrac{\text{SST}}{v-1} = \text{MST}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(F_1 = \dfrac{\text{MST}}{\text{MSE}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Blocks
</td>
<td style="text-align:center;">
<span class="math inline">\(r-1\)</span>
</td>
<td style="text-align:center;width: 5cm; ">
<span class="math inline">\(\text{SSB} = \dfrac{\sum_{j=1}^{r} B_j^2}{v} - \text{C.F.}\)</span>
</td>
<td style="text-align:center;width: 3.2cm; ">
<span class="math inline">\(\dfrac{\text{SSB}}{r-1} = \text{MSR}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(F_2 = \dfrac{\text{MSR}}{\text{MSE}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Error
</td>
<td style="text-align:center;">
<span class="math inline">\((v-1)(r-1)\)</span>
</td>
<td style="text-align:center;width: 5cm; ">
<span class="math inline">\(\text{ESS} = \text{Total SS} - \text{SST} - \text{SSB}\)</span>
</td>
<td style="text-align:center;width: 3.2cm; ">
<span class="math inline">\(\dfrac{\text{ESS}}{(v-1)(r-1)} = \text{MSE}\)</span>
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;">
Total
</td>
<td style="text-align:center;">
<span class="math inline">\(vr-1\)</span>
</td>
<td style="text-align:center;width: 5cm; ">
<span class="math inline">\(\sum_{i=1}^{v}\sum_{j=1}^{r} Y_{ij}^2 - \text{C.F.}\)</span>
</td>
<td style="text-align:center;width: 3.2cm; ">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>where <span class="math inline">\(\text{C.F} = \dfrac{G^2}{rv}\)</span>.</p>
<p><span class="math inline">\(F_{1} \sim F_{(v-1),\ (v-1)(r-1)}\)</span> and <span class="math inline">\(F_{2} \sim F_{(r-1),\ (v-1)(r-1)}\)</span> are two F values, one for treatment and one for blocks respectively. Decisions on the null hypothesis are made by comparing the corresponding F value to the table value given in <span class="quarto-unresolved-ref">?tbl-ftable</span> of Appendix 5.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>What if <span class="math inline">\(F_{2}\)</span> is not significant? If <span class="math inline">\(F_{2}\)</span> is not significant, it indicates that there is no significant difference between blocks, meaning blocking is not effective. Blocking is considered effective in reducing the experimental error only if <span class="math inline">\(F_{2}\)</span> is significant.</p>
</div>
</div>
</section>
<section id="post-hoc-test-in-rcbd" class="level3" data-number="20.2.6">
<h3 data-number="20.2.6" class="anchored" data-anchor-id="post-hoc-test-in-rcbd"><span class="header-section-number">20.2.6</span> Post-hoc test in RCBD</h3>
<p>If the null hypothesis for treatments is rejected in ANOVA; we proceed to post-hoc test explained in section <a href="multipleComparison.html#sec-lsd" class="quarto-xref"><span>Section 19.2</span></a>. Arrange the treatment means in descending order. Critical difference (CD) or LSD (Least Significant Difference) is calculated for each treatment pair <span class="math inline">\(T_{i},\ T_{j}\)</span> using the following formula.</p>
<p><span class="math display">\[CD = \ t_{\frac{\alpha}{2},edf}.\sqrt{\frac{2\ MSE}{r}}\]</span> where, <span class="math inline">\(\text{MSE}\)</span> is the Mean Square Error from ANOVA. <span class="math inline">\(t_{\frac{\alpha}{2},edf}\)</span> is the critical value of two tailed student’s t distribution at <span class="math inline">\(\alpha\)</span> level of significance and error degrees of freedom. <span class="math inline">\(r\)</span> is the number of blocks/replication.<br>
Procedure for grouping using symbols is same as that of CRD explained in section <a href="#sec-postcrd" class="quarto-xref"><span>Section 20.1.4.1</span></a>.</p>
</section>
<section id="replications-in-rcbd" class="level3" data-number="20.2.7">
<h3 data-number="20.2.7" class="anchored" data-anchor-id="replications-in-rcbd"><span class="header-section-number">20.2.7</span> Replications in RCBD</h3>
<p>As explained in section <a href="#sec-replical" class="quarto-xref"><span>Section 20.1.5</span></a> number of replications in RCBD is found out using the equation of error degrees of freedom (<em>edf</em>). It is assumed that <em>edf</em> <span class="math inline">\(\geq 12\)</span>. For RCBD</p>
<p><span id="eq-rcbdrep"><span class="math display">\[(v - 1) (r-1) \geq 12 \tag{20.2}\]</span></span></p>
<p>where <span class="math inline">\(v\)</span> is the number of treatments and <span class="math inline">\(r\)</span> is the replication.</p>
<div id="exm-ct44" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.3</strong></span> You have 4 treatments; you are planning to conduct the experiment in RCBD. Find the minimum number of replications required.</p>
<p><strong>Solution</strong></p>
<p>from <a href="#eq-rcbdrep" class="quarto-xref">Equation&nbsp;<span>20.2</span></a></p>
<p>Since <span class="math inline">\(v\)</span> = 4, <em>edf</em> <span class="math inline">\(= 3\left( r - 1 \right) \geq 12\)</span></p>
<p><span class="math inline">\(\implies r \geq 5\)</span>, minimum replication required is 5</p>
<p>The number of replications required is 5.</p>
</div>
<div id="exm-ct46" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.4</strong></span> The yield of paddy (kg per plot) under four fertilizer treatments A, B, C, and D was studied using an RCBD with 5 blocks. The results are given below.</p>
<div id="tbl-rcbdex" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Yield data (kg per plot) of four fertilizer treatments under RCBD" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rcbdex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.11: Yield data (kg per plot) of four fertilizer treatments under RCBD
</figcaption>
<div aria-describedby="tbl-rcbdex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Block
</th>
<th style="text-align:center;font-weight: bold;">
A
</th>
<th style="text-align:center;font-weight: bold;">
B
</th>
<th style="text-align:center;font-weight: bold;">
C
</th>
<th style="text-align:center;font-weight: bold;">
D
</th>
<th style="text-align:center;font-weight: bold;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;font-weight: bold;">
Block 1
</td>
<td style="text-align:center;">
41
</td>
<td style="text-align:center;">
44
</td>
<td style="text-align:center;">
52
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
180
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Block 2
</td>
<td style="text-align:center;">
42
</td>
<td style="text-align:center;">
51
</td>
<td style="text-align:center;">
51
</td>
<td style="text-align:center;">
48
</td>
<td style="text-align:center;">
192
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Block 3
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
49
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
172
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Block 4
</td>
<td style="text-align:center;">
42
</td>
<td style="text-align:center;">
51
</td>
<td style="text-align:center;">
53
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
196
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Block 5
</td>
<td style="text-align:center;">
41
</td>
<td style="text-align:center;">
47
</td>
<td style="text-align:center;">
51
</td>
<td style="text-align:center;">
45
</td>
<td style="text-align:center;">
184
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;font-weight: bold;">
<strong>Total</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>206</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>236</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>256</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>226</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>924</strong>
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Solution</strong></p>
<p><strong>Grand Total (G)</strong> = 924</p>
<p><strong>Correction Factor</strong> <span class="math inline">\(= \dfrac{G^{2}}{n} = \dfrac{(924)^{2}}{20}\)</span> = 42688.80</p>
<p><strong>Total Sum of Squares (TSS)</strong> <span class="math inline">\(= (41^2+44^2+52^2+...+45^2) - CF\)</span> <span class="math inline">\(= 43080 - 42688.80 = 391.20\)</span></p>
<p><strong>Treatment Sum of Squares (SST)</strong> <span class="math inline">\(= \dfrac{1}{5}(206^{2} + 236^{2} + 256^{2} + 226^{2}) - CF\)</span> <span class="math inline">\(= 42948.80 - 42688.80 = 260.00\)</span></p>
<p><strong>Block Sum of Squares (SSB)</strong> <span class="math inline">\(= \dfrac{1}{4}(180^{2} + 192^{2} + 172^{2} + 196^{2} + 184^{2}) - CF\)</span> <span class="math inline">\(= 42780.00 - 42688.80 = 91.20\)</span></p>
<p><strong>Error Sum of Squares</strong> <span class="math inline">\(= 391.20 - 260.00 - 91.20 = 40.00\)</span></p>
<div id="tbl-rcbdanovaex" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="ANOVA table for the fertilizer trial" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rcbdanovaex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.12: ANOVA table for the fertilizer trial
</figcaption>
<div aria-describedby="tbl-rcbdanovaex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Source of variation
</th>
<th style="text-align:center;font-weight: bold;">
df
</th>
<th style="text-align:center;font-weight: bold;">
Sum of squares
</th>
<th style="text-align:center;font-weight: bold;">
Mean Sum of squares
</th>
<th style="text-align:center;font-weight: bold;">
F Cal
</th>
<th style="text-align:center;font-weight: bold;">
F tab
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;font-weight: bold;">
Treatments
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
260.00
</td>
<td style="text-align:center;">
86.67
</td>
<td style="text-align:center;">
26.00
</td>
<td style="text-align:center;">
3.49
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Blocks
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
91.20
</td>
<td style="text-align:center;">
22.80
</td>
<td style="text-align:center;">
6.84
</td>
<td style="text-align:center;">
3.26
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Error
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
40.00
</td>
<td style="text-align:center;">
3.33
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Total
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
391.20
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Since <span class="math inline">\(F_1\)</span> (treatments) and <span class="math inline">\(F_2\)</span> (blocks) both exceed their table values, treatments differ significantly, and blocking has been effective in reducing the experimental error.</p>
<p><span class="math display">\[CD = t_{\frac{\alpha}{2},edf}\sqrt{\frac{2\,MSE}{r}} = 2.179\sqrt{\frac{2 \times 3.33}{5}} = 2.516\]</span></p>
<p>Treatment means, in descending order, are C = 51.2, B = 47.2, D = 45.2, A = 41.2.</p>
<div id="tbl-rcbdgrouping" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rcbdgrouping-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.13: Grouping of treatment means for the fertilizer trial
</figcaption>
<div aria-describedby="tbl-rcbdgrouping-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Treatments</th>
<th style="text-align: center;">Means</th>
<th style="text-align: center;">Grouping</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">51.2</td>
<td style="text-align: center;">a</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">47.2</td>
<td style="text-align: center;">b</td>
</tr>
<tr class="odd">
<td style="text-align: center;">D</td>
<td style="text-align: center;">45.2</td>
<td style="text-align: center;">b</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">41.2</td>
<td style="text-align: center;">c</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Since <span class="math inline">\(C-B = 4.0\)</span> and <span class="math inline">\(D-A = 4.0\)</span>, both exceed the CD of 2.516, so C is significantly superior to all other treatments, and A gives the significantly lowest yield. B and D do not differ significantly from each other (<span class="math inline">\(B-D = 2.0 &lt; CD\)</span>), so treatment C is recommended as the best-performing fertilizer.</p>
</div>
</section>
<section id="advantages-of-rcbd" class="level3" data-number="20.2.8">
<h3 data-number="20.2.8" class="anchored" data-anchor-id="advantages-of-rcbd"><span class="header-section-number">20.2.8</span> Advantages of RCBD</h3>
<ol type="1">
<li><p>Accuracy: RCB design has been shown to be more efficient or accurate than C.R.D. for most types of experimental work.</p></li>
<li><p>Flexibility: In RCBD no restrictions are placed on the number of treatments or the number of replicates.</p></li>
<li><p>Even if some values are missing, still the analysis can be done by using missing plot technique.</p></li>
<li><p>Ease of analysis: Statistical analysis is simple, rapid and straight forward.</p></li>
</ol>
</section>
<section id="disadvantages-of-rcbd" class="level3" data-number="20.2.9">
<h3 data-number="20.2.9" class="anchored" data-anchor-id="disadvantages-of-rcbd"><span class="header-section-number">20.2.9</span> Disadvantages of RCBD</h3>
<ol type="1">
<li><p>RCBD may give misleading results if blocks are not homogeneous.</p></li>
<li><p>RCBD is not suitable for large number of treatments because in that case the block size will increase and it may not be possible to keep large blocks homogeneous.</p></li>
<li><p>If the data on more than two plots is missing the statistical analysis becomes tedious and complicated.</p></li>
</ol>
</section>
</section>
<section id="latin-square-design-lsd" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="latin-square-design-lsd"><span class="header-section-number">20.3</span> Latin Square Design (LSD)</h2>
<p>In this design, variations in the field in two different directions (or variations due to two different factors) are controlled simultaneously from affecting the treatment comparisons. A layout in RBD controls only one source of external variation affecting the treatment comparisons by the construction of homogeneous blocks. Sometimes when blocks were laid out in a field the environmental conditions within each block need not be the same. For example, soil variability in a North South direction and an environmental gradient in an East West Direction then the conditions within each block will vary. In such situations the variability can be controlled by a Latin Square design (LSD). The blocks in a LSD are called rows and columns; they represent two external factors. The entire experimental area can be divided into small plots arranged in the form of a square. The number of plots in each row and each column are equal, both equal to the number of treatments to be compared.</p>
<section id="sec-lsdrandom" class="level3" data-number="20.3.1">
<h3 data-number="20.3.1" class="anchored" data-anchor-id="sec-lsdrandom"><span class="header-section-number">20.3.1</span> Randomization</h3>
<p>A Latin square of <span class="math inline">\(v\)</span> treatments (usually called side <span class="math inline">\(v\)</span>) is an arrangement of <span class="math inline">\(v\)</span> treatments into <span class="math inline">\(v\)</span> rows and <span class="math inline">\(v\)</span> columns such that every treatment is replicated in each row and each column exactly once.</p>
<p>Latin squares of different orders are provided in standard statistical tables for use in experimental design. When <span class="math inline">\(v\)</span> treatments are to be compared, a Latin square of order <span class="math inline">\(v\)</span>, that is, a <span class="math inline">\(v\times v\)</span> square, is required. The order of the square is therefore determined directly by the number of treatments in the experiment. For example, an experiment involving four treatments requires a <span class="math inline">\(4\times4\)</span> Latin square, whereas an experiment involving five treatments requires a <span class="math inline">\(5\times5\)</span> Latin square.</p>
<p>Standard Latin squares suitable for experimental use are given in the tables of <span class="citation" data-cites="fisher1935statistical">(<a href="references.html#ref-fisher1935statistical" role="doc-biblioref">Fisher and Yates 1935</a>)</span>. In these tables, the Latin squares are presented in a standard form, with the treatment symbols arranged in a specified order, usually alphabetically, in the first row. Several standard squares may be available for a particular order, as illustrated in <a href="#fig-strdlattice" class="quarto-xref">Figure&nbsp;<span>20.7</span></a>. These standard arrangements serve only as the starting point for constructing the experimental layout; they should not be used directly without randomization.</p>
<p>For a given number of treatments (<span class="math inline">\(v\)</span>), select an appropriate standard Latin square of order (<span class="math inline">\(v\)</span>) from the statistical tables. The selected square is then randomized so that the treatment allocation is not influenced by the initial systematic arrangement of the standard square. Randomization is carried out by independently permuting the rows, columns, and treatment symbols according to the prescribed procedure. The resulting randomized Latin square provides the treatment allocation to the experimental units, with each treatment occurring exactly once in every row and once in every column. The randomization procedure is described in the following steps.</p>
<div id="fig-strdlattice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-strdlattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/stdlatin.svg" width="500" height="600" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-strdlattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.7: Standard Latin squares of orders 4 and 5 from the Fisher and Yates (1935) statistical tables.
</figcaption>
</figure>
</div>
<p>Let <span class="math inline">\(v = 6\)</span>. A Latin square for 6 treatments, denoted by <em>A</em>, <em>B</em>, <em>C</em>, <em>D</em>, <em>E</em> and <em>F</em>, can be constructed by placing the symbols in alphabetical order in the first row and generating each subsequent row by a symmetric cyclic shift of the one above it.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lsdlayout" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lsdlayout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/lsdlayout.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lsdlayout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.8: Standard (unrandomized) Latin square with six treatments
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-lsdlayout" class="quarto-xref">Figure&nbsp;<span>20.8</span></a> shows this standard, systematically-arranged Latin square for <span class="math inline">\(v = 6\)</span> treatments before randomization. The blocking is applied in two directions, as rows and as columns, and the number of rows and columns each equals the number of treatments, <span class="math inline">\(v\)</span>. A standard Latin square of 6 treatments can also be directly obtained from the tables.</p>
<p>Randomization of a Latin square design involves three steps:</p>
<ol type="1">
<li>Row randomization<br>
</li>
<li>Column randomization<br>
</li>
<li>Treatment randomization</li>
</ol>
<p>For <span class="math inline">\(v\)</span> treatments, select a Latin square of order <span class="math inline">\(v\)</span> at random from the statistical tables, and then randomize it through the following steps.</p>
<p><em>Row randomization</em>: Number the rows of the selected square from 1 to <span class="math inline">\(v\)</span>. Keeping the first row fixed, rearrange the remaining rows in a random order using random numbers. This produces a new square, as shown in <a href="#fig-lsdlayout1" class="quarto-xref">Figure&nbsp;<span>20.9</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lsdlayout1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lsdlayout1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/lsdlayout1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lsdlayout1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.9: Randomization of the rows of the Latin square
</figcaption>
</figure>
</div>
</div>
</div>
<p><em>Column randomization</em>: Once the rows have been randomized, rearrange the columns in a random order in the same manner to obtain a further randomized square, as shown in <a href="#fig-lsdlayout2" class="quarto-xref">Figure&nbsp;<span>20.10</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lsdlayout2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lsdlayout2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/singlefactor/lsd_layout2.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lsdlayout2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.10: Randomization of the columns of the Latin square
</figcaption>
</figure>
</div>
</div>
</div>
<p><em>Treatment randomization</em>: Finally, assign the <span class="math inline">\(v\)</span> treatments at random to the <span class="math inline">\(v\)</span> letters (<em>A</em>, <em>B</em>, …, <em>F</em>). The resulting square gives the field layout of the design.</p>
</section>
<section id="layout" class="level3" data-number="20.3.2">
<h3 data-number="20.3.2" class="anchored" data-anchor-id="layout"><span class="header-section-number">20.3.2</span> Layout</h3>
<p>The fully randomized square obtained at the end of the randomization procedure, shown in <a href="#fig-lsdlayout2" class="quarto-xref">Figure&nbsp;<span>20.10</span></a>, gives the field layout of the design. Each row and each column of the square corresponds to a physical row and column of plots in the field, and each cell gives the treatment to be applied to that plot. Since every treatment appears exactly once in each row and exactly once in each column, variation in both the row and column directions is controlled simultaneously.</p>
</section>
<section id="statistical-model-for-lsd" class="level3" data-number="20.3.3">
<h3 data-number="20.3.3" class="anchored" data-anchor-id="statistical-model-for-lsd"><span class="header-section-number">20.3.3</span> Statistical model for LSD</h3>
<p>The data collected from experiments in LSD are classified according to the levels of three factors. So it is called a three-way classified design. The two types of blocking (rows and columns) and treatments make up the three factors. The linear model for analysis is:</p>
<p><span id="eq-lsdmodel"><span class="math display">\[Y_{\text{ijk}} = \mu + \tau_{i} + R_{j}+ C_{k}+e_{\text{ijk}} \tag{20.3}\]</span></span></p>
<p>where <span class="math inline">\(i,j,k = 1,2,3,...\ v\)</span></p>
<p><em>i.e.,</em> the response (yield <span class="math inline">\(Y_{ijk}\)</span>) of each plot = a general mean effect (<span class="math inline">\(\mu\)</span>) + effect due to the <span class="math inline">\(i^{th}\)</span> treatment (<span class="math inline">\(\tau_{i}\)</span>) + effect of the <span class="math inline">\(j^{th}\)</span> row (<span class="math inline">\(R_{j}\)</span>) + effect due to the <span class="math inline">\(k^{th}\)</span> column (<span class="math inline">\(C_{k}\)</span>) + random error term associated with each plot (<span class="math inline">\(e_{ijk}\)</span>).</p>
</section>
<section id="analysis" class="level3" data-number="20.3.4">
<h3 data-number="20.3.4" class="anchored" data-anchor-id="analysis"><span class="header-section-number">20.3.4</span> Analysis</h3>
<p>The effect of the general mean is subtracted from each sum of squares (by subtracting the correction factor <span class="math inline">\(C.F. = \dfrac{(\sum{y_{ijk}})^2} {v^2}\)</span>). The total sum of squares is split into four components: (i) variation between the treatments as treatment sum of squares, (ii) variation between the rows, (iii) variation between the columns, and (iv) variation within the factors, <em>i.e.,</em> error sum of squares.</p>
<p>To calculate the sum of squares, arrange the data according to the rows, columns and treatments and obtain the respective totals. Let the treatment totals be <span class="math inline">\(T_{1}\)</span>, <span class="math inline">\(T_{2}\)</span>, …., <span class="math inline">\(T_{v}\)</span>; row totals be <span class="math inline">\(R_{1}\)</span>, <span class="math inline">\(R_{2}\)</span>, <span class="math inline">\(R_{3}\)</span>, …, <span class="math inline">\(R_{v}\)</span> and column totals be <span class="math inline">\(C_{1}\)</span>, <span class="math inline">\(C_{2}\)</span>, <span class="math inline">\(C_{3}\)</span>, …, <span class="math inline">\(C_{v}\)</span>.</p>
<div id="tbl-lsdanova" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="ANOVA of Latin Square Design" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lsdanova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.14: ANOVA of Latin Square Design
</figcaption>
<div aria-describedby="tbl-lsdanova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Source of Variation
</th>
<th style="text-align:center;font-weight: bold;">
d.f
</th>
<th style="text-align:center;font-weight: bold;">
Sum of Squares
</th>
<th style="text-align:center;font-weight: bold;">
M.S.S
</th>
<th style="text-align:center;font-weight: bold;">
F value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;width: 3.2cm; ">
Between treatments
</td>
<td style="text-align:center;">
<span class="math inline">\(v-1\)</span>
</td>
<td style="text-align:center;width: 3cm; ">
<span class="math inline">\(\dfrac{\sum T_i^2}{v} - CF\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(MST\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\dfrac{\text{MST}}{\text{MSE}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;width: 3.2cm; ">
Between rows
</td>
<td style="text-align:center;">
<span class="math inline">\(v-1\)</span>
</td>
<td style="text-align:center;width: 3cm; ">
<span class="math inline">\(\dfrac{\sum R_j^2}{v} - CF\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(MSR\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\dfrac{\text{MSR}}{\text{MSE}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;width: 3.2cm; ">
Between columns
</td>
<td style="text-align:center;">
<span class="math inline">\(v-1\)</span>
</td>
<td style="text-align:center;width: 3cm; ">
<span class="math inline">\(\dfrac{\sum C_k^2}{v} - CF\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(MSC\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\dfrac{\text{MSC}}{\text{MSE}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;width: 3.2cm; ">
Error
</td>
<td style="text-align:center;">
<span class="math inline">\((v-1)(v-2)\)</span>
</td>
<td style="text-align:center;width: 3cm; ">
By subtraction
</td>
<td style="text-align:center;">
<span class="math inline">\(MSE\)</span>
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;width: 3.2cm; ">
Total
</td>
<td style="text-align:center;">
<span class="math inline">\(v^2-1\)</span>
</td>
<td style="text-align:center;width: 3cm; ">
<span class="math inline">\(\sum Y_{ijk}^2 - CF\)</span>
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>All these computed F values are compared with the F table values for <span class="math inline">\((v-1)\)</span> and <span class="math inline">\((v-1)(v-2)\)</span> degrees of freedom.</p>
</section>
<section id="post-hoc-test-lsd" class="level3" data-number="20.3.5">
<h3 data-number="20.3.5" class="anchored" data-anchor-id="post-hoc-test-lsd"><span class="header-section-number">20.3.5</span> Post hoc test (LSD)</h3>
<p>If the treatments turn out to be significant, then the means are compared pairwise using Fisher’s Least Significant Difference (LSD) test, as explained in section <a href="multipleComparison.html#sec-lsd" class="quarto-xref"><span>Section 19.2</span></a>.</p>
<p><span id="eq-lsdcd"><span class="math display">\[C.D. = t_{\left( \frac{\alpha}{2},\ error\ df \right)}\sqrt{\frac{2\,MSE}{v}} \tag{20.4}\]</span></span></p>
<p>Here <span class="math inline">\(t_{\left( \frac{\alpha}{2},\ error\ df \right)}\)</span> denotes the critical value of Student’s <em>t</em> for a two tailed test at <span class="math inline">\(\alpha\)</span> level of significance and error degrees of freedom. If the difference between any two treatment means is greater than the critical difference, they are significantly different; otherwise they are said to be on par. Procedure for grouping using letters or symbols is the same as that of CRD, explained in section <a href="#sec-postcrd" class="quarto-xref"><span>Section 20.1.4.1</span></a>.</p>
</section>
<section id="replications-in-lsd" class="level3" data-number="20.3.6">
<h3 data-number="20.3.6" class="anchored" data-anchor-id="replications-in-lsd"><span class="header-section-number">20.3.6</span> Replications in LSD</h3>
<p>Unlike CRD and RCBD, the number of replications in LSD is not a free choice, since the design requires the number of rows, columns, and treatments to all equal <span class="math inline">\(v\)</span>; each treatment is automatically replicated <span class="math inline">\(v\)</span> times, once in each row and once in each column. So instead of solving for the number of replications, the minimum number of treatments <span class="math inline">\(v\)</span> required is found using the equation for error degrees of freedom (<em>edf</em>). It is assumed that <em>edf</em> <span class="math inline">\(\geq 12\)</span>. For LSD</p>
<p><span id="eq-lsdrep"><span class="math display">\[(v-1)(v-2) \geq 12 \tag{20.5}\]</span></span></p>
<div id="exm-lsdrep" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.5</strong></span> Find the minimum number of treatments <span class="math inline">\(v\)</span> (and hence replications) required for an experiment conducted in LSD.</p>
<p><strong>Solution</strong></p>
<p>from <a href="#eq-lsdrep" class="quarto-xref">Equation&nbsp;<span>20.5</span></a>, <span class="math inline">\((v-1)(v-2) \geq 12\)</span></p>
<p>Trying <span class="math inline">\(v = 4\)</span>: <span class="math inline">\((3)(2) = 6 &lt; 12\)</span>, not sufficient.</p>
<p>Trying <span class="math inline">\(v = 5\)</span>: <span class="math inline">\((4)(3) = 12 \geq 12\)</span>, sufficient.</p>
<p>The minimum number of treatments (and replications) required is 5.</p>
</div>
<div id="exm-ct45" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.6</strong></span> Consider a 5x5 LSD experimental setup as follows</p>
<div id="tbl-LSDE1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="A 5x5 Latin square experimental layout, showing the treatment (A-E) and the response recorded on each plot" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-LSDE1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.15: A 5x5 Latin square experimental layout, showing the treatment (A-E) and the response recorded on each plot
</figcaption>
<div aria-describedby="tbl-LSDE1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Row
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>1</sub>
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>2</sub>
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>3</sub>
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>4</sub>
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>5</sub>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>1</sub>
</td>
<td style="text-align:center;">
C 28
</td>
<td style="text-align:center;">
B 36
</td>
<td style="text-align:center;">
E 18
</td>
<td style="text-align:center;">
D 42
</td>
<td style="text-align:center;">
A 35
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>2</sub>
</td>
<td style="text-align:center;">
E 27
</td>
<td style="text-align:center;">
D 43
</td>
<td style="text-align:center;">
B 27
</td>
<td style="text-align:center;">
A 34
</td>
<td style="text-align:center;">
C 32
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>3</sub>
</td>
<td style="text-align:center;">
B 40
</td>
<td style="text-align:center;">
A 44
</td>
<td style="text-align:center;">
D 39
</td>
<td style="text-align:center;">
C 36
</td>
<td style="text-align:center;">
E 38
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>4</sub>
</td>
<td style="text-align:center;">
D 41
</td>
<td style="text-align:center;">
C 26
</td>
<td style="text-align:center;">
A 34
</td>
<td style="text-align:center;">
E 19
</td>
<td style="text-align:center;">
B 37
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>5</sub>
</td>
<td style="text-align:center;">
A 41
</td>
<td style="text-align:center;">
E 16
</td>
<td style="text-align:center;">
C 20
</td>
<td style="text-align:center;">
B 31
</td>
<td style="text-align:center;">
D 45
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Solution</strong></p>
<p>The three null hypotheses (one each for treatments, rows, and columns) are</p>
<p><span class="math inline">\(H_{01}\)</span>: <span class="math inline">\(\mu_{11} = \mu_{12} = \mu_{13} = \mu_{14} = \mu_{15}\)</span> (treatment means are equal)</p>
<p><span class="math inline">\(H_{11}\)</span>: at least two of the treatment means are different</p>
<p><span class="math inline">\(H_{02}\)</span>: <span class="math inline">\(\mu_{21} = \mu_{22} = \mu_{23} = \mu_{24} = \mu_{25}\)</span> (row means are equal)</p>
<p><span class="math inline">\(H_{12}\)</span>: at least two of the row means are different</p>
<p><span class="math inline">\(H_{03}\)</span>: <span class="math inline">\(\mu_{31} = \mu_{32} = \mu_{33} = \mu_{34} = \mu_{35}\)</span> (column means are equal)</p>
<p><span class="math inline">\(H_{13}\)</span>: at least two of the column means are different</p>
<div id="tbl-LSDE2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="The 5x5 Latin square layout with row, column, and grand totals and means" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-LSDE2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.16: The 5x5 Latin square layout with row, column, and grand totals and means
</figcaption>
<div aria-describedby="tbl-LSDE2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Row
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>1</sub>
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>2</sub>
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>3</sub>
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>4</sub>
</th>
<th style="text-align:center;font-weight: bold;">
C<sub>5</sub>
</th>
<th style="text-align:center;font-weight: bold;">
Total
</th>
<th style="text-align:center;font-weight: bold;">
Mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>1</sub>
</td>
<td style="text-align:center;">
C 28
</td>
<td style="text-align:center;">
B 36
</td>
<td style="text-align:center;">
E 18
</td>
<td style="text-align:center;">
D 42
</td>
<td style="text-align:center;">
A 35
</td>
<td style="text-align:center;">
159
</td>
<td style="text-align:center;">
31.8
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>2</sub>
</td>
<td style="text-align:center;">
E 27
</td>
<td style="text-align:center;">
D 43
</td>
<td style="text-align:center;">
B 27
</td>
<td style="text-align:center;">
A 34
</td>
<td style="text-align:center;">
C 32
</td>
<td style="text-align:center;">
163
</td>
<td style="text-align:center;">
32.6
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>3</sub>
</td>
<td style="text-align:center;">
B 40
</td>
<td style="text-align:center;">
A 44
</td>
<td style="text-align:center;">
D 39
</td>
<td style="text-align:center;">
C 36
</td>
<td style="text-align:center;">
E 38
</td>
<td style="text-align:center;">
197
</td>
<td style="text-align:center;">
39.4
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>4</sub>
</td>
<td style="text-align:center;">
D 41
</td>
<td style="text-align:center;">
C 26
</td>
<td style="text-align:center;">
A 34
</td>
<td style="text-align:center;">
E 19
</td>
<td style="text-align:center;">
B 37
</td>
<td style="text-align:center;">
157
</td>
<td style="text-align:center;">
31.4
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
R<sub>5</sub>
</td>
<td style="text-align:center;">
A 41
</td>
<td style="text-align:center;">
E 16
</td>
<td style="text-align:center;">
C 20
</td>
<td style="text-align:center;">
B 31
</td>
<td style="text-align:center;">
D 45
</td>
<td style="text-align:center;">
153
</td>
<td style="text-align:center;">
30.6
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;font-weight: bold;">
<strong>Total</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>177</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>165</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>138</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>162</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>187</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>829</strong>
</td>
<td style="text-align:center;font-weight: bold;">
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;font-weight: bold;">
<strong>Mean</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>35.4</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>33</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>27.6</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>32.4</strong>
</td>
<td style="text-align:center;font-weight: bold;">
<strong>37.4</strong>
</td>
<td style="text-align:center;font-weight: bold;">
</td>
<td style="text-align:center;font-weight: bold;">
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Grand Total (G)</strong>= 829</p>
<p><strong>Correction Factor(C.F)</strong> <span class="math inline">\(= \frac{G^{2}}{n} = \frac{\left( 829 \right)^{2}}{25}\)</span>= 27489.64</p>
<p><strong>Total Sum of Squares(TSS)</strong>= <span class="math inline">\((28^2+36^2+18^2+...+31^2)-27489.64\)</span> <span class="math inline">\(=29243-27489.64 = 1753.36\)</span></p>
<p><strong>Row Sum of Squares(RSS)</strong>=<span class="math inline">\(\frac{1}{5}(159^{2} + 163^{2} + 197^{2}+157^{2}+153^{2}) - CF\)</span> <span class="math inline">\(=27743.4-27489.64 = 253.76\)</span></p>
<p><strong>Column Sum of Squares(CSS)</strong>=<span class="math inline">\(\frac{1}{5}(177^{2} + 165^{2} + 138^{2}+162^{2}+187^{2}) - CF\)</span> <span class="math inline">\(= 27762.2-27489.64 = 272.56\)</span></p>
<p><strong>Treatment Sum of Squares(SSt)</strong>=<span class="math inline">\(\frac{1}{5}(188^{2} + 171^{2} + 142^{2}+210^{2}+118^{2}) - CF\)</span> <span class="math inline">\(= 28554.6 - 27489.64 = 1064.96\)</span></p>
<p><strong>Error Sum of Squares</strong> <span class="math inline">\(= 1753.36 - 253.76- 272.56-1064.96 = 162.08\)</span></p>
<div id="tbl-lsdanovaex" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="ANOVA table for the Latin Square example" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lsdanovaex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.17: ANOVA table for the Latin Square example
</figcaption>
<div aria-describedby="tbl-lsdanovaex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;font-weight: bold;">
Source of variation
</th>
<th style="text-align:center;font-weight: bold;">
df
</th>
<th style="text-align:center;font-weight: bold;">
Sum of squares
</th>
<th style="text-align:center;font-weight: bold;">
Mean Sum of squares
</th>
<th style="text-align:center;font-weight: bold;">
F Cal
</th>
<th style="text-align:center;font-weight: bold;">
F tab
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;font-weight: bold;">
Row
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
253.76
</td>
<td style="text-align:center;">
63.44
</td>
<td style="text-align:center;">
4.70
</td>
<td style="text-align:center;">
3.26
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Column
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
272.56
</td>
<td style="text-align:center;">
68.14
</td>
<td style="text-align:center;">
5.04
</td>
<td style="text-align:center;">
3.26
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Treatment
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
1064.96
</td>
<td style="text-align:center;">
266.24
</td>
<td style="text-align:center;">
19.71
</td>
<td style="text-align:center;">
3.26
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Error
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
162.08
</td>
<td style="text-align:center;">
13.51
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
Total
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
1753.36
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Since the F cal is greater than the F table value, all the null hypotheses are rejected.</p>
<p><span class="math display">\[C.D. = t_{\left( \frac{\alpha}{2},\ error\ df \right)}\sqrt{\frac{2\,MSE}{v}} = 2.18\sqrt{\frac{2 \times 13.51}{5}} = 5.07\]</span></p>
<p>Mean of treatment D is maximum which is statistically at par with A. Mean of E is minimum and statistically at par with C.</p>
</div>
</section>
<section id="advantages-of-lsd" class="level3" data-number="20.3.7">
<h3 data-number="20.3.7" class="anchored" data-anchor-id="advantages-of-lsd"><span class="header-section-number">20.3.7</span> Advantages of LSD</h3>
<p>LSD is efficient when there are trends in fertility in two perpendicular directions or when there are two factors contributing to experimental error.</p>
</section>
<section id="disadvantages-of-lsd" class="level3" data-number="20.3.8">
<h3 data-number="20.3.8" class="anchored" data-anchor-id="disadvantages-of-lsd"><span class="header-section-number">20.3.8</span> Disadvantages of LSD</h3>
<p>In LSD there is no restriction like number of replications = number of treatments, as required in RCBD; the number of replications is instead fixed to be equal to the number of treatments <span class="math inline">\(v\)</span>. The error degrees of freedom in this design is <span class="math inline">\((v-1)(v-2)\)</span>. For a number of treatments like <span class="math inline">\(v\)</span> = 2, 3 and 4, this value is 0, 2 and 6 respectively (<em>i.e.,</em> very small, hence we cannot carry out the experiment as such for these values of <span class="math inline">\(v\)</span>).</p>
<p>Similarly when <span class="math inline">\(v&gt;10\)</span> the total number of plots required is <span class="math inline">\(v^2 &gt; 100\)</span>. So there will be difficulty in getting a large number of homogeneous plots. So LSD is commonly used for 5 to 10 treatments only.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Historical Insights">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Historical Insights
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>From a soldiers’ puzzle to the experimental field</strong></p>
<p>The Latin square has a history far older than the science of experimental design. The great mathematician <strong>Leonhard Euler</strong> studied such squares in the eighteenth century, most famously through his “problem of the 36 officers”: can six regiments, each with six officers of six different ranks, be arranged in a 6 x 6 square so that every row and every column contains one officer of each rank and one from each regiment? Euler conjectured that no such arrangement exists for a 6 x 6 square, and he was eventually proved right. He called the arrangements <em>Latin squares</em> because he used Latin letters to fill them.</p>
<p>For more than a century the Latin square remained a mathematical curiosity. Its transformation into a tool of science came in the 1920s at the <strong>Rothamsted Experimental Station</strong>, where <strong>Ronald A. Fisher</strong> recognised that the same combinatorial structure could solve a very practical agricultural problem: how to remove soil fertility variation running in <em>two</em> perpendicular directions at once. By assigning treatments so that each appears exactly once in every row and every column, the row and column effects (the two fertility gradients) can be separated out and removed from the experimental error. Fisher introduced the Latin square design in his 1925 book <em>Statistical Methods for Research Workers</em> and developed it further in <em>The Design of Experiments</em> (1935). What began as a puzzle about arranging officers thus became one of the most elegant designs in agricultural research, and a fine example of how pure mathematics can find unexpected use in the service of science. <span class="citation" data-cites="Fisher1925">(<a href="references.html#ref-Fisher1925" role="doc-biblioref">Fisher 1925</a>)</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Quotes to Inspire">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quotes to Inspire
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>“The object of statistical methods is the reduction of data.”</strong><br>
<strong>- R. A. Fisher</strong></p>
</div>
</div>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">20.4</span> Chapter Summary</h2>
<section id="fill-in-the-blanks" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fill-in-the-blanks">Fill in the blanks</h3>
<p>Answers are given at the end of the chapter.</p>
<ol type="1">
<li><p>Experiments in which only a single factor varies while all others are kept constant are called __________ experiments.</p></li>
<li><p>In CRD, treatments are assigned to experimental units __________.</p></li>
<li><p>CRD requires only the two basic principles of __________ and replication.</p></li>
<li><p>__________ is not required in CRD since all experimental units are homogeneous.</p></li>
<li><p>CRD is suitable for experiments with __________ experimental units, such as laboratory or greenhouse experiments.</p></li>
<li><p>In CRD, treatments can have __________ replications.</p></li>
<li><p>The total number of experimental units in CRD is given by <span class="math inline">\(n =\)</span> __________.</p></li>
<li><p>The error degrees of freedom in CRD is given by __________.</p></li>
<li><p>A common rule of thumb is that the error degrees of freedom of a design should be at least __________.</p></li>
<li><p>The statistical model for CRD is the same as that of __________ ANOVA.</p></li>
<li><p>In the CRD model <span class="math inline">\(Y_{ij}=\mu+\tau_i+e_{ij}\)</span>, <span class="math inline">\(\tau_i\)</span> represents the effect of the <span class="math inline">\(i^{th}\)</span> __________.</p></li>
<li><p>The post-hoc test commonly used after a significant ANOVA in agricultural experiments is Fisher’s __________ test.</p></li>
<li><p>Treatment pairs whose difference in means is greater than the critical difference are said to be significantly __________.</p></li>
<li><p>Treatments that are not significantly different from each other are said to be __________.</p></li>
<li><p>RCBD is recommended when the experimental material has a fertility gradient in __________ direction.</p></li>
<li><p>Compared to CRD, RCBD additionally uses the principle of __________.</p></li>
<li><p>Homogeneous sub-groups into which experimental material is grouped in RCBD are called __________.</p></li>
<li><p>In RCBD, the number of replications equals the number of __________.</p></li>
<li><p>In RCBD, the number of plots within a block equals the number of __________.</p></li>
<li><p>The statistical model of RCBD is the same as that of __________ ANOVA.</p></li>
<li><p>In the RCBD model <span class="math inline">\(Y_{ij}=\mu+\tau_i+\gamma_j+e_{ij}\)</span>, <span class="math inline">\(\gamma_j\)</span> represents the effect of the <span class="math inline">\(j^{th}\)</span> __________.</p></li>
<li><p>If the F value for blocks in an RCBD ANOVA is not significant, it indicates that __________ has not been effective.</p></li>
<li><p>The error degrees of freedom formula for RCBD is __________.</p></li>
<li><p>Latin Square Design controls variation in __________ perpendicular directions simultaneously.</p></li>
<li><p>In a Latin square of side <span class="math inline">\(v\)</span>, every treatment is replicated in each row and each column exactly __________.</p></li>
<li><p>Data from an LSD experiment are classified according to __________ factors, making it a three-way classified design.</p></li>
<li><p>In an LSD, the number of rows, columns, and treatments are all equal to __________.</p></li>
<li><p>The error degrees of freedom in an LSD is given by __________.</p></li>
<li><p>LSD is commonly recommended for __________ to __________ treatments.</p></li>
<li><p>The mathematician who studied Latin squares in the eighteenth century, long before their use in experimental design, was __________.</p></li>
<li><p>Fisher introduced the Latin square design in his book __________.</p></li>
<li><p>In LSD, the total sum of squares is split into __________ components.</p></li>
<li><p>In LSD, the correction factor is calculated as __________.</p></li>
<li><p>Among CRD, RCBD, and LSD, for a fixed number of treatments and replications, __________ yields the maximum error degrees of freedom.</p></li>
<li><p>In a treatment-grouping table, treatments sharing a common letter are __________ significantly different.</p></li>
<li><p>Fisher’s LSD formula for CRD with equal replication uses __________ in the denominator under the square root, along with <span class="math inline">\(2\times\text{MSE}\)</span>.</p></li>
<li><p>In CRD with unequal replication, the C.D. formula uses <span class="math inline">\(\dfrac{1}{r_i}+\dfrac{1}{r_j}\)</span> in place of __________.</p></li>
<li><p>The blocks in a Latin Square Design are called __________ and __________.</p></li>
</ol>
</section>
<section id="short-answer-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="short-answer-questions">Short-answer questions</h3>
<ol type="1">
<li><p>Define a single factor experiment.</p></li>
<li><p>What is a Completely Randomized Design?</p></li>
<li><p>Explain why CRD is rarely used for field experiments.</p></li>
<li><p>Which basic principles of design are followed in CRD, and which is not required?</p></li>
<li><p>Explain the randomization procedure used in CRD.</p></li>
<li><p>Write the statistical model for CRD and explain each term.</p></li>
<li><p>Explain how the treatment sum of squares is calculated in CRD when replications are unequal.</p></li>
<li><p>Explain Fisher’s Least Significant Difference (LSD) test.</p></li>
<li><p>Distinguish between “significantly different” and “at par” treatments.</p></li>
<li><p>Explain how letters or symbols are used to group treatment means.</p></li>
<li><p>State the advantages of CRD.</p></li>
<li><p>State the disadvantages of CRD.</p></li>
<li><p>Explain why the error degrees of freedom of a design is generally kept at 12 or more.</p></li>
<li><p>Explain how the minimum number of replications required for a CRD is determined.</p></li>
<li><p>Explain the concept of blocking in RCBD.</p></li>
<li><p>What two factors should be considered while forming blocks in a field experiment?</p></li>
<li><p>Describe the randomization procedure followed in RCBD.</p></li>
<li><p>Explain the layout of an RCBD.</p></li>
<li><p>Write the statistical model for RCBD and explain each term.</p></li>
<li><p>Explain how the number of replications required for an RCBD is determined.</p></li>
<li><p>Explain what it means when the F value for blocks is not significant in an RCBD ANOVA.</p></li>
<li><p>State the advantages of RCBD over CRD.</p></li>
<li><p>State the disadvantages of RCBD.</p></li>
<li><p>Explain why a Latin Square Design is used instead of RCBD in certain situations.</p></li>
<li><p>Explain the layout of a Latin Square Design.</p></li>
<li><p>Describe the randomization procedure followed in LSD.</p></li>
<li><p>Write the statistical model for LSD and explain each term.</p></li>
<li><p>Explain why the error degrees of freedom in an LSD is <span class="math inline">\((v-1)(v-2)\)</span>.</p></li>
<li><p>Explain why LSD is not commonly used for a very small or very large number of treatments.</p></li>
<li><p>State the advantages and disadvantages of LSD.</p></li>
</ol>
</section>
<section id="numerical-and-conceptual-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="numerical-and-conceptual-questions">Numerical and conceptual questions</h3>
<p>Answers are given at the end of the chapter.</p>
<ol type="1">
<li><p>An experimenter has 6 treatments and plans to conduct the experiment in CRD. Find the minimum number of replications required.</p></li>
<li><p>An experimenter has 5 treatments and plans to conduct the experiment in RCBD. Find the minimum number of blocks required.</p></li>
<li><p>A CRD has 4 treatments with 6 replications each. Write down the degrees of freedom for treatments, error, and total.</p></li>
<li><p>An RCBD has 5 treatments and 4 blocks. Write down the degrees of freedom for treatments, blocks, error, and total.</p></li>
<li><p>A Latin Square Design has <span class="math inline">\(v=6\)</span> treatments. Write down the degrees of freedom for rows, columns, treatments, error, and total.</p></li>
<li><p>In a CRD, the treatment sum of squares is 210.40 and the total sum of squares is 285.60, with 4 treatments and 4 replications each. Find the error sum of squares and the degrees of freedom for treatments and error.</p></li>
<li><p>In an RCBD with <span class="math inline">\(v=5\)</span> treatments and <span class="math inline">\(r=4\)</span> blocks, the total SS is 500, treatment SS is 300, and block SS is 120. Find the error SS and the error degrees of freedom.</p></li>
<li><p>In a Latin square with <span class="math inline">\(v=5\)</span>, the row SS is 253.76, column SS is 272.56, treatment SS is 1064.96, and total SS is 1753.36. Find the error SS.</p></li>
<li><p>Why is CRD generally preferred over RCBD when experimental units are known to be homogeneous?</p></li>
<li><p>Two treatments in a CRD have means 40 and 35, and the calculated critical difference is 4. Are the two treatments significantly different? Explain.</p></li>
<li><p>Two treatments in an RCBD have means 28 and 30, and the calculated critical difference is 3. Are the two treatments significantly different? Explain.</p></li>
<li><p>Explain, with reasons, whether CRD, RCBD, or LSD would be most appropriate for a greenhouse pot experiment with homogeneous potting mixture.</p></li>
<li><p>Explain, with reasons, whether CRD, RCBD, or LSD would be most appropriate for a field experiment with a fertility gradient running in one direction only.</p></li>
<li><p>Explain, with reasons, whether CRD, RCBD, or LSD would be most appropriate for a field experiment with fertility gradients running in two perpendicular directions.</p></li>
<li><p>In a treatment-grouping table, treatment P is labelled “a”, treatment Q is labelled “ab”, and treatment R is labelled “b”. Explain the relationships among P, Q, and R.</p></li>
</ol>
</section>
<section id="important-formulae" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="important-formulae">Important formulae</h3>
<p>Total number of experimental units in CRD:</p>
<p><span class="math display">\[
n=rt
\]</span></p>
<p>Error degrees of freedom in CRD:</p>
<p><span class="math display">\[
edf=n-t=t(r-1)
\]</span></p>
<p>Error degrees of freedom in RCBD:</p>
<p><span class="math display">\[
edf=(v-1)(r-1)
\]</span></p>
<p>Error degrees of freedom in LSD:</p>
<p><span class="math display">\[
edf=(v-1)(v-2)
\]</span></p>
<p>Critical difference for CRD with equal replication:</p>
<p><span class="math display">\[
C.D.=t_{\left(\frac{\alpha}{2},\,error\,df\right)}\sqrt{\frac{2\,MSE}{r}}
\]</span></p>
<p>Critical difference for CRD with unequal replication:</p>
<p><span class="math display">\[
C.D.=t_{\left(\frac{\alpha}{2},\,error\,df\right)}\sqrt{MSE\left(\frac{1}{r_i}+\frac{1}{r_j}\right)}
\]</span></p>
<p>Critical difference for RCBD:</p>
<p><span class="math display">\[
CD=t_{\frac{\alpha}{2},edf}\sqrt{\frac{2\,MSE}{r}}
\]</span></p>
<p>Critical difference for LSD:</p>
<p><span class="math display">\[
C.D.=t_{\left(\frac{\alpha}{2},\,error\,df\right)}\sqrt{\frac{2\,MSE}{v}}
\]</span></p>
<p>Correction factor for LSD:</p>
<p><span class="math display">\[
C.F.=\frac{\left(\sum y_{ijk}\right)^2}{v^2}
\]</span></p>
</section>
<section id="quick-revision" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="quick-revision">Quick revision</h3>
<ul>
<li><p>A single factor experiment varies only one factor, the treatments, while all other conditions are kept uniform.</p></li>
<li><p>CRD uses only randomization and replication; local control is not needed since experimental units are already homogeneous.</p></li>
<li><p>CRD is best suited to laboratory and greenhouse experiments; it is rarely used for field experiments because field plots are usually not homogeneous.</p></li>
<li><p>RCBD adds local control (blocking) to randomization and replication, grouping heterogeneous experimental material into homogeneous blocks along a single known source of variation, most often a fertility gradient.</p></li>
<li><p>In RCBD, number of blocks = number of replications, and number of plots per block = number of treatments.</p></li>
<li><p>LSD controls variation in two perpendicular directions at once, using rows and columns as two separate blocking factors, so the number of rows, columns, and treatments are all equal.</p></li>
<li><p>The statistical model of CRD matches one-way ANOVA; the model of RCBD matches two-way ANOVA; LSD requires a three-way classification (rows, columns, treatments).</p></li>
<li><p>Error degrees of freedom should generally be at least 12, since F critical values change very little beyond this point; this rule is used to decide the minimum number of replications needed in a design.</p></li>
<li><p>When the overall F test for treatments is significant, Fisher’s Least Significant Difference (LSD) test is used to compare treatment pairs.</p></li>
<li><p>Treatment means that share a common letter or symbol in a grouping table are not significantly different from each other.</p></li>
<li><p>Among CRD, RCBD, and LSD (for the same number of treatments and replications), CRD gives the largest error degrees of freedom, since none of the variation is set aside for blocking.</p></li>
<li><p>LSD is typically restricted to 5 to 10 treatments: too few treatments leave almost no error degrees of freedom, and too many require an impractically large number of homogeneous plots.</p></li>
</ul>
</section>
<section id="answers-to-fill-in-the-blanks" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="answers-to-fill-in-the-blanks">Answers to fill in the blanks</h3>
<div class="answer-key">
<p><code>1.</code> Single factor <code>2.</code> Completely at random <code>3.</code> Randomization <code>4.</code> Local control <code>5.</code> Homogeneous <code>6.</code> Unequal <code>7.</code> <span class="math inline">\(rt\)</span> <code>8.</code> <span class="math inline">\(n-t\)</span> or <span class="math inline">\(t(r-1)\)</span> <code>9.</code> 12 <code>10.</code> One-way <code>11.</code> Treatment <code>12.</code> Least Significant Difference (LSD) <code>13.</code> Different <code>14.</code> At par <code>15.</code> One <code>16.</code> Local control <code>17.</code> Blocks <code>18.</code> Blocks <code>19.</code> Treatments <code>20.</code> Two-way <code>21.</code> Block <code>22.</code> Blocking <code>23.</code> <span class="math inline">\((v-1)(r-1)\)</span> <code>24.</code> Two <code>25.</code> Once <code>26.</code> Three <code>27.</code> <span class="math inline">\(v\)</span> <code>28.</code> <span class="math inline">\((v-1)(v-2)\)</span> <code>29.</code> Five; ten <code>30.</code> Leonhard Euler <code>31.</code> <em>Statistical Methods for Research Workers</em> <code>32.</code> Four <code>33.</code> <span class="math inline">\(\dfrac{(\sum y_{ijk})^2}{v^2}\)</span> <code>34.</code> CRD <code>35.</code> Not <code>36.</code> <span class="math inline">\(r\)</span> (the common number of replications) <code>37.</code> <span class="math inline">\(\dfrac{2}{r}\)</span> <code>38.</code> Rows; columns</p>
</div>
</section>
<section id="solutions-to-numerical-and-conceptual-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="solutions-to-numerical-and-conceptual-questions">Solutions to numerical and conceptual questions</h3>
<ol type="1">
<li><p>For CRD, <span class="math inline">\(edf=t(r-1)\geq12\)</span>. With <span class="math inline">\(t=6\)</span>, <span class="math inline">\(6(r-1)\geq12 \Rightarrow r-1\geq2 \Rightarrow r\geq3\)</span>. The minimum number of replications required is 3.</p></li>
<li><p>For RCBD, <span class="math inline">\(edf=(v-1)(r-1)\geq12\)</span>. With <span class="math inline">\(v=5\)</span>, <span class="math inline">\(4(r-1)\geq12 \Rightarrow r-1\geq3 \Rightarrow r\geq4\)</span>. The minimum number of blocks required is 4.</p></li>
<li><p>With <span class="math inline">\(t=4\)</span> treatments and <span class="math inline">\(r=6\)</span> replications, <span class="math inline">\(n=24\)</span>. Treatment df <span class="math inline">\(=t-1=3\)</span>; Error df <span class="math inline">\(=n-t=20\)</span>; Total df <span class="math inline">\(=n-1=23\)</span>.</p></li>
<li><p>With <span class="math inline">\(v=5\)</span> treatments and <span class="math inline">\(r=4\)</span> blocks, <span class="math inline">\(n=20\)</span>. Treatment df <span class="math inline">\(=v-1=4\)</span>; Block df <span class="math inline">\(=r-1=3\)</span>; Error df <span class="math inline">\(=(v-1)(r-1)=12\)</span>; Total df <span class="math inline">\(=n-1=19\)</span>.</p></li>
<li><p>With <span class="math inline">\(v=6\)</span>, Row df <span class="math inline">\(=v-1=5\)</span>; Column df <span class="math inline">\(=v-1=5\)</span>; Treatment df <span class="math inline">\(=v-1=5\)</span>; Error df <span class="math inline">\(=(v-1)(v-2)=20\)</span>; Total df <span class="math inline">\(=v^2-1=35\)</span>.</p></li>
<li><p>Error SS <span class="math inline">\(=285.60-210.40=75.20\)</span>. Treatment df <span class="math inline">\(=4-1=3\)</span>; Error df <span class="math inline">\(=n-t=16-4=12\)</span>.</p></li>
<li><p>Error SS <span class="math inline">\(=500-300-120=80\)</span>. Error df <span class="math inline">\(=(v-1)(r-1)=(5-1)(4-1)=12\)</span>.</p></li>
<li><p>Error SS <span class="math inline">\(=1753.36-253.76-272.56-1064.96=162.08\)</span>.</p></li>
<li><p>CRD makes full use of the experimental material without setting aside any degrees of freedom for blocking, so when units are genuinely homogeneous, CRD gives the maximum possible error degrees of freedom and the simplest analysis, without the loss of information that blocking causes when it is not actually needed.</p></li>
<li><p>The difference between the means is <span class="math inline">\(40-35=5\)</span>, which is greater than the critical difference of 4, so the two treatments are significantly different.</p></li>
<li><p>The difference between the means is <span class="math inline">\(30-28=2\)</span>, which is less than the critical difference of 3, so the two treatments are not significantly different; they are said to be at par.</p></li>
<li><p>CRD would be most appropriate, since the potting mixture is homogeneous and environmental conditions in a greenhouse are relatively easy to control; local control is unnecessary, and CRD gives the simplest analysis with the maximum error degrees of freedom.</p></li>
<li><p>RCBD would be most appropriate, since the fertility gradient runs in a single direction and can be controlled by forming blocks perpendicular to that gradient, leaving randomization and replication within each block to handle the remaining variation.</p></li>
<li><p>LSD would be most appropriate, since it controls variation in two perpendicular directions simultaneously using rows and columns, which a single blocking factor in RCBD cannot do.</p></li>
<li><p>P (labelled “a”) and Q (labelled “ab”) share the letter “a”, so they are not significantly different. Q (labelled “ab”) and R (labelled “b”) share the letter “b”, so they are also not significantly different. However, P (labelled “a”) and R (labelled “b”) share no common letter, so they are significantly different from each other.</p></li>
</ol>



<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Fisher1925" class="csl-entry" role="listitem">
Fisher, Ronald A. 1925. <em>Statistical Methods for Research Workers</em>. Edinburgh: Oliver; Boyd.
</div>
<div id="ref-fisher1935statistical" class="csl-entry" role="listitem">
Fisher, Ronald A., and Frank Yates. 1935. <em>Statistical Tables for Biological, Agricultural and Medical Research</em>. Edinburgh: Oliver; Boyd.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.agrinoteskau\.com\/agstat-textbook\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./multipleComparison.html" class="pagination-link" aria-label="Multiple comparison tests">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple comparison tests</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./factorial.html" class="pagination-link" aria-label="Factorial experiments">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Factorial experiments</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Published by PAPAYA publishing division of <a href="https://www.statoberry.com/papaya"><img src=".\images/statoberry.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>   
    <div class="nav-footer-center">
<p><a href="https://www.statoberry.com/papaya"><img src=".\images/papayalogo.png" class="img-fluid" style="width: auto; height: 90px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>
    <div class="nav-footer-right">
<p>Licenced under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC-BY-NC-ND 4.0 Int License</a> <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img src=".\images/cclogo.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a> Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>