<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15&nbsp; Small sample tests – TEXTBOOK OF AGRICULTURAL STATISTICS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./designofexperiments.html" rel="next">
<link href="./largeSampletest.html" rel="prev">
<link href="./images/cover.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-fb77ba77b36fd600d9d65d23f81eb906.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-88896ba663fc8608535e7267b4dbf4c8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-fb77ba77b36fd600d9d65d23f81eb906.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="15&nbsp; Small sample tests – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:description" content="">
<meta property="og:image" content="https://www.agrinoteskau.com/agstat-textbook.html/images/cover.jpg">
<meta property="og:site_name" content="TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:title" content="15&nbsp; Small sample tests – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://www.agrinoteskau.com/agstat-textbook.html/images/papayalogo.png">
<meta name="twitter:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="541">
<meta name="twitter:image-width" content="956">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./smallsampleTest.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Small sample tests</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/sidebarcover.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./images/sidebarcover.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEXTBOOK OF AGRICULTURAL STATISTICS</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basics of statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agstatindia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Official agricultural statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical representation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Central tendency I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Central tendency II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dispersion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measures of dispersion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./skewness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Skewness and kurtosis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./association.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of association</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probabilitydist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampleSurvey.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Sample survey</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesisTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./largeSampletest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Large sample test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./smallsampleTest.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Small sample tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./designofexperiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Design of experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uniformityTrials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Uniformity trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multipleComparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple comparison tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singleFactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Single factor experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./factorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Factorial experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analysis of covariance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./missingPlot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Missing plot analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Appendix 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Appendix 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Appendix 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Appendix 4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Appendix 5</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_personalities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Appendix 3</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#tests-based-on-students-t-distribution-t-tests" id="toc-tests-based-on-students-t-distribution-t-tests" class="nav-link active" data-scroll-target="#tests-based-on-students-t-distribution-t-tests"><span class="header-section-number">15.1</span> Tests based on Student’s t distribution (t-tests)</a>
  <ul class="collapse">
  <li><a href="#test-for-a-single-population-mean" id="toc-test-for-a-single-population-mean" class="nav-link" data-scroll-target="#test-for-a-single-population-mean"><span class="header-section-number">15.1.1</span> Test for a single population mean</a></li>
  <li><a href="#sec-tdecision" id="toc-sec-tdecision" class="nav-link" data-scroll-target="#sec-tdecision"><span class="header-section-number">15.1.2</span> Decision rule for the t test</a></li>
  </ul></li>
  <li><a href="#test-for-equality-of-two-means" id="toc-test-for-equality-of-two-means" class="nav-link" data-scroll-target="#test-for-equality-of-two-means"><span class="header-section-number">15.2</span> Test for equality of two means</a>
  <ul class="collapse">
  <li><a href="#when-the-population-variances-are-equal-homogeneous" id="toc-when-the-population-variances-are-equal-homogeneous" class="nav-link" data-scroll-target="#when-the-population-variances-are-equal-homogeneous">When the population variances are equal (homogeneous)</a></li>
  <li><a href="#when-the-population-variances-are-unequal" id="toc-when-the-population-variances-are-unequal" class="nav-link" data-scroll-target="#when-the-population-variances-are-unequal">When the population variances are unequal</a></li>
  </ul></li>
  <li><a href="#paired-t-test" id="toc-paired-t-test" class="nav-link" data-scroll-target="#paired-t-test"><span class="header-section-number">15.3</span> Paired t-test</a></li>
  <li><a href="#testing-the-significance-of-a-correlation-coefficient" id="toc-testing-the-significance-of-a-correlation-coefficient" class="nav-link" data-scroll-target="#testing-the-significance-of-a-correlation-coefficient"><span class="header-section-number">15.4</span> Testing the significance of a correlation coefficient</a></li>
  <li><a href="#chi-square-test-chi2" id="toc-chi-square-test-chi2" class="nav-link" data-scroll-target="#chi-square-test-chi2"><span class="header-section-number">15.5</span> Chi-square test (<span class="math inline">\(\chi^2\)</span>)</a>
  <ul class="collapse">
  <li><a href="#chi-square-test-for-goodness-of-fit" id="toc-chi-square-test-for-goodness-of-fit" class="nav-link" data-scroll-target="#chi-square-test-for-goodness-of-fit"><span class="header-section-number">15.5.1</span> Chi-square test for goodness of fit</a></li>
  <li><a href="#chi-square-test-for-independence-of-attributes" id="toc-chi-square-test-for-independence-of-attributes" class="nav-link" data-scroll-target="#chi-square-test-for-independence-of-attributes"><span class="header-section-number">15.5.2</span> Chi-square test for independence of attributes</a></li>
  <li><a href="#chi-square-test-for-a-22-contingency-table" id="toc-chi-square-test-for-a-22-contingency-table" class="nav-link" data-scroll-target="#chi-square-test-for-a-22-contingency-table"><span class="header-section-number">15.5.3</span> Chi-square test for a 2×2 contingency table</a></li>
  <li><a href="#chi-square-test-for-a-population-variance" id="toc-chi-square-test-for-a-population-variance" class="nav-link" data-scroll-target="#chi-square-test-for-a-population-variance"><span class="header-section-number">15.5.4</span> Chi-square test for a population variance</a></li>
  </ul></li>
  <li><a href="#sec-ftest" id="toc-sec-ftest" class="nav-link" data-scroll-target="#sec-ftest"><span class="header-section-number">15.6</span> F-test for equality of two population variances</a>
  <ul class="collapse">
  <li><a href="#decision-rule-for-the-f-test" id="toc-decision-rule-for-the-f-test" class="nav-link" data-scroll-target="#decision-rule-for-the-f-test">Decision rule for the F-test</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">15.7</span> Chapter Summary</a>
  <ul class="collapse">
  <li><a href="#fill-in-the-blanks" id="toc-fill-in-the-blanks" class="nav-link" data-scroll-target="#fill-in-the-blanks">Fill in the blanks</a></li>
  <li><a href="#short-answer-questions" id="toc-short-answer-questions" class="nav-link" data-scroll-target="#short-answer-questions">Short-answer questions</a></li>
  <li><a href="#numerical-and-conceptual-questions" id="toc-numerical-and-conceptual-questions" class="nav-link" data-scroll-target="#numerical-and-conceptual-questions">Numerical and conceptual questions</a></li>
  <li><a href="#important-formulae" id="toc-important-formulae" class="nav-link" data-scroll-target="#important-formulae">Important formulae</a></li>
  <li><a href="#quick-revision" id="toc-quick-revision" class="nav-link" data-scroll-target="#quick-revision">Quick revision</a></li>
  <li><a href="#answers-to-fill-in-the-blanks" id="toc-answers-to-fill-in-the-blanks" class="nav-link" data-scroll-target="#answers-to-fill-in-the-blanks">Answers to fill in the blanks</a></li>
  <li><a href="#solutions-to-numerical-and-conceptual-questions" id="toc-solutions-to-numerical-and-conceptual-questions" class="nav-link" data-scroll-target="#solutions-to-numerical-and-conceptual-questions">Solutions to numerical and conceptual questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Small sample tests</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<style>
/* Remove alternating row shading from tables in this chapter, matching the
   plain table style used elsewhere in the book. */
.lightable-classic tbody tr:nth-child(odd),
.lightable-classic tbody tr:nth-child(even),
table.table tbody tr:nth-child(odd),
table.table tbody tr:nth-child(even),
table tbody tr:nth-child(odd),
table tbody tr:nth-child(even) {
  background-color: transparent !important;
}
</style>
<p>If the sample size <span class="math inline">\(n\)</span> is less than 30 (<span class="math inline">\(n &lt; 30\)</span>), it is known as a <strong>small sample</strong>. For small samples, the sampling distributions commonly used are the <span class="math inline">\(\chi^2\)</span> (chi-square), <span class="math inline">\(F\)</span>, and <span class="math inline">\(t\)</span> distributions. The study of the sampling distribution of a statistic for small samples is known as <strong>small sample theory</strong>.</p>
<section id="tests-based-on-students-t-distribution-t-tests" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="tests-based-on-students-t-distribution-t-tests"><span class="header-section-number">15.1</span> Tests based on Student’s t distribution (t-tests)</h2>
<p><strong>Assumptions of the t-test</strong></p>
<ul>
<li><p>The parent population from which the sample is drawn is normal.</p></li>
<li><p>The sample is a random sample.</p></li>
<li><p>The population standard deviation <span class="math inline">\(\sigma\)</span> is unknown.</p></li>
</ul>
<section id="test-for-a-single-population-mean" class="level3" data-number="15.1.1">
<h3 data-number="15.1.1" class="anchored" data-anchor-id="test-for-a-single-population-mean"><span class="header-section-number">15.1.1</span> Test for a single population mean</h3>
<p>Consider a population with mean <span class="math inline">\(\mu\)</span>, where <span class="math inline">\(\mu\)</span> is unknown. We take a random sample of size <span class="math inline">\(n\)</span> (<span class="math inline">\(n &lt; 30\)</span>) from the population and calculate the sample mean <span class="math inline">\(\overline{x}\)</span>. We want to test whether the population mean <span class="math inline">\(\mu\)</span> is equal to a known constant <span class="math inline">\(\mu_0\)</span>, based on the sample mean.</p>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> = <span class="math inline">\(\mu_0\)</span></p>
<p>The alternative hypothesis may be either:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> &lt; <span class="math inline">\(\mu_0\)</span> (left-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> &gt; <span class="math inline">\(\mu_0\)</span> (right-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_0\)</span> (two-tailed alternative)</p>
<p>The test statistic is:</p>
<p><span id="eq-t-single"><span class="math display">\[t = \frac{\overline{x} - \mu_0}{\dfrac{s}{\sqrt{n}}} \tag{15.1}\]</span></span></p>
<p>where <span class="math inline">\(s^2 = \dfrac{\sum_{i=1}^{n}\left( x_i - \overline{x} \right)^2}{n - 1}\)</span>.</p>
<p>Under the null hypothesis, <span class="math inline">\(t\)</span> follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom.</p>
</section>
<section id="sec-tdecision" class="level3" data-number="15.1.2">
<h3 data-number="15.1.2" class="anchored" data-anchor-id="sec-tdecision"><span class="header-section-number">15.1.2</span> Decision rule for the t test</h3>
<p>Let <span class="math inline">\(t\)</span> be the calculated value, degrees of freedom = <span class="math inline">\(n - 1\)</span>, and <span class="math inline">\(\alpha\)</span> be the level of significance. We reject the null hypothesis if:</p>
<ul>
<li><p><span class="math inline">\(|t| &gt; t_{\alpha/2}\)</span> ; for a two-tailed test</p></li>
<li><p><span class="math inline">\(t &gt; t_{\alpha}\)</span> ; for a right-tailed test</p></li>
<li><p><span class="math inline">\(t &lt; -t_{\alpha}\)</span> ; for a left-tailed test</p></li>
</ul>
<p>Here <span class="math inline">\(t_{\alpha}\)</span> or <span class="math inline">\(t_{\alpha/2}\)</span> is obtained from the table of Student’s <span class="math inline">\(t\)</span> distribution for the given degrees of freedom <span class="math inline">\(n - 1\)</span> and level of significance <span class="math inline">\(\alpha\)</span>. If the calculated value of the test statistic is greater than the critical value from the table, we reject the null hypothesis. Otherwise, we do not have enough evidence to reject it.You can see the t-table in <a href="appendix4.html#tbl-ttable" class="quarto-xref">Table&nbsp;<span>27.1</span></a> of Appendix 4</p>
<div id="exm-tmean1" class="theorem example">
<p><span class="theorem-title"><strong>Example 15.1</strong></span> Based on field experiments, a new variety of green gram is expected to give a yield of 12 quintals per hectare. The variety was tested on 10 randomly selected farmers’ fields. The yields (quintals per hectare) were recorded as 14.3, 12.6, 13.7, 10.9, 13.7, 12, 11.4, 12, 12.6, and 13.1. Do the results confirm the expectation?</p>
<p><strong>Solution</strong></p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> = 12</p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> 12 (two-tailed test)</p>
<p>Sample size (<span class="math inline">\(n\)</span>) = 10</p>
<p>Sample mean, <span class="math inline">\(\overline{x}\)</span> = <span class="math inline">\(\dfrac{\sum_{i=1}^{n} x_i}{n} = \dfrac{14.3 + 12.6 + \ldots + 13.1}{10} = \dfrac{126.3}{10} = 12.63\)</span></p>
<p>Sample standard deviation (<span class="math inline">\(s\)</span>) = 1.0853</p>
<p><span class="math inline">\(\mu_0\)</span> = 12</p>
<p>Level of significance, <span class="math inline">\(\alpha\)</span> = 0.05</p>
<p>The calculation of the sample mean and sample standard deviation is shown in <a href="#tbl-tmean1" class="quarto-xref">Table&nbsp;<span>15.1</span></a>.</p>
<div id="tbl-tmean1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Calculation of sample mean and standard deviation" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tmean1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.1: Calculation of sample mean and standard deviation
</figcaption>
<div aria-describedby="tbl-tmean1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Sl No.&nbsp;
</th>
<th style="text-align:center;">
Yield
</th>
<th style="text-align:center;">
<span class="math display">\[\left( \mathbf{x}_{\mathbf{i}} \mathbf{-} \overline{\mathbf{x}} \right)\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[\left( \mathbf{x}_{\mathbf{i}} \mathbf{-} \overline{\mathbf{x}} \right)^{\mathbf{2}}\]</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
14.3
</td>
<td style="text-align:center;">
1.67
</td>
<td style="text-align:center;">
2.7889
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
12.6
</td>
<td style="text-align:center;">
-0.03
</td>
<td style="text-align:center;">
0.0009
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
13.7
</td>
<td style="text-align:center;">
1.07
</td>
<td style="text-align:center;">
1.1449
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
10.9
</td>
<td style="text-align:center;">
-1.73
</td>
<td style="text-align:center;">
2.9929
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
13.7
</td>
<td style="text-align:center;">
1.07
</td>
<td style="text-align:center;">
1.1449
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
-0.63
</td>
<td style="text-align:center;">
0.3969
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
11.4
</td>
<td style="text-align:center;">
-1.23
</td>
<td style="text-align:center;">
1.5129
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
-0.63
</td>
<td style="text-align:center;">
0.3969
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
12.6
</td>
<td style="text-align:center;">
-0.03
</td>
<td style="text-align:center;">
0.0009
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
13.1
</td>
<td style="text-align:center;">
0.47
</td>
<td style="text-align:center;">
0.2209
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>From <a href="#tbl-tmean1" class="quarto-xref">Table&nbsp;<span>15.1</span></a>, the sum of squared deviations is <span class="math inline">\(\sum_{i=1}^{n}\left( x_i - \overline{x} \right)^2 = 10.601\)</span>.</p>
<p><span class="math display">\[s^2 = \frac{\sum_{i=1}^{n}\left( x_i - \overline{x} \right)^2}{n-1} = \frac{10.601}{9} = 1.1779\]</span></p>
<p><span class="math display">\[s = \sqrt{1.1779} = 1.0853\]</span></p>
<p>The test statistic is:</p>
<p><span class="math display">\[t = \frac{\overline{x} - \mu_0}{\dfrac{s}{\sqrt{n}}} = \frac{12.63 - 12}{\dfrac{1.0853}{\sqrt{10}}}\]</span></p>
<p><span class="math display">\[= \frac{0.63}{0.3432} = 1.835\]</span></p>
<p>The table value of <span class="math inline">\(t\)</span> for 9 degrees of freedom at the 5% level of significance (two-tailed) is 2.262 (see the <a href="appendix4.html#tbl-ttable" class="quarto-xref">Table&nbsp;<span>27.1</span></a> in Appendix 4).</p>
<p>Since the calculated value (1.835) is less than the table value (2.262), we do not have enough evidence to reject the null hypothesis. We conclude that there is insufficient evidence to say the mean differs from 12 quintals per hectare. That is null hypothesis is not rejected and the results confirm the expectation.</p>
</div>
<div id="exr-tmean1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 15.1</strong></span> The mean weekly sales of soap bars in departmental stores were 146.3 bars per store. After an advertising campaign, the mean weekly sales in 22 stores for a typical week was 153.7, with a standard deviation of 17.2. Was the advertising campaign successful? (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
</div>
</section>
</section>
<section id="test-for-equality-of-two-means" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="test-for-equality-of-two-means"><span class="header-section-number">15.2</span> Test for equality of two means</h2>
<p>Let there be two normally distributed populations with means <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span>. Let the population standard deviations be equal and unknown. Let samples of sizes <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> be taken from these populations, with sample means <span class="math inline">\(\overline{x}_1\)</span> and <span class="math inline">\(\overline{x}_2\)</span> respectively. We want to test whether the two population means are significantly different, based on the sample means.</p>
<p>There are two cases under this situation:</p>
<ol type="1">
<li><p>Population variances are equal.</p></li>
<li><p>Population variances are unequal.</p></li>
</ol>
<p>Before proceeding to the t-test, an F-test is performed to test the homogeneity of population variances (see <a href="#sec-ftest" class="quarto-xref"><span>Section 15.6</span></a>).</p>
<section id="when-the-population-variances-are-equal-homogeneous" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="when-the-population-variances-are-equal-homogeneous">When the population variances are equal (homogeneous)</h3>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1\)</span> = <span class="math inline">\(\mu_2\)</span></p>
<p>The alternative hypothesis may be either:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> &lt; <span class="math inline">\(\mu_2\)</span> (left-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> &gt; <span class="math inline">\(\mu_2\)</span> (right-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_2\)</span> (two-tailed alternative)</p>
<p>We calculate the test statistic <span class="math inline">\(t\)</span> using the following formula:</p>
<p><span id="eq-t-two-equal"><span class="math display">\[t = \frac{\overline{x}_1 - \overline{x}_2}{s \sqrt{\dfrac{1}{n_1} + \dfrac{1}{n_2}}} \tag{15.2}\]</span></span></p>
<p>where <span class="math inline">\(s^2 = \dfrac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}\)</span> is the pooled variance, and <span class="math inline">\(\overline{x}_1\)</span> and <span class="math inline">\(\overline{x}_2\)</span> are the sample means from populations 1 and 2 respectively.</p>
<p>Under the null hypothesis, <span class="math inline">\(t\)</span> follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n_1 + n_2 - 2\)</span> degrees of freedom. The decision rule is the same as for the previous t-test (see <a href="#sec-tdecision" class="quarto-xref"><span>Section 15.1.2</span></a>).</p>
</section>
<section id="when-the-population-variances-are-unequal" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="when-the-population-variances-are-unequal">When the population variances are unequal</h3>
<p>The Welch t-test is an adaptation of Student’s t-test. It is used to compare the means of two groups when the variances are different.</p>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1\)</span> = <span class="math inline">\(\mu_2\)</span></p>
<p>The alternative hypothesis may be either:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> &lt; <span class="math inline">\(\mu_2\)</span> (left-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> &gt; <span class="math inline">\(\mu_2\)</span> (right-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_2\)</span> (two-tailed alternative)</p>
<p>We calculate the test statistic <span class="math inline">\(t\)</span> using the following formula:</p>
<p><span id="eq-t-welch"><span class="math display">\[t = \frac{\overline{x}_1 - \overline{x}_2}{\sqrt{\dfrac{s_1^2}{n_1} + \dfrac{s_2^2}{n_2}}} \tag{15.3}\]</span></span></p>
<p>where <span class="math inline">\(s_1\)</span> and <span class="math inline">\(s_2\)</span> are the sample standard deviations from the two populations respectively.</p>
<p>The degrees of freedom of the Welch t-test are calculated as follows:</p>
<p><span id="eq-welch-df"><span class="math display">\[\text{df} = \frac{\left( \dfrac{s_1^2}{n_1} + \dfrac{s_2^2}{n_2} \right)^2}{\dfrac{s_1^4}{n_1^2 (n_1 - 1)} + \dfrac{s_2^4}{n_2^2 (n_2 - 1)}} \tag{15.4}\]</span></span></p>
<p>Once the <span class="math inline">\(t\)</span> value is determined, read the critical value of Student’s <span class="math inline">\(t\)</span> distribution from the table corresponding to the significance level. The decision rule is the same as for the previous t-test (see <a href="#sec-tdecision" class="quarto-xref"><span>Section 15.1.2</span></a>).</p>
<div id="exr-tmean2" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 15.2</strong></span> In order to compare the effectiveness of two sources of nitrogen, namely ammonium chloride and urea, on the grain yield of paddy, an experiment was conducted. The results on the grain yield of paddy (kg/plot) under the two treatments are given below. Test whether the two sources differ in effectiveness. (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
<p><strong>Ammonium chloride</strong>: 13.4, 10.9, 11.2, 11.8, 14, 15.3, 14.2, 12.6, 17, 16.2, 16.5, 15.7</p>
<p><strong>Urea</strong>: 12, 11.7, 10.7, 11.2, 14.8, 14.4, 13.9, 13.7, 16.9, 16, 15.6, 16</p>
</div>
</section>
</section>
<section id="paired-t-test" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="paired-t-test"><span class="header-section-number">15.3</span> Paired t-test</h2>
<p>The paired t-test is used to compare the means of two related samples, that is, when we have two values (a pair of values) for the same experimental unit. For example, suppose 20 cows receive a treatment for 3 months and the question is whether the treatment has an impact on milk yield. The milk yield of the 20 cows is measured before and after the treatment. This gives 20 values before treatment and 20 values after treatment. To test whether there is any significant difference between before and after, the paired t-test can be used, because the two sets of values being compared are related. We have a pair of values for each cow, one before and one after treatment.</p>
<p>Suppose we have two correlated random samples <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span> and <span class="math inline">\(y_1, y_2, \ldots, y_n\)</span>. We want to test whether the two population means are significantly different.</p>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1\)</span> = <span class="math inline">\(\mu_2\)</span></p>
<p>The alternative hypothesis may be either:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> &lt; <span class="math inline">\(\mu_2\)</span> (left-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> &gt; <span class="math inline">\(\mu_2\)</span> (right-tailed alternative)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_2\)</span> (two-tailed alternative)</p>
<p>We calculate the test statistic <span class="math inline">\(t\)</span> using the following formula:</p>
<p><span id="eq-t-paired"><span class="math display">\[t = \frac{\overline{d}}{\dfrac{s}{\sqrt{n}}} \tag{15.5}\]</span></span></p>
<p>where <span class="math inline">\(\overline{d} = \dfrac{\sum_{i=1}^{n} d_i}{n}\)</span>, <span class="math inline">\(d_i = x_i - y_i\)</span>, and <span class="math inline">\(s^2 = \dfrac{\sum_{i=1}^{n}\left( d_i - \overline{d} \right)^2}{n - 1}\)</span>.</p>
<p>Under the null hypothesis, <span class="math inline">\(t\)</span> follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom. For a two-tailed test, we compare <span class="math inline">\(|t|\)</span> with the critical value. The decision rule is the same as for the previous t-test (see <a href="#sec-tdecision" class="quarto-xref"><span>Section 15.1.2</span></a>).</p>
<div id="exm-paired1" class="theorem example">
<p><span class="theorem-title"><strong>Example 15.2</strong></span> In an experiment, plots were divided into two equal parts. One part received soil treatment A and the second part received soil treatment B. Each plot was planted with sorghum. The sorghum yield (kg/plot) was observed as shown below. Test the effectiveness of the soil treatments on sorghum yield.</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">Treatment <strong>A</strong></td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">53</td>
</tr>
<tr class="even">
<td style="text-align: center;">Treatment <strong>B</strong></td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">53</td>
</tr>
</tbody>
</table>
<p><strong>Solution</strong></p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1\)</span> = <span class="math inline">\(\mu_2\)</span> (there is no significant difference between the effects of the two soil treatments)</p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_1\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> <span class="math inline">\(\mu_2\)</span> (two-tailed test; there is a significant difference between the effects of the two soil treatments)</p>
<p>Level of significance, <span class="math inline">\(\alpha\)</span> = 0.05</p>
<p>The calculation of the differences is shown in <a href="#tbl-paired1" class="quarto-xref">Table&nbsp;<span>15.2</span></a>.</p>
<div id="tbl-paired1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Calculation of paired differences" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-paired1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.2: Calculation of paired differences
</figcaption>
<div aria-describedby="tbl-paired1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Sl No.&nbsp;
</th>
<th style="text-align:center;">
<span class="math display">\[\mathbf{A}\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[\mathbf{B}\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[\mathbf{d}_{\mathbf{i}} \mathbf{= A - B}\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[\mathbf{d}_{\mathbf{i}} \mathbf{-} \overline{\mathbf{d}}\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[\left( \mathbf{d}_{\mathbf{i}} \mathbf{-} \overline{\mathbf{d}} \right)^{\mathbf{2}}\]</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
49
</td>
<td style="text-align:center;">
52
</td>
<td style="text-align:center;">
-3
</td>
<td style="text-align:center;">
-1
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
53
</td>
<td style="text-align:center;">
55
</td>
<td style="text-align:center;">
-2
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
51
</td>
<td style="text-align:center;">
52
</td>
<td style="text-align:center;">
-1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
52
</td>
<td style="text-align:center;">
53
</td>
<td style="text-align:center;">
-1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
47
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
-3
</td>
<td style="text-align:center;">
-1
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
54
</td>
<td style="text-align:center;">
-4
</td>
<td style="text-align:center;">
-2
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
52
</td>
<td style="text-align:center;">
54
</td>
<td style="text-align:center;">
-2
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
53
</td>
<td style="text-align:center;">
53
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>From <a href="#tbl-paired1" class="quarto-xref">Table&nbsp;<span>15.2</span></a>, <span class="math inline">\(\sum_{i=1}^{8} d_i = -16\)</span> and <span class="math inline">\(\sum_{i=1}^{8}\left( d_i - \overline{d} \right)^2 = 12\)</span>.</p>
<p><span class="math display">\[\overline{d} = \frac{\sum_{i=1}^{8} d_i}{n} = \frac{-16}{8} = -2\]</span></p>
<p><span class="math display">\[s^2 = \frac{\sum_{i=1}^{8}\left( d_i - \overline{d} \right)^2}{n-1} = \frac{12}{7} = 1.7143\]</span></p>
<p><span class="math display">\[s = \sqrt{1.7143} = 1.309\]</span></p>
<p><span class="math display">\[t = \frac{\overline{d}}{\dfrac{s}{\sqrt{n}}} = \frac{-2}{\dfrac{1.309}{\sqrt{8}}}\]</span></p>
<p><span class="math display">\[= \frac{-2}{0.4629} = -4.321\]</span></p>
<p>The table value of <span class="math inline">\(t\)</span> for 7 degrees of freedom at the 5% level of significance is 2.365.</p>
<p>Since the calculated value <span class="math inline">\(|t|\)</span> = 4.321 is greater than the table value (2.365), we reject the null hypothesis. We conclude that there is a significant difference between soil treatments A and B. Because <span class="math inline">\(d_i = A - B\)</span> is negative on average, soil treatment B increases the yield of sorghum significantly.</p>
</div>
<div id="exr-paired1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 15.3</strong></span> A certain stimulus administered to each of 12 patients resulted in the following increase in blood pressure: 5, 2, 8, -1, 3, 0, -2, 1, 5, 0, 4, 6. Can it be concluded that the stimulus is, in general, accompanied by an increase in blood pressure? (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
</div>
</section>
<section id="testing-the-significance-of-a-correlation-coefficient" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="testing-the-significance-of-a-correlation-coefficient"><span class="header-section-number">15.4</span> Testing the significance of a correlation coefficient</h2>
<p>Let there be two normally distributed populations with correlation coefficient <span class="math inline">\(\rho\)</span>. We want to test the null hypothesis that the population correlation coefficient is zero (<span class="math inline">\(\rho = 0\)</span>). A t-test can be used for this purpose. If we reject the null hypothesis, we conclude that there is a significant correlation in the population (<span class="math inline">\(\rho \neq 0\)</span>). If we do not have enough evidence to reject the null hypothesis, we conclude that there is no significant correlation.</p>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\rho\)</span> = 0</p>
<p>The alternative hypothesis is:</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\rho\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> 0 (two-tailed alternative)</p>
<p>The test statistic is:</p>
<p><span id="eq-t-corr"><span class="math display">\[t = \frac{r \sqrt{n - 2}}{\sqrt{1 - r^2}} \tag{15.6}\]</span></span></p>
<p>Under the null hypothesis, <span class="math inline">\(t\)</span> follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n - 2\)</span> degrees of freedom. We reject the null hypothesis if the calculated value is greater than the table value of <span class="math inline">\(t\)</span> corresponding to <span class="math inline">\(n - 2\)</span> degrees of freedom and the level of significance <span class="math inline">\(\alpha\)</span>. In our case <span class="math inline">\(\alpha\)</span> = 0.05.</p>
<div id="exm-corr1" class="theorem example">
<p><span class="theorem-title"><strong>Example 15.3</strong></span> A correlation coefficient of 0.2 was derived from a random sample of 625 pairs of observations. Test whether the population correlation coefficient is significant.</p>
<p><strong>Solution</strong></p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\rho\)</span> = 0 (population correlation coefficient is zero)</p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\rho\)</span> <span class="math inline">\(\mathbf{\neq}\)</span> 0 (population correlation coefficient is not zero)</p>
<p>Sample correlation coefficient (<span class="math inline">\(r\)</span>) = 0.2</p>
<p>Number of pairs (<span class="math inline">\(n\)</span>) = 625</p>
<p><span class="math display">\[t = \frac{r \sqrt{n - 2}}{\sqrt{1 - r^2}} = \frac{0.2 \sqrt{625 - 2}}{\sqrt{1 - 0.04}} = 5.095\]</span></p>
<p>Since the sample size is large (<span class="math inline">\(n &gt; 30\)</span>), the <span class="math inline">\(t\)</span> distribution can be approximated by the standard normal distribution. The critical value for a two-tailed test at the 5% level of significance is 1.96. Since the calculated value (5.095) is greater than 1.96, we reject the null hypothesis and conclude that there is a significant correlation in the population.</p>
</div>
</section>
<section id="chi-square-test-chi2" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="chi-square-test-chi2"><span class="header-section-number">15.5</span> Chi-square test (<span class="math inline">\(\chi^2\)</span>)</h2>
<p>Chi-square tests are based on the sampling distribution called the chi-square distribution (<span class="math inline">\(\chi^2\)</span> distribution). The <span class="math inline">\(\chi^2\)</span> tests are based on the following assumptions:</p>
<ol type="1">
<li><p>The sample observations are independent.</p></li>
<li><p>The total frequency should be reasonably large, say greater than 50.</p></li>
<li><p>The theoretical cell frequencies should not be less than 5. If any theoretical cell frequency is less than 5, it is pooled with the preceding or succeeding frequency so that the pooled frequency is more than 5, and the degrees of freedom lost in pooling are adjusted.</p></li>
<li><p>The constraints on the cell frequencies should be linear, for example <span class="math inline">\(\sum O_i = \sum E_i\)</span>, where <span class="math inline">\(O_i\)</span> and <span class="math inline">\(E_i\)</span> represent the observed and expected frequencies.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <span class="math inline">\(\chi^2\)</span> tests do not make any assumptions regarding the parent population from which the observations are taken. Such tests do not involve any population parameter. Hence these tests are known as <strong>non-parametric tests</strong> or <strong>distribution-free tests</strong>.</p>
</div>
</div>
<p><strong>Degrees of freedom in <span class="math inline">\(\chi^2\)</span> tests</strong>: Degrees of freedom refers to the number of independent variates that make up the statistic. In general, it is the total number of observations less the number of independent constraints imposed on the observations. For example, if <span class="math inline">\(k\)</span> is the number of independent constraints in a set of data on <span class="math inline">\(n\)</span> observations, then degrees of freedom = <span class="math inline">\(n - k\)</span>.</p>
<p>Three important chi-square tests are:</p>
<ul>
<li><p>Chi-square test for goodness of fit.</p></li>
<li><p>Chi-square test for independence of attributes.</p></li>
<li><p>Chi-square test for a variance.</p></li>
</ul>
<section id="chi-square-test-for-goodness-of-fit" class="level3" data-number="15.5.1">
<h3 data-number="15.5.1" class="anchored" data-anchor-id="chi-square-test-for-goodness-of-fit"><span class="header-section-number">15.5.1</span> Chi-square test for goodness of fit</h3>
<p>A very powerful test for the significance of the discrepancy between theory and experiment was given by Prof.&nbsp;Karl Pearson in 1900 and is known as the “<span class="math inline">\(\chi^2\)</span> test for goodness of fit”. <span class="citation" data-cites="Pearson1900">(<a href="references.html#ref-Pearson1900" role="doc-biblioref">Pearson 1900</a>)</span></p>
<p>We want to test the null hypothesis:</p>
<p><span class="math inline">\(H_0\)</span>: There is no significant difference between theory and experiment.</p>
<p>against the alternative hypothesis:</p>
<p><span class="math inline">\(H_1\)</span>: There is a significant difference between theory and experiment.</p>
<p>If <span class="math inline">\(O_i\)</span> (<span class="math inline">\(i = 1, 2, \ldots, n\)</span>) is a set of observed frequencies and <span class="math inline">\(E_i\)</span> (<span class="math inline">\(i = 1, 2, \ldots, n\)</span>) is the corresponding set of expected (theoretical) frequencies, then Karl Pearson’s chi-square test statistic is:</p>
<p><span id="eq-chi-gof"><span class="math display">\[\chi^2 = \sum_{i=1}^{n} \frac{\left( O_i - E_i \right)^2}{E_i} \tag{15.7}\]</span></span></p>
<p>Here <span class="math inline">\(O_i\)</span> represents the <span class="math inline">\(i^{\text{th}}\)</span> observed frequency and <span class="math inline">\(E_i\)</span> the corresponding expected frequency according to the theory behind the data. Under the null hypothesis, the statistic follows a chi-square distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom (when no parameter is estimated from the data).</p>
<section id="decision-rule-for-the-goodness-of-fit-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="decision-rule-for-the-goodness-of-fit-test">Decision rule for the goodness-of-fit test</h4>
<p>Let <span class="math inline">\(\chi^2_{\text{cal}}\)</span> be the calculated value, degrees of freedom = <span class="math inline">\(n - 1\)</span>, and <span class="math inline">\(\alpha\)</span> the level of significance. We reject the null hypothesis if <span class="math inline">\(\chi^2_{\text{cal}} &gt; \chi^2_{\text{tab}}\)</span>, where <span class="math inline">\(\chi^2_{\text{tab}}\)</span> is the table value of <span class="math inline">\(\chi^2\)</span> at <span class="math inline">\(n - 1\)</span> degrees of freedom. In the case of the <span class="math inline">\(\chi^2\)</span> test, only a one-tailed (right-tailed) test is used.</p>
<div id="exm-gof1" class="theorem example">
<p><span class="theorem-title"><strong>Example 15.4</strong></span> In plant genetics, our interest may be to test whether observed segregation ratios deviate significantly from Mendelian ratios. In such situations we test the agreement between observed and theoretical frequencies; such a test is called a test of goodness of fit. In a cross between parents of genetic constitution AAbb and aaBB, the phenotypes in the sample are classified as follows:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">AB</td>
<td style="text-align: center;">Ab</td>
<td style="text-align: center;">aB</td>
<td style="text-align: center;">ab</td>
<td style="text-align: center;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center;">87</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">160</td>
</tr>
</tbody>
</table>
<p>They are expected to occur in a 9:3:3:1 ratio. Do the data agree with the theoretical ratio?</p>
<p><strong>Solution</strong></p>
<p>The calculation of the chi-square statistic is shown in <a href="#tbl-gof1" class="quarto-xref">Table&nbsp;<span>15.3</span></a>.</p>
<div id="tbl-gof1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Calculation of chi-square for goodness of fit" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gof1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.3: Calculation of chi-square for goodness of fit
</figcaption>
<div aria-describedby="tbl-gof1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Phenotypes
</th>
<th style="text-align:center;">
AB
</th>
<th style="text-align:center;">
Ab
</th>
<th style="text-align:center;">
aB
</th>
<th style="text-align:center;">
ab
</th>
<th style="text-align:center;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Observed (Oi)
</td>
<td style="text-align:center;">
87
</td>
<td style="text-align:center;">
29
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
160
</td>
</tr>
<tr>
<td style="text-align:center;">
Expected (Ei)
</td>
<td style="text-align:center;">
90
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
160
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math display">\[\mathbf{O}_{\mathbf{i}}\mathbf{-}\mathbf{E}_{\mathbf{i}}\]</span>
</td>
<td style="text-align:center;">
-3
</td>
<td style="text-align:center;">
-1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math display">\[\left( \mathbf{O}_{\mathbf{i}}\mathbf{-}\mathbf{E}_{\mathbf{i}} \right)^{\mathbf{2}}\]</span>
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math display">\[\frac{\left( \mathbf{O}_{\mathbf{i}}\mathbf{-}\mathbf{E}_{\mathbf{i}} \right)^{\mathbf{2}}}{\mathbf{E}_{\mathbf{i}}}\]</span>
</td>
<td style="text-align:center;">
0.11
</td>
<td style="text-align:center;">
0.033
</td>
<td style="text-align:center;">
0.133
</td>
<td style="text-align:center;">
0.4
</td>
<td style="text-align:center;">
0.676
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^{n} \frac{\left( O_i - E_i \right)^2}{E_i} = 0.667\]</span></p>
<p><span class="math inline">\(\chi^2_{\text{cal}}\)</span> = 0.667. The table value of chi-square for <span class="math inline">\(4 - 1 = 3\)</span> degrees of freedom at the 5% level of significance is 7.815. Since the calculated value is less than the table value, we do not reject the null hypothesis. We conclude that the data agree with the 9:3:3:1 ratio.</p>
</div>
<div id="exr-gof1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 15.4</strong></span> The number of yeast cells counted in a haemocytometer is compared with the theoretical value given below. Does the experimental result support the theory? (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Yeast per cell</th>
<th style="text-align: center;">Observed Frequency</th>
<th style="text-align: center;">Expected Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">103</td>
<td style="text-align: center;">106</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">143</td>
<td style="text-align: center;">141</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">98</td>
<td style="text-align: center;">93</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">41</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">5</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="chi-square-test-for-independence-of-attributes" class="level3" data-number="15.5.2">
<h3 data-number="15.5.2" class="anchored" data-anchor-id="chi-square-test-for-independence-of-attributes"><span class="header-section-number">15.5.2</span> Chi-square test for independence of attributes</h3>
<p>The chi-square test of independence checks whether two attributes are likely to be related. For example, chemical treatment and germination can be two attributes. If we want to know whether chemical treatment has any influence on germination, we can use the chi-square test. For this purpose, the data are arranged in the form of a contingency table.</p>
<section id="contingency-table" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="contingency-table">Contingency table</h4>
<p>A contingency table is a tabular representation of categorical data, consisting of a collection of cells containing counts. It usually shows frequencies for particular combinations of values of two discrete random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Each cell represents a mutually exclusive combination of <span class="math inline">\(X\)</span>-<span class="math inline">\(Y\)</span> values.</p>
<div id="exm-conting1" class="theorem example">
<p><span class="theorem-title"><strong>Example 15.5</strong></span> In order to determine the possible effect of a chemical treatment on the germination rate of cotton seeds, a pot culture experiment was conducted. The results are given below in the form of a contingency table. (<span class="math inline">\(X\)</span> = germination, <span class="math inline">\(Y\)</span> = chemical treatment). Attribute <span class="math inline">\(X\)</span> has two classes, <span class="math inline">\(X_1\)</span> = germinated and <span class="math inline">\(X_2\)</span> = not germinated. Attribute <span class="math inline">\(Y\)</span> has two classes, <span class="math inline">\(Y_1\)</span> = treated and <span class="math inline">\(Y_2\)</span> = untreated.</p>
<div id="tbl-conting1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Contingency table for germination of cotton seeds" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-conting1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.4: Contingency table for germination of cotton seeds
</figcaption>
<div aria-describedby="tbl-conting1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
X/Y
</th>
<th style="text-align:center;">
Germinated(X<sub>1</sub>)
</th>
<th style="text-align:center;">
Not Germinated(X<sub>2</sub>)
</th>
<th style="text-align:center;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Treated(Y<sub>1</sub>)
</td>
<td style="text-align:center;">
118
</td>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
140
</td>
</tr>
<tr>
<td style="text-align:center;">
Untreated(Y<sub>2</sub>)
</td>
<td style="text-align:center;">
120
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
160
</td>
</tr>
<tr>
<td style="text-align:center;">
Total
</td>
<td style="text-align:center;">
238
</td>
<td style="text-align:center;">
62
</td>
<td style="text-align:center;">
300
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The solution is worked out in <a href="#sec-yates" class="quarto-xref"><span>Section 15.5.3.1</span></a> using the shortcut formula for a 2×2 table.</p>
</div>
<p>Let us consider two attributes <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, where <span class="math inline">\(A\)</span> is divided into <span class="math inline">\(r\)</span> classes <span class="math inline">\(A_1, A_2, \ldots, A_r\)</span> and <span class="math inline">\(B\)</span> into <span class="math inline">\(s\)</span> classes <span class="math inline">\(B_1, B_2, \ldots, B_s\)</span>. The cell frequencies can be expressed in the form of an <span class="math inline">\(r \times s\)</span> contingency table as shown below.</p>
<div id="tbl-rscontingency" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="General form of an r x s contingency table" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rscontingency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.5: General form of an r x s contingency table
</figcaption>
<div aria-describedby="tbl-rscontingency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
A/B
</th>
<th style="text-align:center;">
A1
</th>
<th style="text-align:center;">
A2
</th>
<th style="text-align:center;">
. . .
</th>
<th style="text-align:center;">
Ar
</th>
<th style="text-align:center;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
B1
</td>
<td style="text-align:center;">
(A1 B1)
</td>
<td style="text-align:center;">
(A2 B1)
</td>
<td style="text-align:center;">
. . .
</td>
<td style="text-align:center;">
(Ar B<sub>1</sub>)
</td>
<td style="text-align:center;">
(B1)
</td>
</tr>
<tr>
<td style="text-align:center;">
B2
</td>
<td style="text-align:center;">
(A1 B2)
</td>
<td style="text-align:center;">
(A2 B2)
</td>
<td style="text-align:center;">
. . .
</td>
<td style="text-align:center;">
(Ar B2)
</td>
<td style="text-align:center;">
(B2)
</td>
</tr>
<tr>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
</tr>
<tr>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
</tr>
<tr>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
<td style="text-align:center;">
.
</td>
</tr>
<tr>
<td style="text-align:center;">
Bs
</td>
<td style="text-align:center;">
(A1 Bs)
</td>
<td style="text-align:center;">
(A2 Bs)
</td>
<td style="text-align:center;">
. . .
</td>
<td style="text-align:center;">
(Ar Bs)
</td>
<td style="text-align:center;">
(Bs)
</td>
</tr>
<tr>
<td style="text-align:center;">
Total
</td>
<td style="text-align:center;">
(A1)
</td>
<td style="text-align:center;">
(A2)
</td>
<td style="text-align:center;">
. . .
</td>
<td style="text-align:center;">
(Ar)
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math inline">\((A_i B_j)\)</span> = the number of items possessing both attributes <span class="math inline">\(A_i\)</span> (<span class="math inline">\(i = 1, 2, \ldots, r\)</span>) and <span class="math inline">\(B_j\)</span> (<span class="math inline">\(j = 1, 2, \ldots, s\)</span>)</p>
<p><span class="math inline">\((A_i)\)</span> = the number of items possessing attribute <span class="math inline">\(A_i\)</span> (<span class="math inline">\(i = 1, 2, \ldots, r\)</span>)</p>
<p><span class="math inline">\((B_j)\)</span> = the number of items possessing attribute <span class="math inline">\(B_j\)</span> (<span class="math inline">\(j = 1, 2, \ldots, s\)</span>)</p>
<p><span class="math inline">\(\sum (A_i) = \sum (B_j) = N\)</span> is the total frequency.</p>
</section>
<section id="expected-frequencies" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="expected-frequencies">Expected frequencies</h4>
<p>The expected frequency corresponding to each observed frequency <span class="math inline">\((A_i B_j)\)</span> is calculated from the formula:</p>
<p><span id="eq-expected"><span class="math display">\[E_{ij} = \frac{(A_i)(B_j)}{N} \tag{15.8}\]</span></span></p>
</section>
<section id="degrees-of-freedom" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="degrees-of-freedom">Degrees of freedom</h4>
<p>Degrees of freedom for an <span class="math inline">\(r \times s\)</span> contingency table = <span class="math inline">\((r - 1)(s - 1)\)</span>.</p>
</section>
<section id="test-procedure" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="test-procedure">Test procedure</h4>
<p>The null hypothesis to be tested is:</p>
<p><span class="math inline">\(H_0\)</span>: The two attributes under consideration are independent.</p>
<p>The alternative hypothesis is:</p>
<p><span class="math inline">\(H_1\)</span>: The two attributes under consideration are not independent.</p>
<p>The test statistic is:</p>
<p><span id="eq-chi-indep"><span class="math display">\[\chi^2 = \sum_{i=1}^{r} \sum_{j=1}^{s} \frac{\left( O_{ij} - E_{ij} \right)^2}{E_{ij}} \tag{15.9}\]</span></span></p>
<p>where <span class="math inline">\(O_{ij}\)</span> = observed frequencies, <span class="math inline">\(E_{ij}\)</span> = expected frequencies, <span class="math inline">\(r\)</span> = number of rows, and <span class="math inline">\(s\)</span> = number of columns.</p>
<p>It can be verified that <span class="math inline">\(\sum_{i=1}^{r} \sum_{j=1}^{s} O_{ij} = \sum_{i=1}^{r} \sum_{j=1}^{s} E_{ij}\)</span>.</p>
<p>Under the null hypothesis, the test statistic follows a chi-square distribution with <span class="math inline">\((r - 1)(s - 1)\)</span> degrees of freedom. The decision rule is the same as for the goodness-of-fit test.</p>
<div id="exm-conting2" class="theorem example">
<p><span class="theorem-title"><strong>Example 15.6</strong></span> In a survey, a random sample of 198 farms was classified into three classes according to tenure status (owned, rented, and mixed). They were also classified according to the level of soil fertility (high, moderate, and low). The results are given below. Test whether tenure status depends on soil fertility.</p>
<div id="tbl-conting2" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-conting2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.6: Classification of farms by tenure status and soil fertility
</figcaption>
<div aria-describedby="tbl-conting2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Owned</td>
<td style="text-align: center;">Rented</td>
<td style="text-align: center;">Mixed</td>
<td style="text-align: center;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center;">High</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">62</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Moderate</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">46</td>
</tr>
<tr class="even">
<td style="text-align: center;">Low</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">90</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">84</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">66</td>
<td style="text-align: center;">198</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Solution</strong></p>
<p>The expected value <span class="math inline">\(E_{ij}\)</span> for each cell is calculated by multiplying the corresponding row total and column total and dividing by the grand total. The expected frequencies are shown in <a href="#tbl-conting2exp" class="quarto-xref">Table&nbsp;<span>15.7</span></a>, and the calculation of the chi-square statistic is shown in <a href="#tbl-conting2calc" class="quarto-xref">Table&nbsp;<span>15.8</span></a>.</p>
<div id="tbl-conting2exp" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Expected frequencies for the tenure and fertility data" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-conting2exp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.7: Expected frequencies for the tenure and fertility data
</figcaption>
<div aria-describedby="tbl-conting2exp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
Owned
</th>
<th style="text-align:center;">
Rented
</th>
<th style="text-align:center;">
Mixed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
High
</td>
<td style="text-align:center;">
26.3
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
20.7
</td>
</tr>
<tr>
<td style="text-align:center;">
Moderate
</td>
<td style="text-align:center;">
19.5
</td>
<td style="text-align:center;">
11.2
</td>
<td style="text-align:center;">
15.3
</td>
</tr>
<tr>
<td style="text-align:center;">
Low
</td>
<td style="text-align:center;">
38.2
</td>
<td style="text-align:center;">
21.8
</td>
<td style="text-align:center;">
30
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-conting2calc" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap="Calculation of chi-square for independence of attributes" data-filters="parse-latex">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-conting2calc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.8: Calculation of chi-square for independence of attributes
</figcaption>
<div aria-describedby="tbl-conting2calc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class=" lightable-classic table table-bordered" style="font-family: Georgia; width: auto !important; margin-left: auto; margin-right: auto; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
<span class="math display">\[O_{ij}\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[E_{ij}\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[O_{ij} - E_{ij}\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[\left( O_{ij} - E_{ij} \right)^{2}\]</span>
</th>
<th style="text-align:center;">
<span class="math display">\[\frac{\left( O_{ij} - E_{ij} \right)^{2}}{E_{ij}}\]</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
26.3
</td>
<td style="text-align:center;">
13.7
</td>
<td style="text-align:center;">
187.6
</td>
<td style="text-align:center;">
7.1
</td>
</tr>
<tr>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
-3
</td>
<td style="text-align:center;">
9.2
</td>
<td style="text-align:center;">
0.6
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
20.7
</td>
<td style="text-align:center;">
-10.7
</td>
<td style="text-align:center;">
113.8
</td>
<td style="text-align:center;">
5.5
</td>
</tr>
<tr>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
19.5
</td>
<td style="text-align:center;">
2.5
</td>
<td style="text-align:center;">
6.2
</td>
<td style="text-align:center;">
0.3
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
11.2
</td>
<td style="text-align:center;">
-1.2
</td>
<td style="text-align:center;">
1.3
</td>
<td style="text-align:center;">
0.1
</td>
</tr>
<tr>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
15.3
</td>
<td style="text-align:center;">
-1.3
</td>
<td style="text-align:center;">
1.8
</td>
<td style="text-align:center;">
0.1
</td>
</tr>
<tr>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
38.2
</td>
<td style="text-align:center;">
-16.2
</td>
<td style="text-align:center;">
261.9
</td>
<td style="text-align:center;">
6.9
</td>
</tr>
<tr>
<td style="text-align:center;">
26
</td>
<td style="text-align:center;">
21.8
</td>
<td style="text-align:center;">
4.2
</td>
<td style="text-align:center;">
17.5
</td>
<td style="text-align:center;">
0.8
</td>
</tr>
<tr>
<td style="text-align:center;">
42
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
144
</td>
<td style="text-align:center;">
4.8
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
<span class="math display">\[\chi_{\text{cal}}^{2} =\]</span>
</td>
<td style="text-align:center;">
26.3
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="math inline">\(\chi^2_{\text{cal}}\)</span> = 26.3. The table value of chi-square for <span class="math inline">\((3 - 1)(3 - 1) = 4\)</span> degrees of freedom at the 5% level of significance is 9.488. Since the calculated value is greater than the table value, we reject the null hypothesis and conclude that the two attributes are not independent.</p>
</div>
</section>
</section>
<section id="chi-square-test-for-a-22-contingency-table" class="level3" data-number="15.5.3">
<h3 data-number="15.5.3" class="anchored" data-anchor-id="chi-square-test-for-a-22-contingency-table"><span class="header-section-number">15.5.3</span> Chi-square test for a 2×2 contingency table</h3>
<p>When the number of rows and columns are both equal to 2, the table is called a 2×2 contingency table. Consider two attributes <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> with classes <span class="math inline">\(A_1, A_2\)</span> and <span class="math inline">\(B_1, B_2\)</span> respectively, where <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span>, <span class="math inline">\(d\)</span> are the frequencies in each cell.</p>
<div id="tbl-2x2" class="bordered quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2x2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.9: General form of a 2×2 contingency table
</figcaption>
<div aria-describedby="tbl-2x2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-bordered caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">\(A_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(A_2\)</span></th>
<th style="text-align: center;">Row Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(B_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b\)</span></td>
<td style="text-align: center;"><span class="math inline">\(R_1 = a + b\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(B_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d\)</span></td>
<td style="text-align: center;"><span class="math inline">\(R_2 = c + d\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Column Total</td>
<td style="text-align: center;"><span class="math inline">\(C_1 = a + c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(C_2 = b + d\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n = a+b+c+d\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Here <span class="math inline">\(R_1, R_2\)</span> and <span class="math inline">\(C_1, C_2\)</span> are the row totals and column totals respectively, and <span class="math inline">\(n\)</span> is the total number of observations.</p>
<p>The null hypothesis is <span class="math inline">\(H_0\)</span>: the two attributes are independent. The alternative hypothesis is <span class="math inline">\(H_1\)</span>: the two attributes are not independent.</p>
<p>For a 2×2 contingency table, <span class="math inline">\(\chi^2\)</span> can be found directly using the shortcut formula:</p>
<p><span id="eq-chi-2x2"><span class="math display">\[\chi^2 = \frac{n\left( ad - bc \right)^2}{C_1 C_2 R_1 R_2} \tag{15.10}\]</span></span></p>
<p>Under the null hypothesis, the statistic follows a chi-square distribution with <span class="math inline">\((2 - 1)(2 - 1) = 1\)</span> degree of freedom.</p>
<section id="sec-yates" class="level4">
<h4 class="anchored" data-anchor-id="sec-yates">Yates’ correction for continuity</h4>
<p>In a 2×2 contingency table, the number of degrees of freedom is <span class="math inline">\((2 - 1)(2 - 1) = 1\)</span>. If any one of the cell frequencies is less than 5, then pooling would result in <span class="math inline">\(\chi^2\)</span> with 0 degrees of freedom, which is meaningless. In this case we apply a correction due to Yates, known as <strong>Yates’ correction for continuity</strong>. The correction is made by subtracting <span class="math inline">\(n/2\)</span> from the absolute value of <span class="math inline">\((ad - bc)\)</span>. The modified test statistic is:</p>
<p><span id="eq-yates"><span class="math display">\[\chi^2 = \frac{n\left( \left| ad - bc \right| - \dfrac{n}{2} \right)^2}{C_1 C_2 R_1 R_2} \tag{15.11}\]</span></span></p>
<div id="exm-yates1" class="theorem example">
<p><span class="theorem-title"><strong>Example 15.7</strong></span> This is the solution to the germination experiment introduced in <a href="#exm-conting1" class="quarto-xref">Example&nbsp;<span>15.5</span></a>.</p>
<p><span class="math inline">\(H_0\)</span>: The chemical treatment does not affect the germination rate of cotton seeds (the attributes are independent).</p>
<p><span class="math inline">\(H_1\)</span>: The chemical treatment affects the germination rate of cotton seeds.</p>
<p>Applying Yates’ correction with <span class="math inline">\(a = 118\)</span>, <span class="math inline">\(b = 22\)</span>, <span class="math inline">\(c = 120\)</span>, <span class="math inline">\(d = 40\)</span>, <span class="math inline">\(n = 300\)</span>:</p>
<p><span class="math display">\[\chi^2 = \frac{300\left( \left| 118 \times 40 - 22 \times 120 \right| - \dfrac{300}{2} \right)^2}{238 \times 62 \times 140 \times 160}\]</span></p>
<p><span class="math display">\[= 3.38\]</span></p>
<p><span class="math inline">\(\chi^2_{\text{cal}}\)</span> = 3.38. The table value of chi-square for <span class="math inline">\((2 - 1)(2 - 1) = 1\)</span> degree of freedom at the 5% level of significance is 3.841. Since the calculated value is less than the table value, we do not have enough evidence to reject the null hypothesis. The chemical treatment does not improve the germination rate of cotton seeds significantly.</p>
</div>
<div id="exr-yates1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 15.5</strong></span> In an experiment on the effect of a growth regulator on fruit setting in muskmelon, the following results were obtained. Test whether fruit setting in muskmelon and the application of the growth regulator are independent at the 5% level.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Fruit set</th>
<th style="text-align: center;">Fruit not set</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Treated</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">Control</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">21</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="chi-square-test-for-a-population-variance" class="level3" data-number="15.5.4">
<h3 data-number="15.5.4" class="anchored" data-anchor-id="chi-square-test-for-a-population-variance"><span class="header-section-number">15.5.4</span> Chi-square test for a population variance</h3>
<p>Consider a normal population with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>, where both are unknown. We take a random sample of size <span class="math inline">\(n\)</span> from the population and want to test whether the population variance <span class="math inline">\(\sigma^2\)</span> is equal to a known constant <span class="math inline">\(\sigma_0^2\)</span>, based on the sample variance.</p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\sigma^2\)</span> = <span class="math inline">\(\sigma_0^2\)</span></p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\sigma^2\)</span> &gt; <span class="math inline">\(\sigma_0^2\)</span></p>
<p>The test statistic is:</p>
<p><span id="eq-chi-var"><span class="math display">\[\chi^2 = \frac{(n - 1)s^2}{\sigma_0^2} \tag{15.12}\]</span></span></p>
<p>where <span class="math inline">\(s^2 = \dfrac{\sum_{i=1}^{n}\left( x_i - \overline{x} \right)^2}{n - 1}\)</span> is the sample variance.</p>
<p>Under the null hypothesis, the test statistic follows a chi-square distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom. The decision rule is the same as for the goodness-of-fit test.</p>
<div id="exr-chivar1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 15.6</strong></span> Test the null hypothesis that <span class="math inline">\(\sigma^2\)</span> = 0.16 against the alternative hypothesis <span class="math inline">\(\sigma^2\)</span> &gt; 0.16, given that <span class="math inline">\(s^2\)</span> = 0.01719 for a random sample of size 11 from a normal population. (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
</div>
</section>
</section>
<section id="sec-ftest" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="sec-ftest"><span class="header-section-number">15.6</span> F-test for equality of two population variances</h2>
<p>Let there be two normally distributed populations with variances <span class="math inline">\(\sigma_1^2\)</span> and <span class="math inline">\(\sigma_2^2\)</span> respectively. Let samples of sizes <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> be taken from these populations. We want to test whether the two population variances are significantly different, based on the sample variances.</p>
<p>Null hypothesis, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\sigma_1^2\)</span> = <span class="math inline">\(\sigma_2^2\)</span></p>
<p>Alternative hypothesis, <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\sigma_1^2\)</span> &gt; <span class="math inline">\(\sigma_2^2\)</span></p>
<p>The test statistic (taking the larger sample variance in the numerator) is:</p>
<p><span id="eq-f"><span class="math display">\[F = \frac{s_1^2}{s_2^2}, \quad \text{where } s_1^2 &gt; s_2^2 \tag{15.13}\]</span></span></p>
<p>Under the null hypothesis, the test statistic follows an <span class="math inline">\(F\)</span> distribution with <span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span> degrees of freedom.</p>
<section id="decision-rule-for-the-f-test" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="decision-rule-for-the-f-test">Decision rule for the F-test</h3>
<p>If the calculated value is greater than the table value of <span class="math inline">\(F\)</span> at the specified level of significance and the two degrees of freedom (that is, <span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span>), we reject the null hypothesis. You can see the F-table for 5% level of significance <a href="appendix5.html" class="quarto-xref"><span>Chapter 28</span></a>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The larger sample variance is always placed in the numerator so that <span class="math inline">\(F \geq 1\)</span>. If <span class="math inline">\(s_2^2 &gt; s_1^2\)</span>, then the test statistic is <span class="math inline">\(F = \dfrac{s_2^2}{s_1^2}\)</span>, which follows an <span class="math inline">\(F\)</span> distribution with <span class="math inline">\(n_2 - 1\)</span> and <span class="math inline">\(n_1 - 1\)</span> degrees of freedom.</p>
</div>
</div>
<div id="exr-fvar1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 15.7</strong></span> For a random sample from one normal population, <span class="math inline">\(n_1\)</span> = 11 and <span class="math inline">\(s_1^2\)</span> = 21.87. For another random sample from a second normal population, <span class="math inline">\(n_2\)</span> = 8 and <span class="math inline">\(s_2^2\)</span> = 15.36. Test the equality of variances. (<span class="math inline">\(\alpha\)</span> = 0.05)</p>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Historical Insights">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Historical Insights
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>A brewer, a secret, and the birth of the t distribution</strong></p>
<p>At the beginning of the twentieth century, the Guinness brewery in Dublin employed a young Oxford-trained chemist named <strong>William Sealy Gosset</strong>. His job was to bring scientific rigour to brewing, judging the quality of barley and hops from only a handful of samples. The trouble was that the statistical methods of the day assumed large samples, while Gosset rarely had more than a few observations to work with. The normal-distribution based tests simply did not behave well for such small samples.</p>
<p>Working through this problem, Gosset derived the exact sampling distribution of the mean when the population standard deviation is unknown and must be estimated from a small sample. This distribution, slightly flatter than the normal curve with heavier tails, is what we now call the <strong>t distribution</strong>. It was one of the first genuinely small-sample results in statistics.</p>
<p>Guinness, however, treated its research as a trade secret and did not allow employees to publish under their own names, fearing that competitors would learn how the brewery used statistics. Gosset was therefore obliged to publish his 1908 paper in the journal <em>Biometrika</em> under the modest pen name <strong>“Student”</strong>. <span class="citation" data-cites="Student1908">(<a href="references.html#ref-Student1908" role="doc-biblioref">Student 1908</a>)</span> For this reason the distribution has been known ever since as <strong>Student’s t distribution</strong>, and the associated test as <strong>Student’s t-test</strong>, even though there was never any student involved. The true author was a brewer solving a very practical problem, one pint of statistics at a time.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Quotes to Inspire">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Quotes to Inspire
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>“Like dreams, statistics are a form of wish fulfillment.”</strong><br>
<strong>- Jean Baudrillard</strong></p>
</div>
</div>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">15.7</span> Chapter Summary</h2>
<section id="fill-in-the-blanks" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fill-in-the-blanks">Fill in the blanks</h3>
<p>Answers are given at the end of the chapter.</p>
<ol type="1">
<li><p>A sample with size less than __________ is generally called a small sample.</p></li>
<li><p>The study of sampling distributions for small samples is called __________ sample theory.</p></li>
<li><p>The three important sampling distributions used in small-sample tests are the __________, __________, and __________ distributions.</p></li>
<li><p>Student’s <span class="math inline">\(t\)</span>-test is mainly used when the population standard deviation is __________.</p></li>
<li><p>One of the important assumptions of the <span class="math inline">\(t\)</span>-test is that the parent population is __________.</p></li>
<li><p>The sample used in a <span class="math inline">\(t\)</span>-test should be a __________ sample.</p></li>
<li><p>For a one-sample <span class="math inline">\(t\)</span>-test, the degrees of freedom are __________.</p></li>
<li><p>The null hypothesis for testing a single population mean is <span class="math inline">\(H_0:\mu=\)</span> __________.</p></li>
<li><p>The test statistic for a single population mean is based on the sample mean and sample __________.</p></li>
<li><p>When comparing two means with equal population variances, the __________ variance is used.</p></li>
<li><p>When two population variances are unequal, the appropriate test for comparing two means is the __________ <span class="math inline">\(t\)</span>-test.</p></li>
<li><p>The degrees of freedom for the equal-variance two-sample <span class="math inline">\(t\)</span>-test are __________.</p></li>
<li><p>The degrees of freedom for the Welch <span class="math inline">\(t\)</span>-test are calculated using the __________ formula.</p></li>
<li><p>The paired <span class="math inline">\(t\)</span>-test is used when the two observations being compared are __________.</p></li>
<li><p>In a paired <span class="math inline">\(t\)</span>-test, <span class="math inline">\(d_i\)</span> represents the __________ between the two paired observations.</p></li>
<li><p>The degrees of freedom for a paired <span class="math inline">\(t\)</span>-test are __________.</p></li>
<li><p>To test whether a population correlation coefficient is zero, the test statistic follows a __________ distribution.</p></li>
<li><p>The null hypothesis for testing the significance of a correlation coefficient is <span class="math inline">\(H_0:\rho=\)</span> __________.</p></li>
<li><p>The degrees of freedom for testing the significance of a correlation coefficient are __________.</p></li>
<li><p>The chi-square test is based on the __________ distribution.</p></li>
<li><p>Chi-square tests are generally classified as __________-parametric tests.</p></li>
<li><p>The chi-square test for goodness of fit compares observed frequencies with __________ frequencies.</p></li>
<li><p>The chi-square goodness-of-fit test was developed by __________.</p></li>
<li><p>The chi-square goodness-of-fit statistic is calculated using the differences between __________ and __________ frequencies.</p></li>
<li><p>In the goodness-of-fit test, if no parameter is estimated from the data, the degrees of freedom are __________.</p></li>
<li><p>The chi-square goodness-of-fit test is a __________-tailed test.</p></li>
<li><p>The chi-square test of independence is used to determine whether two __________ are independent.</p></li>
<li><p>Data for a chi-square test of independence are usually arranged in a __________ table.</p></li>
<li><p>The expected frequency in a contingency table is obtained by multiplying the corresponding __________ total and __________ total and dividing by the grand total.</p></li>
<li><p>The degrees of freedom for an <span class="math inline">\(r\times s\)</span> contingency table are __________.</p></li>
<li><p>In a 2×2 contingency table, the degrees of freedom are __________.</p></li>
<li><p>Yates’ correction is used for a __________ contingency table when a cell frequency is less than 5.</p></li>
<li><p>In the chi-square test for a population variance, the null hypothesis is <span class="math inline">\(H_0:\sigma^2=\)</span> __________.</p></li>
<li><p>The test statistic for testing a population variance follows a chi-square distribution with __________ degrees of freedom.</p></li>
<li><p>The <span class="math inline">\(F\)</span>-test is used to test the equality of two population __________.</p></li>
<li><p>In the <span class="math inline">\(F\)</span>-test, the __________ sample variance is placed in the numerator.</p></li>
<li><p>Placing the larger sample variance in the numerator ensures that <span class="math inline">\(F\)</span> is __________ than or equal to 1.</p></li>
<li><p>The degrees of freedom of the <span class="math inline">\(F\)</span> distribution are __________ and __________.</p></li>
<li><p>The <span class="math inline">\(t\)</span> distribution was developed by William Sealy __________.</p></li>
<li><p>Gosset published his work under the pen name __________.</p></li>
</ol>
</section>
<section id="short-answer-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="short-answer-questions">Short-answer questions</h3>
<ol type="1">
<li><p>Define a small sample.</p></li>
<li><p>What is small sample theory?</p></li>
<li><p>State the assumptions of the <span class="math inline">\(t\)</span>-test.</p></li>
<li><p>Explain why the <span class="math inline">\(t\)</span> distribution is used when the population standard deviation is unknown.</p></li>
<li><p>State the null and alternative hypotheses for testing a single population mean.</p></li>
<li><p>Derive or explain the test statistic for a single population mean.</p></li>
<li><p>What are the degrees of freedom in a one-sample <span class="math inline">\(t\)</span>-test?</p></li>
<li><p>State the decision rules for one-tailed and two-tailed <span class="math inline">\(t\)</span>-tests.</p></li>
<li><p>Explain the test for equality of two means when the population variances are equal.</p></li>
<li><p>What is pooled variance?</p></li>
<li><p>Why is pooled variance used when population variances are assumed equal?</p></li>
<li><p>Explain the Welch <span class="math inline">\(t\)</span>-test.</p></li>
<li><p>When should the Welch <span class="math inline">\(t\)</span>-test be used?</p></li>
<li><p>Distinguish between the equal-variance <span class="math inline">\(t\)</span>-test and Welch <span class="math inline">\(t\)</span>-test.</p></li>
<li><p>What is a paired <span class="math inline">\(t\)</span>-test?</p></li>
<li><p>Give an agricultural example where a paired <span class="math inline">\(t\)</span>-test can be used.</p></li>
<li><p>Explain how paired observations are converted into differences.</p></li>
<li><p>State the test statistic for the paired <span class="math inline">\(t\)</span>-test.</p></li>
<li><p>What are the degrees of freedom for a paired <span class="math inline">\(t\)</span>-test?</p></li>
<li><p>Explain the test for the significance of a correlation coefficient.</p></li>
<li><p>State the null and alternative hypotheses for testing a correlation coefficient.</p></li>
<li><p>What are the degrees of freedom for testing the significance of a correlation coefficient?</p></li>
<li><p>Define the chi-square distribution.</p></li>
<li><p>State the assumptions of the chi-square test.</p></li>
<li><p>Why are chi-square tests called non-parametric or distribution-free tests?</p></li>
<li><p>What is meant by degrees of freedom in a chi-square test?</p></li>
<li><p>List the three important chi-square tests discussed in the chapter.</p></li>
<li><p>Explain the chi-square goodness-of-fit test.</p></li>
<li><p>State the null and alternative hypotheses for the goodness-of-fit test.</p></li>
<li><p>Explain the difference between observed and expected frequencies.</p></li>
<li><p>State the degrees of freedom for the chi-square goodness-of-fit test.</p></li>
<li><p>Explain the chi-square test of independence.</p></li>
<li><p>What is a contingency table?</p></li>
<li><p>Explain how expected frequencies are calculated in a contingency table.</p></li>
<li><p>State the degrees of freedom for an <span class="math inline">\(r\times s\)</span> contingency table.</p></li>
<li><p>Explain the chi-square test for a 2×2 contingency table.</p></li>
<li><p>State the shortcut formula for a 2×2 contingency table.</p></li>
<li><p>What is Yates’ correction for continuity?</p></li>
<li><p>When is Yates’ correction applied?</p></li>
<li><p>Explain the chi-square test for a population variance.</p></li>
<li><p>State the assumptions required for testing a population variance using chi-square.</p></li>
<li><p>What is an <span class="math inline">\(F\)</span>-test?</p></li>
<li><p>Explain the procedure for testing equality of two population variances.</p></li>
<li><p>Why is the larger sample variance placed in the numerator in an <span class="math inline">\(F\)</span>-test?</p></li>
<li><p>State the degrees of freedom of the <span class="math inline">\(F\)</span> distribution used in the test.</p></li>
<li><p>Distinguish between <span class="math inline">\(t\)</span>, <span class="math inline">\(\chi^2\)</span>, and <span class="math inline">\(F\)</span> distributions.</p></li>
<li><p>Explain the historical contribution of William Sealy Gosset to small-sample statistics.</p></li>
</ol>
</section>
<section id="numerical-and-conceptual-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="numerical-and-conceptual-questions">Numerical and conceptual questions</h3>
<p>Answers are given at the end of the chapter.</p>
<ol type="1">
<li><p>A new variety of green gram is expected to produce 12 quintals per hectare. A random sample of 10 farmers’ fields gives yields of 14.3, 12.6, 13.7, 10.9, 13.7, 12, 11.4, 12, 12.6, and 13.1 quintals per hectare. Test whether the results confirm the expectation at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>The mean weekly sales of soap bars before an advertising campaign was 146.3 bars per store. After the campaign, the mean weekly sales in 22 stores was 153.7 with standard deviation 17.2. Test whether the advertising campaign was successful at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>Two sources of nitrogen, ammonium chloride and urea, were compared for paddy grain yield. Test whether the two sources differ in effectiveness at <span class="math inline">\(\alpha=0.05\)</span> using the data given in the chapter.</p></li>
<li><p>Explain why an <span class="math inline">\(F\)</span>-test is performed before choosing between the equal-variance and unequal-variance two-sample <span class="math inline">\(t\)</span>-tests.</p></li>
<li><p>Two related treatments are applied to the same experimental units. Explain why an ordinary two-sample <span class="math inline">\(t\)</span>-test is not appropriate and why a paired <span class="math inline">\(t\)</span>-test should be used.</p></li>
<li><p>Soil treatments A and B gave paired yields of 49, 53, 51, 52, 47, 50, 52, 53 and 52, 55, 52, 53, 50, 54, 54, 53 kg/plot, respectively. Test whether the treatments differ significantly at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>A stimulus administered to each of 12 patients produced changes in blood pressure of 5, 2, 8, -1, 3, 0, -2, 1, 5, 0, 4, and 6. Test whether the stimulus is associated with an increase in blood pressure at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>A correlation coefficient of 0.2 is obtained from 625 pairs of observations. Test whether the population correlation coefficient is significant.</p></li>
<li><p>A genetic cross produces observed frequencies 87, 29, 32, and 12 for four phenotypic classes. Test whether the observations agree with the theoretical 9:3:3:1 ratio at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>Observed frequencies of yeast cells are 103, 143, 98, 42, 8, and 6, while the corresponding expected frequencies are 106, 141, 93, 41, 14, and 5. Test the goodness of fit at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>A survey classifies farms according to tenure status and soil fertility. Test whether tenure status and soil fertility are independent using the contingency table given in the chapter.</p></li>
<li><p>For a 2×2 contingency table with frequencies <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span>, and <span class="math inline">\(d\)</span>, derive the shortcut formula for the chi-square statistic.</p></li>
<li><p>In a 2×2 contingency table, one of the cell frequencies is less than 5. Explain why Yates’ correction is required.</p></li>
<li><p>Test the null hypothesis <span class="math inline">\(\sigma^2=0.16\)</span> against the alternative <span class="math inline">\(\sigma^2&gt;0.16\)</span> when <span class="math inline">\(s^2=0.01719\)</span> and <span class="math inline">\(n=11\)</span> at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>Two samples from normal populations have <span class="math inline">\(n_1=11\)</span>, <span class="math inline">\(s_1^2=21.87\)</span>, <span class="math inline">\(n_2=8\)</span>, and <span class="math inline">\(s_2^2=15.36\)</span>. Test the equality of population variances at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>A sample of 15 observations has sample variance 12.5. Test whether the population variance is 10 at the 5% level using the appropriate chi-square test.</p></li>
<li><p>Two independent samples have sample variances 25 and 16. Explain which variance should be placed in the numerator of the <span class="math inline">\(F\)</span> statistic and why.</p></li>
<li><p>A sample correlation coefficient is <span class="math inline">\(r=0.35\)</span> based on 20 pairs of observations. Test whether the population correlation coefficient is significantly different from zero at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>A sample of 12 observations has mean 25 and standard deviation 4. Test whether the population mean is 22 at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>Two independent small samples have equal population variances. Explain which <span class="math inline">\(t\)</span>-test should be used and state its degrees of freedom.</p></li>
</ol>
</section>
<section id="important-formulae" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="important-formulae">Important formulae</h3>
<p>Sample variance:</p>
<p><span class="math display">\[
s^2=\frac{\sum_{i=1}^{n}(x_i-\bar{x})^2}{n-1}
\]</span></p>
<p>One-sample <span class="math inline">\(t\)</span> statistic:</p>
<p><span class="math display">\[
t=\frac{\bar{x}-\mu_0}{s/\sqrt{n}}
\]</span></p>
<p>Degrees of freedom for one-sample <span class="math inline">\(t\)</span>-test:</p>
<p><span class="math display">\[
df=n-1
\]</span></p>
<p>Pooled variance:</p>
<p><span class="math display">\[
s^2=\frac{(n_1-1)s_1^2+(n_2-1)s_2^2}{n_1+n_2-2}
\]</span></p>
<p>Two-sample <span class="math inline">\(t\)</span> statistic for equal variances:</p>
<p><span class="math display">\[
t=\frac{\bar{x}_1-\bar{x}_2}{s\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}
\]</span></p>
<p>Degrees of freedom for equal-variance two-sample <span class="math inline">\(t\)</span>-test:</p>
<p><span class="math display">\[
df=n_1+n_2-2
\]</span></p>
<p>Welch <span class="math inline">\(t\)</span> statistic:</p>
<p><span class="math display">\[
t=\frac{\bar{x}_1-\bar{x}_2}{\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}}
\]</span></p>
<p>Welch degrees of freedom:</p>
<p><span class="math display">\[
df=\frac{\left(\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}\right)^2}{\frac{s_1^4}{n_1^2(n_1-1)}+\frac{s_2^4}{n_2^2(n_2-1)}}
\]</span></p>
<p>Paired difference:</p>
<p><span class="math display">\[
d_i=x_i-y_i
\]</span></p>
<p>Mean paired difference:</p>
<p><span class="math display">\[
\bar{d}=\frac{\sum_{i=1}^{n}d_i}{n}
\]</span></p>
<p>Variance of paired differences:</p>
<p><span class="math display">\[
s^2=\frac{\sum_{i=1}^{n}(d_i-\bar{d})^2}{n-1}
\]</span></p>
<p>Paired <span class="math inline">\(t\)</span> statistic:</p>
<p><span class="math display">\[
t=\frac{\bar{d}}{s/\sqrt{n}}
\]</span></p>
<p>Degrees of freedom for paired <span class="math inline">\(t\)</span>-test:</p>
<p><span class="math display">\[
df=n-1
\]</span></p>
<p>Test statistic for significance of correlation coefficient:</p>
<p><span class="math display">\[
t=\frac{r\sqrt{n-2}}{\sqrt{1-r^2}}
\]</span></p>
<p>Degrees of freedom for correlation test:</p>
<p><span class="math display">\[
df=n-2
\]</span></p>
<p>Chi-square goodness-of-fit statistic:</p>
<p><span class="math display">\[
\chi^2=\sum_{i=1}^{n}\frac{(O_i-E_i)^2}{E_i}
\]</span></p>
<p>Degrees of freedom for goodness-of-fit test:</p>
<p><span class="math display">\[
df=n-1
\]</span></p>
<p>Expected frequency in an <span class="math inline">\(r\times s\)</span> contingency table:</p>
<p><span class="math display">\[
E_{ij}=\frac{(A_i)(B_j)}{N}
\]</span></p>
<p>Chi-square test of independence:</p>
<p><span class="math display">\[
\chi^2=\sum_{i=1}^{r}\sum_{j=1}^{s}\frac{(O_{ij}-E_{ij})^2}{E_{ij}}
\]</span></p>
<p>Degrees of freedom for an <span class="math inline">\(r\times s\)</span> contingency table:</p>
<p><span class="math display">\[
df=(r-1)(s-1)
\]</span></p>
<p>Chi-square statistic for a 2×2 contingency table:</p>
<p><span class="math display">\[
\chi^2=\frac{n(ad-bc)^2}{C_1C_2R_1R_2}
\]</span></p>
<p>Yates’ corrected chi-square statistic:</p>
<p><span class="math display">\[
\chi^2=\frac{n\left(|ad-bc|-\frac{n}{2}\right)^2}{C_1C_2R_1R_2}
\]</span></p>
<p>Chi-square test statistic for population variance:</p>
<p><span class="math display">\[
\chi^2=\frac{(n-1)s^2}{\sigma_0^2}
\]</span></p>
<p>Degrees of freedom for chi-square variance test:</p>
<p><span class="math display">\[
df=n-1
\]</span></p>
<p><span class="math inline">\(F\)</span> statistic:</p>
<p><span class="math display">\[
F=\frac{s_1^2}{s_2^2},\quad s_1^2&gt;s_2^2
\]</span></p>
<p>Degrees of freedom for <span class="math inline">\(F\)</span> test:</p>
<p><span class="math display">\[
df_1=n_1-1,\qquad df_2=n_2-1
\]</span></p>
</section>
<section id="quick-revision" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="quick-revision">Quick revision</h3>
<ul>
<li>Small sample → generally <span class="math inline">\(n&lt;30\)</span>.</li>
<li>Small sample theory → study of sampling distributions for small samples.</li>
<li>Important small-sample distributions → <span class="math inline">\(t\)</span>, <span class="math inline">\(\chi^2\)</span>, and <span class="math inline">\(F\)</span>.</li>
<li>Student’s <span class="math inline">\(t\)</span>-test → used mainly for small samples when <span class="math inline">\(\sigma\)</span> is unknown.</li>
<li>Basic <span class="math inline">\(t\)</span>-test assumptions → normal parent population, random sample, and unknown population standard deviation.</li>
<li>One-sample <span class="math inline">\(t\)</span>-test → tests a population mean against a specified value.</li>
<li>One-sample <span class="math inline">\(t\)</span> degrees of freedom → <span class="math inline">\(n-1\)</span>.</li>
<li>Two-sample <span class="math inline">\(t\)</span>-test → compares two population means.</li>
<li>Equal variances → use pooled variance.</li>
<li>Equal-variance two-sample <span class="math inline">\(t\)</span> degrees of freedom → <span class="math inline">\(n_1+n_2-2\)</span>.</li>
<li>Unequal variances → use Welch’s <span class="math inline">\(t\)</span>-test.</li>
<li>Welch’s <span class="math inline">\(t\)</span>-test uses separate sample variance terms.</li>
<li>Welch’s degrees of freedom are generally not an integer and are calculated using the Welch-Satterthwaite formula.</li>
<li>Paired <span class="math inline">\(t\)</span>-test → compares two related observations.</li>
<li>Examples of paired data → before and after measurements on the same experimental unit.</li>
<li>Paired <span class="math inline">\(t\)</span>-test is performed on the differences within pairs.</li>
<li>Paired <span class="math inline">\(t\)</span> degrees of freedom → <span class="math inline">\(n-1\)</span>.</li>
<li>Correlation test → tests whether the population correlation coefficient is zero.</li>
<li>For the correlation test, <span class="math inline">\(H_0:\rho=0\)</span>.</li>
<li>Correlation test degrees of freedom → <span class="math inline">\(n-2\)</span>.</li>
<li>Chi-square tests → based on the chi-square distribution.</li>
<li>Chi-square tests in this chapter are non-parametric or distribution-free tests.</li>
<li>Important chi-square tests → goodness of fit, independence of attributes, and population variance.</li>
<li>Goodness-of-fit test → compares observed and expected frequencies.</li>
<li>Goodness-of-fit null hypothesis → no significant difference between theory and observation.</li>
<li>Goodness-of-fit test is right-tailed.</li>
<li>Goodness-of-fit degrees of freedom → <span class="math inline">\(n-1\)</span> when no parameter is estimated.</li>
<li>Independence test → determines whether two attributes are independent.</li>
<li>Contingency table → arrangement of frequencies for combinations of categorical attributes.</li>
<li>Expected frequency → row total × column total ÷ grand total.</li>
<li><span class="math inline">\(r\times s\)</span> contingency table degrees of freedom → <span class="math inline">\((r-1)(s-1)\)</span>.</li>
<li>2×2 contingency table degrees of freedom → 1.</li>
<li>Yates’ correction → used for a 2×2 table when a cell frequency is less than 5, as specified in this chapter.</li>
<li>Population variance test → tests a specified value of <span class="math inline">\(\sigma^2\)</span>.</li>
<li>Chi-square variance statistic → <span class="math inline">\(\frac{(n-1)s^2}{\sigma_0^2}\)</span>.</li>
<li><span class="math inline">\(F\)</span>-test → tests equality of two population variances.</li>
<li>Larger sample variance → always placed in the numerator of <span class="math inline">\(F\)</span>.</li>
<li>Therefore, <span class="math inline">\(F\geq1\)</span>.</li>
<li><span class="math inline">\(F\)</span> degrees of freedom → <span class="math inline">\(n_1-1\)</span> and <span class="math inline">\(n_2-1\)</span>.</li>
<li>In hypothesis testing, compare the calculated statistic with the appropriate table value.</li>
<li>For a two-tailed <span class="math inline">\(t\)</span>-test → reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(|t|\)</span> exceeds the critical value.</li>
<li>For a right-tailed <span class="math inline">\(t\)</span>-test → reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(t\)</span> exceeds the critical value.</li>
<li>For a left-tailed <span class="math inline">\(t\)</span>-test → reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(t\)</span> is less than the negative critical value.</li>
<li>For chi-square tests → reject <span class="math inline">\(H_0\)</span> when calculated <span class="math inline">\(\chi^2\)</span> exceeds the table value.</li>
<li>For the <span class="math inline">\(F\)</span>-test → reject <span class="math inline">\(H_0\)</span> when calculated <span class="math inline">\(F\)</span> exceeds the table value.</li>
<li>William Sealy Gosset developed the <span class="math inline">\(t\)</span> distribution and published under the name “Student”.</li>
<li>Student’s <span class="math inline">\(t\)</span> distribution has heavier tails than the normal distribution.</li>
</ul>
</section>
<section id="answers-to-fill-in-the-blanks" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="answers-to-fill-in-the-blanks">Answers to fill in the blanks</h3>
<ol type="1">
<li>30 · 2. Small · 3. <span class="math inline">\(\chi^2\)</span>; <span class="math inline">\(F\)</span>; <span class="math inline">\(t\)</span> · 4. Unknown · 5. Normal · 6. Random · 7. <span class="math inline">\(n-1\)</span> · 8. <span class="math inline">\(\mu_0\)</span> · 9. Standard deviation · 10. Pooled · 11. Welch · 12. <span class="math inline">\(n_1+n_2-2\)</span> · 13. Welch-Satterthwaite · 14. Related · 15. Difference · 16. <span class="math inline">\(n-1\)</span> · 17. <span class="math inline">\(t\)</span> · 18. 0 · 19. <span class="math inline">\(n-2\)</span> · 20. Chi-square · 21. Non · 22. Expected · 23. Karl Pearson · 24. Observed; expected · 25. <span class="math inline">\(n-1\)</span> · 26. Right · 27. Attributes · 28. Contingency · 29. Row; column · 30. <span class="math inline">\((r-1)(s-1)\)</span> · 31. 1 · 32. 2×2 · 33. <span class="math inline">\(\sigma_0^2\)</span> · 34. <span class="math inline">\(n-1\)</span> · 35. Variances · 36. Larger · 37. Greater · 38. <span class="math inline">\(n_1-1\)</span>; <span class="math inline">\(n_2-1\)</span> · 39. Gosset · 40. Student</li>
</ol>
</section>
<section id="solutions-to-numerical-and-conceptual-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="solutions-to-numerical-and-conceptual-questions">Solutions to numerical and conceptual questions</h3>
<ol type="1">
<li><p>Given <span class="math inline">\(n=10\)</span>, <span class="math inline">\(\bar{x}=12.63\)</span>, <span class="math inline">\(s=1.0853\)</span>, <span class="math inline">\(\mu_0=12\)</span>. Using <a href="#eq-t-single" class="quarto-xref">Equation&nbsp;<span>15.1</span></a>, <span class="math inline">\(t=\frac{12.63-12}{1.0853/\sqrt{10}}=1.835\)</span>, with <span class="math inline">\(df=9\)</span>. At <span class="math inline">\(\alpha=0.05\)</span> (two-tailed), the table value is 2.262; since <span class="math inline">\(|1.835|&lt;2.262\)</span>, we do not reject <span class="math inline">\(H_0\)</span>. There is insufficient evidence that the mean yield differs from 12 quintals per hectare.</p></li>
<li><p>Given <span class="math inline">\(n=22\)</span>, <span class="math inline">\(\bar{x}=153.7\)</span>, <span class="math inline">\(s=17.2\)</span>, <span class="math inline">\(\mu_0=146.3\)</span>. To test whether the campaign was successful, <span class="math inline">\(H_0:\mu=146.3\)</span> and <span class="math inline">\(H_1:\mu&gt;146.3\)</span> (right-tailed). Using <a href="#eq-t-single" class="quarto-xref">Equation&nbsp;<span>15.1</span></a>, <span class="math inline">\(t=\frac{153.7-146.3}{17.2/\sqrt{22}}\approx2.02\)</span>, with <span class="math inline">\(df=21\)</span>. At <span class="math inline">\(\alpha=0.05\)</span>, the one-tailed critical value is approximately 1.721; since <span class="math inline">\(2.02&gt;1.721\)</span>, we reject <span class="math inline">\(H_0\)</span>. There is significant evidence that the advertising campaign increased weekly sales.</p></li>
<li><p>The two treatments are applied to independent groups, so an independent two-sample <span class="math inline">\(t\)</span>-test is appropriate. First test the equality of the population variances using the <span class="math inline">\(F\)</span>-test. If the variances are homogeneous, use <a href="#eq-t-two-equal" class="quarto-xref">Equation&nbsp;<span>15.2</span></a> with the pooled variance; if unequal, use Welch’s test, <a href="#eq-t-welch" class="quarto-xref">Equation&nbsp;<span>15.3</span></a>. The decision is made by comparing the calculated <span class="math inline">\(t\)</span> with the appropriate critical value.</p></li>
<li><p>The equal-variance two-sample <span class="math inline">\(t\)</span>-test assumes <span class="math inline">\(\sigma_1^2=\sigma_2^2\)</span>, so the equality of population variances should first be assessed. The <span class="math inline">\(F\)</span>-test is used for this purpose: if the variances can be regarded as equal, the pooled-variance <span class="math inline">\(t\)</span>-test is used; if unequal, Welch’s <span class="math inline">\(t\)</span>-test is used.</p></li>
<li><p>When two observations are obtained from the same experimental unit, the observations are related and are not independent, so the analysis should focus on the within-unit differences rather than treating the two sets as independent samples. The paired <span class="math inline">\(t\)</span>-test is appropriate because it tests whether the mean paired difference is significantly different from zero.</p></li>
<li><p>For each plot, <span class="math inline">\(d_i=A_i-B_i\)</span>, giving <span class="math inline">\(\bar{d}=-2\)</span> and <span class="math inline">\(s=1.309\)</span>. Using <a href="#eq-t-paired" class="quarto-xref">Equation&nbsp;<span>15.5</span></a>, <span class="math inline">\(t=\frac{-2}{1.309/\sqrt{8}}=-4.321\)</span>, with <span class="math inline">\(df=7\)</span>. At <span class="math inline">\(\alpha=0.05\)</span>, the two-tailed critical value is 2.365; since <span class="math inline">\(|-4.321|&gt;2.365\)</span>, we reject <span class="math inline">\(H_0\)</span>. There is a significant difference between treatments A and B; since <span class="math inline">\(\bar{d}\)</span> is negative, treatment B produced the higher mean yield.</p></li>
<li><p>Let <span class="math inline">\(d\)</span> denote the change in blood pressure, so <span class="math inline">\(H_0:\mu_d=0\)</span> and <span class="math inline">\(H_1:\mu_d&gt;0\)</span>. The observed differences are <span class="math inline">\(5,2,8,-1,3,0,-2,1,5,0,4,6\)</span>, with mean <span class="math inline">\(\bar{d}=\frac{31}{12}=2.583\)</span> and sample standard deviation <span class="math inline">\(s=3.088\)</span>. Using <a href="#eq-t-paired" class="quarto-xref">Equation&nbsp;<span>15.5</span></a>, <span class="math inline">\(t=\frac{2.583}{3.088/\sqrt{12}}\approx2.90\)</span>, with <span class="math inline">\(df=11\)</span>. At <span class="math inline">\(\alpha=0.05\)</span> for a one-tailed test, the critical value is approximately 1.796; since <span class="math inline">\(2.90&gt;1.796\)</span>, we reject <span class="math inline">\(H_0\)</span>. There is significant evidence that the stimulus is associated with an increase in blood pressure.</p></li>
<li><p>Given <span class="math inline">\(r=0.2\)</span>, <span class="math inline">\(n=625\)</span>, so <span class="math inline">\(H_0:\rho=0\)</span> and <span class="math inline">\(H_1:\rho\neq0\)</span>. Using <a href="#eq-t-corr" class="quarto-xref">Equation&nbsp;<span>15.6</span></a>, <span class="math inline">\(t=\frac{0.2\sqrt{623}}{\sqrt{1-0.2^2}}=5.095\)</span>, with <span class="math inline">\(df=623\)</span>. At the 5% level, the critical value is approximately 1.96; since <span class="math inline">\(5.095&gt;1.96\)</span>, we reject <span class="math inline">\(H_0\)</span>. There is a significant correlation in the population.</p></li>
<li><p>The observed frequencies are <span class="math inline">\(87,29,32,12\)</span> with expected ratio <span class="math inline">\(9:3:3:1\)</span> and <span class="math inline">\(N=160\)</span>, giving expected frequencies <span class="math inline">\(90,30,30,10\)</span>. Using <a href="#eq-chi-gof" class="quarto-xref">Equation&nbsp;<span>15.7</span></a>, <span class="math inline">\(\chi^2=\sum\frac{(O-E)^2}{E}=0.667\)</span>, with <span class="math inline">\(df=3\)</span>. At <span class="math inline">\(\alpha=0.05\)</span>, <span class="math inline">\(\chi^2_{0.05,3}=7.815\)</span>; since <span class="math inline">\(0.667&lt;7.815\)</span>, we do not reject <span class="math inline">\(H_0\)</span>. The observed data agree with the theoretical 9:3:3:1 ratio.</p></li>
<li><p>Using <a href="#eq-chi-gof" class="quarto-xref">Equation&nbsp;<span>15.7</span></a> with the given observed and expected frequencies, <span class="math inline">\(\chi^2=\frac{(103-106)^2}{106}+\frac{(143-141)^2}{141}+\frac{(98-93)^2}{93}+\frac{(42-41)^2}{41}+\frac{(8-14)^2}{14}+\frac{(6-5)^2}{5}\approx3.18\)</span>, with <span class="math inline">\(df=5\)</span>. At <span class="math inline">\(\alpha=0.05\)</span>, the critical value is approximately 11.070; since <span class="math inline">\(3.18&lt;11.070\)</span>, we do not reject <span class="math inline">\(H_0\)</span>. The observed frequencies do not differ significantly from the expected frequencies.</p></li>
<li><p><span class="math inline">\(H_0\)</span>: the two attributes are independent; <span class="math inline">\(H_1\)</span>: the two attributes are not independent. Using <a href="#eq-expected" class="quarto-xref">Equation&nbsp;<span>15.8</span></a> for each cell, the calculated chi-square value given in the chapter is <span class="math inline">\(\chi^2_{\text{cal}}=26.3\)</span>. The table value at 4 degrees of freedom and <span class="math inline">\(\alpha=0.05\)</span> is <span class="math inline">\(\chi^2_{\text{tab}}=9.488\)</span>; since <span class="math inline">\(26.3&gt;9.488\)</span>, we reject <span class="math inline">\(H_0\)</span>. Tenure status and soil fertility are not independent.</p></li>
<li><p>For a 2×2 table with cell frequencies <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span>, <span class="math inline">\(d\)</span> and total <span class="math inline">\(n\)</span>, <a href="#eq-chi-2x2" class="quarto-xref">Equation&nbsp;<span>15.10</span></a> gives <span class="math inline">\(\chi^2=\frac{n(ad-bc)^2}{C_1C_2R_1R_2}\)</span>, where <span class="math inline">\(R_1,R_2\)</span> are the row totals and <span class="math inline">\(C_1,C_2\)</span> are the column totals. The degrees of freedom are <span class="math inline">\(df=(2-1)(2-1)=1\)</span>.</p></li>
<li><p>For a 2×2 table, the degrees of freedom are only 1. If a cell frequency is less than 5, the usual pooling procedure would eliminate the only degree of freedom, so Yates’ correction for continuity is used instead, giving the corrected statistic in <a href="#eq-yates" class="quarto-xref">Equation&nbsp;<span>15.11</span></a>.</p></li>
<li><p>Given <span class="math inline">\(\sigma_0^2=0.16\)</span>, <span class="math inline">\(s^2=0.01719\)</span>, <span class="math inline">\(n=11\)</span>, so <span class="math inline">\(H_0:\sigma^2=0.16\)</span> and <span class="math inline">\(H_1:\sigma^2&gt;0.16\)</span>. Using <a href="#eq-chi-var" class="quarto-xref">Equation&nbsp;<span>15.12</span></a>, <span class="math inline">\(\chi^2=\frac{10(0.01719)}{0.16}=1.0744\)</span>, with <span class="math inline">\(df=10\)</span>. Since the calculated value is much smaller than the right-tailed critical value at <span class="math inline">\(\alpha=0.05\)</span>, we do not reject <span class="math inline">\(H_0\)</span>. There is insufficient evidence that the population variance is greater than 0.16.</p></li>
<li><p>Given <span class="math inline">\(n_1=11\)</span>, <span class="math inline">\(s_1^2=21.87\)</span>, <span class="math inline">\(n_2=8\)</span>, <span class="math inline">\(s_2^2=15.36\)</span>, so <span class="math inline">\(H_0:\sigma_1^2=\sigma_2^2\)</span> and <span class="math inline">\(H_1:\sigma_1^2&gt;\sigma_2^2\)</span>. Since <span class="math inline">\(21.87&gt;15.36\)</span>, using <a href="#eq-f" class="quarto-xref">Equation&nbsp;<span>15.13</span></a>, <span class="math inline">\(F=\frac{21.87}{15.36}=1.424\)</span>, with <span class="math inline">\(df_1=10\)</span> and <span class="math inline">\(df_2=7\)</span>. The calculated value is less than the corresponding critical value at <span class="math inline">\(\alpha=0.05\)</span>, so we do not reject <span class="math inline">\(H_0\)</span>. There is insufficient evidence that the two population variances differ.</p></li>
<li><p>Given <span class="math inline">\(n=15\)</span>, <span class="math inline">\(s^2=12.5\)</span>, <span class="math inline">\(\sigma_0^2=10\)</span>, so <span class="math inline">\(H_0:\sigma^2=10\)</span> and <span class="math inline">\(H_1:\sigma^2\neq10\)</span>. Using <a href="#eq-chi-var" class="quarto-xref">Equation&nbsp;<span>15.12</span></a>, <span class="math inline">\(\chi^2=\frac{14(12.5)}{10}=17.5\)</span>, with <span class="math inline">\(df=14\)</span>. For a two-tailed test, compare the calculated value with the lower and upper chi-square critical values at <span class="math inline">\(\alpha/2=0.025\)</span>; the decision is made by determining whether 17.5 lies in the rejection region.</p></li>
<li><p>The larger sample variance should be placed in the numerator. Since <span class="math inline">\(25&gt;16\)</span>, using <a href="#eq-f" class="quarto-xref">Equation&nbsp;<span>15.13</span></a>, <span class="math inline">\(F=\frac{25}{16}=1.5625\)</span>; this ensures <span class="math inline">\(F\geq1\)</span> and simplifies the comparison with the upper-tail <span class="math inline">\(F\)</span> critical value.</p></li>
<li><p>Given <span class="math inline">\(r=0.35\)</span>, <span class="math inline">\(n=20\)</span>, so <span class="math inline">\(H_0:\rho=0\)</span> and <span class="math inline">\(H_1:\rho\neq0\)</span>. Using <a href="#eq-t-corr" class="quarto-xref">Equation&nbsp;<span>15.6</span></a>, <span class="math inline">\(t=\frac{0.35\sqrt{18}}{\sqrt{1-0.35^2}}\approx1.585\)</span>, with <span class="math inline">\(df=18\)</span>. At <span class="math inline">\(\alpha=0.05\)</span>, the two-tailed critical value is approximately 2.101; since <span class="math inline">\(1.585&lt;2.101\)</span>, we do not reject <span class="math inline">\(H_0\)</span>. There is insufficient evidence that the population correlation coefficient differs significantly from zero.</p></li>
<li><p>Given <span class="math inline">\(n=12\)</span>, <span class="math inline">\(\bar{x}=25\)</span>, <span class="math inline">\(s=4\)</span>, <span class="math inline">\(\mu_0=22\)</span>, so <span class="math inline">\(H_0:\mu=22\)</span> and <span class="math inline">\(H_1:\mu\neq22\)</span>. Using <a href="#eq-t-single" class="quarto-xref">Equation&nbsp;<span>15.1</span></a>, <span class="math inline">\(t=\frac{25-22}{4/\sqrt{12}}\approx2.598\)</span>, with <span class="math inline">\(df=11\)</span>. At <span class="math inline">\(\alpha=0.05\)</span>, the two-tailed critical value is approximately 2.201; since <span class="math inline">\(2.598&gt;2.201\)</span>, we reject <span class="math inline">\(H_0\)</span>. There is significant evidence that the population mean differs from 22.</p></li>
<li><p>When two independent small samples come from populations with equal variances, use the pooled two-sample <span class="math inline">\(t\)</span>-test, <a href="#eq-t-two-equal" class="quarto-xref">Equation&nbsp;<span>15.2</span></a>, with pooled variance <span class="math inline">\(s^2=\frac{(n_1-1)s_1^2+(n_2-1)s_2^2}{n_1+n_2-2}\)</span> and degrees of freedom <span class="math inline">\(df=n_1+n_2-2\)</span>.</p></li>
</ol>



<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Pearson1900" class="csl-entry" role="listitem">
Pearson, Karl. 1900. <span>“On the Criterion That a Given System of Deviations from the Probable in the Case of a Correlated System of Variables Is Such That It Can Be Reasonably Supposed to Have Arisen from Random Sampling.”</span> <em>Philosophical Magazine, Series 5</em> 50 (302): 157–75. <a href="https://doi.org/10.1080/14786440009463897">https://doi.org/10.1080/14786440009463897</a>.
</div>
<div id="ref-Student1908" class="csl-entry" role="listitem">
Student. 1908. <span>“The Probable Error of a Mean.”</span> <em>Biometrika</em> 6 (1): 1–25. <a href="https://doi.org/10.1093/biomet/6.1.1">https://doi.org/10.1093/biomet/6.1.1</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/www\.agrinoteskau\.com\/agstat-textbook\.html");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./largeSampletest.html" class="pagination-link" aria-label="Large sample test">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Large sample test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./designofexperiments.html" class="pagination-link" aria-label="Design of experiments">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Design of experiments</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Published by PAPAYA publishing division of <a href="https://www.statoberry.com/papaya"><img src=".\images/statoberry.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>   
    <div class="nav-footer-center">
<p><a href="https://www.statoberry.com/papaya"><img src=".\images/papayalogo.png" class="img-fluid" style="width: auto; height: 90px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>
    <div class="nav-footer-right">
<p>Licenced under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC-BY-NC-ND 4.0 Int License</a> <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img src=".\images/cclogo.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a> Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>